### ISSUE TITLE
Fresh water crafting

### ISSUE THREAD

**Issue by xsi93** [MatrexsVigil/harvestcraft#1]
There is a bug in 1.7.10h version, you get only 1 fresh water regardless the config amount of it.
To craft fresh water from water bucket there are two recipes: one with all listAllwater (getting only 1 fresh water), the other with vanilla water bucket (getting the config amount of fresh water) and is always prioritized the first.
Is there a way to fix it?
![pam bug](https://cloud.githubusercontent.com/assets/8198874/7107385/68dee6a0-e164-11e4-8162-64a1a9c4fdf3.png)

**Comment by BraynStorm** [comment]
Same bug. No idea how to fix it...

**Comment by Unknown-Zombie** [comment]
Fresh Water recipe still ignores config settings in 1.7.10j

**Comment by Unknown-Zombie** [comment]
I'm still having this issue in 1.7.10k.

When looking up the recipe for Fresh Water in NEI there are for some reason 2 recipes registered. Like the screenshot that xsi93 posted above, the recipe at the top (which takes precedence) cycles through all members of the listAllWater oreDict entry and any of those items only returns one FreshWater. The second recipe shows only the vanilla Minecraft Water Bucket, and returns the amount of FreshWater set in harvestcraft.cfg file.

**Comment by Aeroxia** [comment]
This is still not working, config is completely ignored, always 1 fresh water even with vanilla water bucket.
