### ISSUE TITLE
[1.12.2c] Green Bean Casserole is uncraftable

### ISSUE THREAD

**Issue by Luke616** [MatrexsVigil/harvestcraft#100]
Title, I presume this is due to the item being registered as harvestcraft:greenbeencasseroleitem (misspelled with been instead of a bean)

**Comment by Luke616** [comment]
Not sure if I should make a new issue - found a few more uncraftable items and also spotted a couple spelling errors. There might be more than just these, but this is what I saw when going through a bunch of your foods for another mod's configs. This is version 1.12.2c once again:

UNCRAFTABLE:
	Chicken and Garlic
	Green Bean Casserole
	Sauced Lamb Kebab

MISSPELLED DISPLAY NAME:
	Three Been Salad (should be Three Bean Salad)
	Grapfruit Juice (should be Grapefruit Juice)
	
MISSPELLED INTERNAL NAME: 
(not sure if you should fix these or leave them, may break some people's custom config files and cause item deletion - definitely put it in the patch notes if you do.)
	harvestcraft:greenbeencasseroleitem (should be greenbeancasserole)
	harvestcraft:lemonaideitem (should be lemonadeitem)

I'll post again / update if I see anything else. Huge fan of harvestcraft btw, thanks for the excellent mod.

**Comment by MatrexsVigil** [comment]
Thank you!  Fixed in 1.12.2d
