### ISSUE TITLE
Salt Recipes

### ISSUE THREAD

**Issue by Chunkey** [MatrexsVigil/harvestcraft#102]
Unidict is unifying my salts so all salt becomes mekanism salt. This works for some recipes that accept anysalt but many recipes require pam's salt. Is there anyway for all of the recipes to be updated to accept anysalt? Thanks

To clarify. Hot sauce, soy sauce, yorkshire pudding, veggie strips, sweet pickle, sausage, roast potatoes, roast chicken, okra chips and kimchi are  recipes that still require Pam's salt. I think that's all of them.

**Comment by MatrexsVigil** [comment]
Fixed in 1.12.2e - Also, all _alt recipes have now been renamed foodname_foodSalt, foodname_itemSalt, foodname_dustSalt, foodname_foodHoneydrop, foodname_dropHoney, etc for all recipes that use alternative items in them for easy finding, changing, and deleting (if needed).
