### ISSUE TITLE
Bait not respecting config values

### ISSUE THREAD

**Issue by LabGoblin** [MatrexsVigil/harvestcraft#103]
if you change the config values for bait crafting it still gives you 4. the same goes for fresh water its giving 1 even though i set the config to 8

**Comment by MatrexsVigil** [comment]
These config options are now pointless, as you can directly change the recipe amount in the specific recipe JSON file in the JAR.  I will be removing these config options next update.

**Comment by MatrexsVigil** [comment]
Fixed in 1.12.2e
