### ISSUE TITLE
[1.12.2d] Fruit trees still drop fruit blocks

### ISSUE THREAD

**Issue by Insane96** [MatrexsVigil/harvestcraft#104]
![2018-01-09_19 17 17](https://user-images.githubusercontent.com/7185104/34736057-f48cb9d8-f571-11e7-9b49-59d6817e5b00.png)

Same as #92

**Comment by Insane96** [comment]
Seems to be an Hunger Overhaul bug

**Comment by MatrexsVigil** [comment]
Thank you for closing these.

**Comment by Insane96** [comment]
Np, I know the feeling of having an issue page full of duplicates and invalid bugs.
