### ISSUE TITLE
Dupe bug with Market GUI

### ISSUE THREAD

**Issue by MJRLegends** [MatrexsVigil/harvestcraft#104]
Bug was found with 1.7.10 but i dont know if its just 1.7.10 with the issue.
How to reproduce it Note: shift click the item from the slot : ![](https://i.gyazo.com/dd91307269c69ea90803193f7369324c.gif)

**Comment by LezChap** [comment]
Confirmed it happens with just NEI and Harvestcraft installed, not an interaction with anything else.

**Comment by oaksvirals** [comment]
I can confirm this as well.

**Comment by blay09** [comment]
**ContainerMarket.java, Line 53**

```java
} else if (slotIndex >= 1 && slotIndex < 28) { // Inventory to Hotbar
if (!this.mergeItemStack(slotStack, 27, 37, false)) {
    return null;
}
```

Change the 27 there to 28 to fix.

**Fixed:**
```java
} else if (slotIndex >= 1 && slotIndex < 28) {  // Inventory to Hotbar 
if (!this.mergeItemStack(slotStack, 28, 37, false)) {
    return null;
}
```

**Comment by MJRLegends** [comment]
so does this mean it will be fixed? @blay09

**Comment by blay09** [comment]
I let Pam know and I assume she'll get it fixed for her next update. I'm not part of Harvestcraft myself.

**Comment by Darkosto** [comment]
Is this bug going to be fixed? I would love to be able to add this block back to Sky Factory and all my other modpacks.

**Comment by evernife** [comment]
Can someone provide a patch with this fix...
