### ISSUE TITLE
[1.12.2d] You can no longer plant crops directly

### ISSUE THREAD

**Issue by Insane96** [MatrexsVigil/harvestcraft#105]
You have to plant seeds

**Comment by MatrexsVigil** [comment]
Did this only happen with the update to 1.12.2d or have you changed mods?  Any other information?

**Comment by Insane96** [comment]
Yep. Same as the [tree fruit block drop bug](https://github.com/progwml6/HungerOverhaul/issues/163) is a Hunger Overhaul problem. https://github.com/progwml6/HungerOverhaul/issues/164
