### ISSUE TITLE
[1.12b] Crash Using Shipping Bin

### ISSUE THREAD

**Issue by MokahTGS** [MatrexsVigil/harvestcraft#11]
Got a crash trying to sell cotton in the shipping bin:

https://pastebin.com/WTCLJJMv

**Comment by mgwerner** [comment]
Same in 1.9.4 1.10h, trying to sell any item, causes crash when clicking Sell button.  Stack of items attempted to sell vanish, Shipping Bin is reset to tea/spinach when opened again, nothing in the box to place items, and no emeralds received.

**Comment by MatrexsVigil** [comment]
If you are still experiencing this crash after updating to HarvestCraft 1.12.2L and Forge 2555+, please re-post here: https://github.com/MatrexsVigil/harvestcraft/issues/127
