### ISSUE TITLE
[1.12.2] Broken apple item model

### ISSUE THREAD

**Issue by KorDum** [MatrexsVigil/harvestcraft#110]
Pam's HarvestCraft 1.12.2g

![image](https://user-images.githubusercontent.com/1331559/34873222-43b41cf6-f7a5-11e7-97c8-41ea830d510b.png)

![image](https://user-images.githubusercontent.com/1331559/34873251-5f00720c-f7a5-11e7-9977-56bfa6c01b51.png)

**Comment by MatrexsVigil** [comment]
Fixed in 1.12.2h!
