### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by LNJ2** [MatrexsVigil/harvestcraft#111]
I would like to use your textures in another project (Minetest TNG, a game for the minetest game engine). And I did not found any license here...
I would recommend you to use a Creative Commons license like this: https://creativecommons.org/licenses/by-sa/4.0/

This way everybody could use them, if you say that you are the original author and that it's under the CC BY-SA 4.0 license.

**Comment by MatrexsVigil** [comment]
I'm sorry but my textures and the Painterly Pack textures I use with permission are not allowed to be used in any other project.

**Comment by LNJ2** [comment]
Where can I get the Painterly Pack textures?

**Comment by Syndaryl** [comment]
Painterlypack.net, but I note that the permissions are "Users may use this pack with an official liscenced copy of Minecraft only, unless they have prior permission from myself."
Minetest is not Minecraft, therefore you need to contact the Painterlypack maintainer for explicit permission.

**Comment by LNJ2** [comment]
Ok, thanks.
