### ISSUE TITLE
Bubbly Water Unobtainable in Survival?

### ISSUE THREAD

**Issue by weegee209** [MatrexsVigil/harvestcraft#112]
The recipes for Bubbly Water and Salt seem to conflict with each other, or rather the Salt recipe overrides the Bubbly Water recipe. Both recipes are the same: Pot + Fresh Water.

**Comment by LimeTheOn** [comment]
wrong recipe in jei, use presser

**Comment by Jorhlok** [comment]
There's no presser in 1.8+

**Comment by LimeTheOn** [comment]
My bad. Also, there may be no presser in 1.8x but there is presser in 1.8+ since im playing in 1.9x and there is one...also i dont see any label.
