### ISSUE TITLE
[1.9.4] Recipes for saplings and market don't work

### ISSUE THREAD

**Issue by RealGrep** [MatrexsVigil/harvestcraft#115]
The market is uncraftable. As well, the saplings are not craftable, nor to recipes for them appear in JEI. I suspect something is reversed. As another PR says, the seeds are craftable into produce, rather than the opposite. Possibly the same error is in the saplings and market?

Adding the recipes in with CraftTweaker resolves the issue, but that's just a workaround.

**Comment by drewbit** [comment]
Think I could get the CraftTweaker script you used for that? Just to save me the trouble of doing it myself.

**Comment by RealGrep** [comment]
Sure, I put it here on my Dropbox: https://www.dropbox.com/s/b3fgumz2dydddxj/harvestcraft.zs?dl=0

If you find any errors, let me know.
