### ISSUE TITLE
Sauced lamb kebab 

### ISSUE THREAD

**Issue by Draskh** [MatrexsVigil/harvestcraft#116]
It has no recipe and lower food values than normal lamb kebab. That should be fixed. I use 1.12.2f

**Comment by JoshD8500** [comment]
Also garlic steak still has no recipe

**Comment by Draskh** [comment]
You should also change the German transaltion from "Saucen Lammdöner" to "Lammkebap mit Sauce". That would get better along with the name "Lammkebap"

**Comment by MatrexsVigil** [comment]
I can confirm that in 1.12.2k that lamb kebab is 5pts (2 1/2 shanks) and sauced kebab is 10 (5 shanks).  Also, garlic steak has a recipe.  Please update your HarvestCraft, I guess?

**Comment by Draskh** [comment]
Sauced Lamb kebaap has no recipe shown in JEI in harvestcraft 1.12.2m..
