### ISSUE TITLE
[1.9.4] empty list input for damper, gherkin recepies (JEI report)

### ISSUE THREAD

**Issue by Syndaryl** [MatrexsVigil/harvestcraft#117]
[12:14:16] [Client thread/ERROR] [JEI]: Recipe has an empty list as an input. net.minecraftforge.oredict.ShapelessOreRecipe@1652fc90
Output ItemStacks: [[1xharvestcraft:damperItem@0]]
Output Fluids: []
Input ItemStacks: [[1xharvestcraft:bakewareItem@0], [1xharvestcraft:flourItem@0], [OreDict: listAllmilk, 1xharvestcraft:soymilkItem@0, 1xminecraft:milk_bucket@0, 1xharvestcraft:freshmilkItem@0], [], [1xharvestcraft:butterItem@0]]
Input Fluids: []
[12:14:16] [Client thread/ERROR] [JEI]: Recipe has an empty list as an input. net.minecraftforge.oredict.ShapelessOreRecipe@64443be3
Output ItemStacks: [[1xharvestcraft:gherkinItem@0]]
Output Fluids: []
Input ItemStacks: [[1xharvestcraft:potItem@0], [1xharvestcraft:vinegarItem@0], [], [1xharvestcraft:spiceleafItem@0], [1xharvestcraft:cucumberItem@0]]
Input Fluids: []

**Comment by lebertran** [comment]
AFAIK, these recipes are registered four times with different salt ore dictionary keys in order to cover as many salt mods as possible, so this is not a bug.
