### ISSUE TITLE
Queen Bee Not Turning to Royal Jelly

### ISSUE THREAD

**Issue by MokahTGS** [MatrexsVigil/harvestcraft#118]
The spent Queen Bee does not turn to royal jelly on putting into the grafting grid despite what JEI says.  Looks like the actual recipe is broken.

**Comment by Syndaryl** [comment]
It works if the Queen Bee has any durabilty left. It doesn't work if it's out of durability.

**Comment by MokahTGS** [comment]
Actually have you tested this?  Pretty sure I've tried a queen with durability left and it still didn't work.  I know JEI says it should but I don't think it does.

Anyway, it should work with 0 durability like it did in 1.7.10 unless Pam was making a change.

**Comment by Syndaryl** [comment]
Yes, I have tested this. It works if the Queen Bee has any durability left, even 1. I've got four bottles of royal jelly in my chest from wild caught bees, and several generations of bees working fine in my hives.

**Comment by MokahTGS** [comment]
Hmmm....strange.  I'll test again tonight.  I wonder if I've got a recipe conflict that is causing issues.

**Comment by lebertran** [comment]
A queen bee with zero durability will not work, see [RecipeRegistry.java](https://github.com/lebertran/harvestcraft/blob/master/src/main/java/com/pam/harvestcraft/item/RecipeRegistry.java). Which durability did you have (use F3+H to see it)?

**Comment by Syndaryl** [comment]
That's the exact bug we're complaining about. Until the updates,  a queen bee with zero durability was the _only one_ that worked. The condition has been inverted.

**Comment by Syndaryl** [comment]
If this is an intentional design change, I request a more expensive way to convert a zero durability queen bee - perhaps crafting her with grub to produce the royal jelly? Or with a honey-filled waxcomb?

**Comment by lebertran** [comment]
This is not intentional, I did not know that it used to be that way. I will push a fix that behaviour asap.

**Comment by wesleybruce** [comment]
I can confirm its only the zero health spent bee not any of the others. I have 4 in a chest awaiting the fix. Good spawn rate of hives.

**Comment by Trcx528** [comment]
Changing the i = 1, to 1 = 0 on [this line](https://github.com/lebertran/harvestcraft/blob/master/src/main/java/com/pam/harvestcraft/item/RecipeRegistry.java#L89)  should fix this issue.  I'd make a pull request but I don't have a development environment available to build and test.
