### ISSUE TITLE
pumpkin pie

### ISSUE THREAD

**Issue by chris5022** [MatrexsVigil/harvestcraft#123]
not a big issue or came crashing. but i am mostly sure this is related to pams
[18:09:53] [Server thread/ERROR]: Parsing error loading built-in advancement minecraft:recipes/food/pumpkin_pie
com.google.gson.JsonSyntaxException: Unknown recipe 'minecraft:pumpkin_pie'

**Comment by MatrexsVigil** [comment]
This is going to happen for all vanilla Minecraft foods if you have enablevanillafoodBalance set to true because I replace the foods with my own versions.
