### ISSUE TITLE
[1.12.2] Is this an error from HarvestCraft?

### ISSUE THREAD

**Issue by PhoenixRiver** [MatrexsVigil/harvestcraft#124]
Hello :)

I'm trying to find the owner of this error and from /config the only mod I have that sets prices seems to be HarvestCraft (though it might be something else that just doesn't have a config option for it but I'll contact them after confirmation it isn't HarvestCraft). Looks like it's a pretty simple fix in that the price ranges have been inverted (oops!)

```
[15:21:30] [main/WARN]: PriceRange(10, 1) invalid, 1 smaller than 10
[15:21:30] [main/WARN]: PriceRange(9, 1) invalid, 1 smaller than 9
[15:21:30] [main/WARN]: PriceRange(3, 2) invalid, 2 smaller than 3
[15:21:31] [main/WARN]: PriceRange(-10, -18) invalid, -18 smaller than -10
[15:21:31] [main/WARN]: PriceRange(-10, -18) invalid, -18 smaller than -10
[15:21:31] [main/WARN]: PriceRange(-10, -18) invalid, -18 smaller than -10
```

Version: Pam's HarvestCraft 1.12.2f.jar
Forge Version: 1.12.2-forge1.12.2-14.23.1.2587

Mod list (though it's probably unnecessary here?)
AIImprovements-1.12-0.0.1b3.jar
animania-1.12.2-1.4.3.jar
AppleCore-mc1.12.2-3.1.0.jar
CarryOn MC1.12 v1.7.jar
Chameleon-1.12-4.1.3.jar
chameleoncreepers-1.4.1-1.12.jar
chickens-6.0.3.jar
CookingForBlockheads_1.12.1-6.3.17.jar
CraftStudio-1.0.0.93-mc1.12-alpha.jar
DynamicSurroundings-1.12.2-3.4.7.2.jar
DynamicTrees-1.12.2-0.7.2c.jar
Erosion-2.2.1.jar
GiacomosFishingNet-1.12.2-1.6.1.jar
hatchery-1.12.2-2.1.2.jar
Hwyla-1.8.23-B38_1.12.jar
iceandfire-1.3.1-1.12.2.jar
ImmersiveEngineering-0.12-76-core.jar
ImmersiveEngineering-0.12-76.jar
japaricraftmod-1.12-3.6.0.jar
jehc-1.12-1.3.1.jar
jei_1.12.2-4.8.5.132.jar
jeiintegration_1.12.2-1.5.1.36.jar
journeymap-1.12.2-5.5.2.jar
llibrary-1.7.9-1.12.jar
Mantle-1.12-1.3.1.21.jar
morechickens-1.12.2-3.0.0.jar
natura-1.12.2-4.3.2.42.jar
OptiFine_1.12.2_HD_U_C8.jar
Owls-1.12.2-1.0.1.jar
Pam's HarvestCraft 1.12.2f.jar
simplytea-1.4.jar
SpiceOfLife-mc1.12-1.3.11.jar
StorageDrawers-1.12.1-5.3.3.jar
Waddles-1.12.2-0.5.6.jar
WailaHarvestability-mc1.12-1.1.12.jar

Hope this helps :)

**Comment by MatrexsVigil** [comment]
I would need to see the entire error log, but I don't think that's HarvestCraft.  I don't have anything that is called PriceRange in my code.

**Comment by PhoenixRiver** [comment]
Once I've a chance I'll binary search the mods to find the culprit -
assuming it's not an interaction between two of them - but there's
nothing really more in the logs related to that at all - it's likely
something bigger though since the call is from Main rather than a
mod... does Minecraft have anything life that?! (Nothing that I know
of).

Thank you for your help though and thank you also for an amazing mod :D

**Comment by wamc2017** [comment]
This is definitely not a harvestcraft error, the first 3 records are issued by Ice and Fire and have something todo with villager trades I think.
Don't know about the other 3, but those could be issued by any mod which adds villager trades... 

Edit: The other three lines are issued by JapariCraft, found it by searching for EntityVillager.PriceInfo(-10, -18) through google :smile:

**Comment by PhoenixRiver** [comment]
They're villager trades? Ah, then it's likely Immersive Engineering or
Japaricraft - IE adds a whole new villager and structure I think and
both add items to villager chests. Will sort it out tomorrow and lodge
a bug report with them :)

It is an easy mistake to make I guess :)

I'll also file one with Ice and Fire :) - thank you again, especially
for going out of your way :)

**Comment by MatrexsVigil** [comment]
I think this is resolved.  Please re-open if you find it's actually HC some how.  =)
