### ISSUE TITLE
[1.9.4] Crops drop more seeds than the crop.

### ISSUE THREAD

**Issue by MoxieGrrl** [MatrexsVigil/harvestcraft#124]
On right click harvest and left click breaking crops always drop one of the appropriate produce and 0-2 seeds. This is particularly annoying if you have enough seeds and no longer need them. I also really dislike only getting one of the crop.

Suggestion: Make seeds drop on breaking the crop with a left click, but not on right click harvesting. Also, can we have more than one crop drop back? 1-3 would be lovely.

**Comment by JamesGrimm** [comment]
This should maybe be marked as a suggested enhancement. But I agree, I end up getting as much or more seeds than produce from right clicking my farms which is a bit excessive on the seed drops. More annoyance and storage issue than game stopper.

**Comment by MokahTGS** [comment]
Yeah...not really a bug but very annoying as I'm now deleting seeds to keep them from overflowing chests.  I really preferred the old way of just crafting a crop into a seed.

**Comment by LieseDenise** [comment]
Agreed, It would be nice to see that be part of the config file.

**Comment by MatrexsVigil** [comment]
Crops now drop all crops with no seeds as default in config.  Set cropsdropSeeds to true if you want it back the old way.
