### ISSUE TITLE
[1.12.2] Mussels and Sardines in water traps?

### ISSUE THREAD

**Issue by wamc2017** [MatrexsVigil/harvestcraft#126]
Hi,

thanks for the mod and the last modifications to automate stuff. :+1: 

I tried to figure out how to get all the fish ingame and if I understand the source code, there's no way how to get Mussels ingame...
Also the Sardines are only available by fishing. I think both should be added to the water trap...

In https://github.com/MatrexsVigil/harvestcraft/blob/master/src/main/java/com/pam/harvestcraft/tileentities/TileEntityWaterTrap.java#L236 case 29 and 30 are Items.Fish which is already case 0, I think those should be ItemRegistry.musselrawItem and ItemRegistry.sardinerawItem instead.

If this is not an issue, ignore me... :smile: 

Thanks for looking into it.

Best regards
 wamc

**Comment by MatrexsVigil** [comment]
Fixed in 1.12.2L
