### ISSUE TITLE
(Proposal) Balanced hunger restore and saturation values    VS    Actually Additions

### ISSUE THREAD

**Issue by MarikCZ** [MatrexsVigil/harvestcraft#128]
Hi

I think, that only Vanila food is balanced. Sorry, maybe I'm not right, but I have not installed any other mod that adds food.
For example, classic bread is made from 3 wheats, and adds 1.5 HungerPoints. (In balanced mode) Baguette from AA is made from 1 wheat, and adds even 3HP! Thats 6 times more effective! :D Temporarily I disabled recipes for AA using CraftTweaker, so it doesn't hurry for me. ;)
Maybe easier solution is replacing (for example) AA cheese with HC cheese... Thats how work for example CoFH core with ThermalX mods. It replaces all copper and tin from other small mods, with its own. Thanks for that, all is organized in one mode, in one place. There are no more 3 types of tin dust, and no more 50 types for bread, and baguettes. ;)
I don't know what is better for you, but I think that it will be not work for only 1 minute. So I repeat, this is not hurry and only proposal.

Have a nice day!

**Comment by MatrexsVigil** [comment]
At this time I am not going to try and mess with other mod's food.  If you're using HarvestCraft, then you'll just have to keep yourself limited to HC foods if you want that kind of balance.

**Comment by MarikCZ** [comment]
OK, I fully understand. I have better idea. I will contact AA developers, if they can add hunger points and saturation for various food to config files. Thanks

**Comment by MarikCZ** [comment]
Maybe option for disable food part of mods is better. I see now, that most of AA food is available in HC, so why have them twice? ;)
