### ISSUE TITLE
[1.9.4] Fully spent queens cannot be crafted for royal jelly

### ISSUE THREAD

**Issue by Trcx528** [MatrexsVigil/harvestcraft#129]
Playing FTB Unstable 4.0.9 (latest)

Letting the queen runs it's full cycle in an apiary will produce a queen with 0 durability (out of 18).  This queen can not be crafted for royal jelly, all other queens with a damage value (1-17) can be crafted into royal jelly according to jei.  

It would appear that a recipe is missing.

**Comment by wesleybruce** [comment]
Duplicate of report #118 
Well spotted though.
