### ISSUE TITLE
right click crops, infinite food

### ISSUE THREAD

**Issue by ScottNotFound** [MatrexsVigil/harvestcraft#129]
When there is a fresh crop planted on farmland, right clicking it will give you one of that crop even if the crop is not grown.

**Comment by MatrexsVigil** [comment]
Do you have any other mods installed?  I cannot replicate this issue.

**Comment by ScottNotFound** [comment]
I'm currently on mobile but this is the modlist, and I was going to try to isolate the issue to more specific circumstances. I've only noticed this happening to crops from pams harvestcraft so far but I suspect simple harvest may have something to do with it.

`"mods": {
        "actually-additions": "https://addons-origin.cursecdn.com/files/2520/975/ActuallyAdditions-1.12.2-r128.jar",
        "actually-baubles": "https://addons-origin.cursecdn.com/files/2459/131/ActuallyBaubles-1.12-1.1.jar",
        "actuallycomputers": "https://addons-origin.cursecdn.com/files/2465/255/actuallycomputers-2.1.0.jar",
        "advanced-generators": "https://addons-origin.cursecdn.com/files/2516/219/generators-0.9.20.12-mc1.12.2.jar",
        "ae2stuff": "https://addons-origin.cursecdn.com/files/2491/32/ae2stuff-0.7.0.4-mc1.12.2.jar",
        "akashic-tome": "https://addons-origin.cursecdn.com/files/2476/494/AkashicTome-1.2-10.jar",
        "applecore": "https://addons-origin.cursecdn.com/files/2508/285/AppleCore-mc1.12.2-3.1.0.jar",
        "appleskin": "https://addons-origin.cursecdn.com/files/2496/585/AppleSkin-mc1.12-1.0.9.jar",
        "applied-energistics-2": "https://addons-origin.cursecdn.com/files/2520/222/appliedenergistics2-rv5-stable-5.jar",
        "armorplus": "https://addons-origin.cursecdn.com/files/2514/849/armorplus-1.12.2-11.9.2.32-beta.jar",
        "astral-sorcery": "https://addons-origin.cursecdn.com/files/2509/51/astralsorcery-1.12.2-1.8.4.jar",
        "autoreglib": "https://addons-origin.cursecdn.com/files/2497/562/AutoRegLib-1.3-15.jar",
        "backpacks": "https://addons-origin.cursecdn.com/files/2519/520/backpacks%201.12.2%20-%203.4.3.jar",
        "bad-wither-no-cookie-reloaded": "https://addons-origin.cursecdn.com/files/2496/784/badwithernocookiereloaded-1.12-2.12.jar",
        "baubles": "https://addons-origin.cursecdn.com/files/2518/667/Baubles-1.12-1.5.2.jar",
        "bdlib": "https://addons-origin.cursecdn.com/files/2518/31/bdlib-1.14.3.12-mc1.12.2.jar",
        "betterfps": "https://addons-origin.cursecdn.com/files/2483/393/BetterFps-1.4.8.jar",
        "bibliocraft": "https://addons-origin.cursecdn.com/files/2456/43/BiblioCraft[v2.4.3][MC1.12.0].jar",
        "binnies-mods": "https://addons-origin.cursecdn.com/files/2520/129/binnie-mods-1.12.2-2.5.0.112.jar",
        "biomes-o-plenty": "https://addons-origin.cursecdn.com/files/2495/245/BiomesOPlenty-1.12.2-7.0.1.2302-universal.jar",
        "bookshelf": "https://addons-origin.cursecdn.com/files/2522/71/Bookshelf-1.12.2-2.3.522.jar",
        "botania": "https://addons-origin.cursecdn.com/files/2507/921/Botania%20r1.10-352.jar",
        "chameleon": "https://addons-origin.cursecdn.com/files/2450/900/Chameleon-1.12-4.1.3.jar",
        "chisels-bits": "https://addons-origin.cursecdn.com/files/2506/644/chiselsandbits-14.11.jar",
        "codechickenlib-1-8": "https://addons-origin.cursecdn.com/files/2509/819/CodeChickenLib-1.12.2-3.1.5.331-universal.jar",
        "cofh-core": "https://addons-origin.cursecdn.com/files/2519/297/CoFHCore-1.12.2-4.3.10.5-universal.jar",
        "cofh-world": "https://addons-origin.cursecdn.com/files/2513/671/CoFHWorld-1.12.2-1.1.1.12-universal.jar",
        "common-capabilities": "https://addons-origin.cursecdn.com/files/2467/504/CommonCapabilities-1.12-1.4.0.jar",
        "cucumber": "https://addons-origin.cursecdn.com/files/2520/478/cucumber-1.12-1.0.4.jar",
        "cyclops-core": "https://addons-origin.cursecdn.com/files/2519/785/CyclopsCore-1.12.2-0.11.1.jar",
        "dark-utilites": "https://addons-origin.cursecdn.com/files/2522/89/DarkUtils-1.12.2-1.8.192.jar",
        "deep-resonance": "https://addons-origin.cursecdn.com/files/2514/28/deepresonance-1.12-1.6.0.jar",
        "eleccore": "https://addons-origin.cursecdn.com/files/2510/914/ElecCore-1.12.2-1.8.434.jar",
        "embers": "https://addons-origin.cursecdn.com/files/2495/586/embers-0.230.jar",
        "ender-storage-1-8": "https://addons-origin.cursecdn.com/files/2509/842/EnderStorage-1.12.2-2.4.2.126-universal.jar",
        "environmental-tech": "https://addons-origin.cursecdn.com/files/2512/886/environmentaltech-1.12.2-2.0.6b.jar",
        "et-lunar-environmental-tech-addon": "https://addons-origin.cursecdn.com/files/2509/903/etlunar-1.12.2-2.0.6a.jar",
        "extra-bit-manipulation": "https://addons-origin.cursecdn.com/files/2475/985/ExtraBitManipulation-1.12-3.2.1.jar",
        "extra-utilities": "https://addons-origin.cursecdn.com/files/2512/406/extrautils2-1.12-1.7.2.jar",
        "extracells2": "https://addons-origin.cursecdn.com/files/2521/550/ExtraCells-1.12.2-2.5.11a48.jar",
        "extreme-reactors": "https://addons-origin.cursecdn.com/files/2516/62/ExtremeReactors-1.12.2-0.4.5.45.jar",
        "flux-networks": "https://addons-origin.cursecdn.com/files/2512/474/fluxnetworks-1.12.2-3.0.2.jar",
        "forestry": "https://addons-origin.cursecdn.com/files/2520/694/forestry_1.12.2-5.7.0.236.jar",
        "immersive-cables": "https://addons-origin.cursecdn.com/files/2513/800/ImmersiveCables-1.12.2-1.2.0.1.jar",
        "immersive-engineering": "https://addons-origin.cursecdn.com/files/2515/333/ImmersiveEngineering-0.12-76.jar",
        "immersive-petroleum": "https://addons-origin.cursecdn.com/files/2514/850/immersivepetroleum-1.12.2-1.1.6.jar",
        "immersive-railroading": "https://addons-origin.cursecdn.com/files/2520/142/ImmersiveRailroading-0.4.4_1.12.jar",
        "industrial-craft": "https://addons-origin.cursecdn.com/files/2462/277/industrialcraft-2-2.8.16-ex112.jar",
        "industrial-foregoing": "https://addons-origin.cursecdn.com/files/2520/927/industrialforegoing-1.12.2-1.7.0-114.jar",
        "integrated-dynamics": "https://addons-origin.cursecdn.com/files/2522/285/IntegratedDynamics-1.12.2-0.10.2.jar",
        "integrated-tunnels": "https://addons-origin.cursecdn.com/files/2519/798/IntegratedTunnels-1.12.2-1.4.1.jar",
        "inventory-tweaks": "https://addons-origin.cursecdn.com/files/2482/481/InventoryTweaks-1.63.jar",
        "jei": "https://addons-origin.cursecdn.com/files/2511/52/jei_1.12.2-4.8.5.138.jar",
        "jei-integration": "https://addons-origin.cursecdn.com/files/2491/927/jeiintegration_1.12.2-1.5.1.36.jar",
        "journeymap": "https://addons-origin.cursecdn.com/files/2498/312/journeymap-1.12.2-5.5.2.jar",
        "just-enough-harvestcraft": "https://addons-origin.cursecdn.com/files/2482/75/jehc-1.12-1.3.1.jar",
        "just-enough-resources-jer": "https://addons-origin.cursecdn.com/files/2497/186/JustEnoughResources-1.12.2-0.8.5.27.jar",
        "mantle": "https://addons-origin.cursecdn.com/files/2474/52/Mantle-1.12-1.3.1.21.jar",
        "mcjtylib": "https://addons-origin.cursecdn.com/files/2516/349/mcjtylib-1.12-2.6.2.jar",
        "mobtotems": "https://addons-origin.cursecdn.com/files/2479/353/mobtotems-1.12.1-0.3.0.jar",
        "morph-o-tool": "https://addons-origin.cursecdn.com/files/2475/117/Morph-o-Tool-1.2-16.jar",
        "morpheus": "https://addons-origin.cursecdn.com/files/2432/272/Morpheus-1.12-3.3.2.jar",
        "mouse-tweaks": "https://addons-origin.cursecdn.com/files/2462/627/MouseTweaks-2.8-mc1.12.1.jar",
        "mystical-aggradditions": "https://addons-origin.cursecdn.com/files/2503/986/mysticalagradditions-1.12-1.2.7.jar",
        "mystical-agriculture": "https://addons-origin.cursecdn.com/files/2511/36/mysticalagriculture-1.12-1.6.7.jar",
        "natura": "https://addons-origin.cursecdn.com/files/2519/128/natura-1.12.2-4.3.2.42.jar",
        "natures-compass": "https://addons-origin.cursecdn.com/files/2513/221/NaturesCompass-1.12.2-1.5.1.jar",
        "netherportalfix": "https://addons-origin.cursecdn.com/files/2489/643/NetherPortalFix_1.12.1-5.3.13.jar",
        "oc-sensors": "https://addons-origin.cursecdn.com/files/2466/745/ocsensors-1.0.2-b12.jar",
        "oc-xnet-driver": "https://addons-origin.cursecdn.com/files/2520/329/ocxnetdriver-1.0.0-b5.jar",
        "openblocks": "https://addons-origin.cursecdn.com/files/2514/379/OpenBlocks-1.12.2-1.7.4.jar",
        "opencomputers": "https://addons-origin.cursecdn.com/files/2508/602/OpenComputers-MC1.12.1-1.7.1.43.jar",
        "openmodslib": "https://addons-origin.cursecdn.com/files/2514/375/OpenModsLib-1.12.2-0.11.4.jar",
        "optifine": "https://s3.amazonaws.com/modmc/mods/optifine/OptiFine_1.12.2_HD_U_C8.jar",
        "p455w0rds-library": "https://addons-origin.cursecdn.com/files/2516/440/p455w0rdslib-1.12-2.0.25.jar",
        "pams-cookables": "https://addons-origin.cursecdn.com/files/2504/109/pamscookables-1.1.jar",
        "pams-harvestcraft": "https://addons-origin.cursecdn.com/files/2521/633/Pam's%20HarvestCraft%201.12.2L.jar",
        "powered-thingies": "https://addons-origin.cursecdn.com/files/2509/628/powered-thingies-1.12.2-1.0.12.jar",
        "psi": "https://addons-origin.cursecdn.com/files/2499/167/Psi-r1.1-59.jar",
        "quark": "https://addons-origin.cursecdn.com/files/2517/238/Quark-r1.4-121.jar",
        "quick-leaf-delay": "https://addons-origin.cursecdn.com/files/2469/364/QuickLeafDecay-MC1.12.1-1.2.4.jar",
        "random-things": "https://addons-origin.cursecdn.com/files/2521/25/RandomThings-MC1.12.2-4.1.2.jar",
        "reauth": "https://addons-origin.cursecdn.com/files/2491/161/ReAuth-3.5.2.jar",
        "redstone-flux": "https://addons-origin.cursecdn.com/files/2448/933/RedstoneFlux-1.12-2.0.1.2-universal.jar",
        "reliquary-v1-3": "https://addons-origin.cursecdn.com/files/2509/540/Reliquary-1.12.2-1.3.4.728.jar",
        "rftools": "https://addons-origin.cursecdn.com/files/2516/350/rftools-1.12-7.23.jar",
        "rftools-control": "https://addons-origin.cursecdn.com/files/2514/31/rftoolsctrl-1.12-1.8.0.jar",
        "rftools-dimensions": "https://addons-origin.cursecdn.com/files/2516/650/rftoolsdim-1.12-5.50.jar",
        "roots": "https://addons-origin.cursecdn.com/files/2510/836/roots-2-0.104.jar",
        "shadowfacts-forgelin": "https://addons-origin.cursecdn.com/files/2505/90/Forgelin-1.6.0.jar",
        "simple-harvest": "https://addons-origin.cursecdn.com/files/2432/128/simpleharvest-1.07.jar",
        "sonar-core": "https://addons-origin.cursecdn.com/files/2512/472/sonarcore-1.12.2-5.0.4.jar",
        "storage-drawers": "https://addons-origin.cursecdn.com/files/2484/308/StorageDrawers-1.12.1-5.3.3.jar",
        "storage-drawers-extras": "https://addons-origin.cursecdn.com/files/2443/623/StorageDrawersExtras-1.12-3.1.0.jar",
        "techguns": "https://addons-origin.cursecdn.com/files/2518/488/techguns-1.12.2-2.0.1.1.jar",
        "tesla-core-lib": "https://addons-origin.cursecdn.com/files/2509/629/tesla-core-lib-1.12-1.0.12.jar",
        "the-lost-cities": "https://addons-origin.cursecdn.com/files/2497/882/lostcities-1.12-1.0.2.jar",
        "the-one-probe": "https://addons-origin.cursecdn.com/files/2496/985/theoneprobe-1.12-1.4.19.jar",
        "thedragonlib": "https://addons-origin.cursecdn.com/files/2489/142/thedragonlib-1.12.2-5.2.0.jar",
        "thermal-cultivation": "https://addons-origin.cursecdn.com/files/2518/223/ThermalCultivation-1.12.2-0.1.5.3-universal.jar",
        "thermal-dynamics": "https://addons-origin.cursecdn.com/files/2518/224/ThermalDynamics-1.12.2-2.3.10.4-universal.jar",
        "thermal-foundation": "https://addons-origin.cursecdn.com/files/2518/222/ThermalFoundation-1.12.2-2.3.10.6-universal.jar",
        "thermalexpansion": "https://addons-origin.cursecdn.com/files/2520/117/ThermalExpansion-1.12.2-5.3.10.15-universal.jar",
        "tinkers-construct": "https://addons-origin.cursecdn.com/files/2518/400/TConstruct-1.12.2-2.9.0.55.jar",
        "track-api": "https://addons-origin.cursecdn.com/files/2520/75/TrackAPI-1.0_1.12.jar",
        "unidict": "https://addons-origin.cursecdn.com/files/2520/277/UniDict-1.12.2-2.3.1.jar",
        "valkyrielib": "https://addons-origin.cursecdn.com/files/2512/885/valkyrielib-1.12.2-2.0.6b.jar",
        "wanionlib": "https://addons-origin.cursecdn.com/files/2510/15/WanionLib-1.12.2-1.4.jar",
        "waystones": "https://addons-origin.cursecdn.com/files/2513/625/Waystones_1.12.2-4.0.20.jar",
        "wireless-crafting-terminal": "https://addons-origin.cursecdn.com/files/2502/510/WirelessCraftingTerminal-1.12.2-3.8.55.jar",
        "woot": "https://addons-origin.cursecdn.com/files/2519/756/woot-1.12.2-0.0.7.jar",
        "xnet": "https://addons-origin.cursecdn.com/files/2517/60/xnet-1.12-1.6.7.jar",
        "zerocore": "https://addons-origin.cursecdn.com/files/2482/156/zerocore-1.12-0.1.1.0.jar"
      }`

**Comment by ScottNotFound** [comment]
Okay yeah this doesn't happen with just harvestcraft, but it does with harvestcraft and simple harvest. I'm fairly certain the simple harvest mod is causing the issue if [this](https://github.com/dazsim/Simple-Harvest/blob/master/src/main/java/com/workshopcraft/SimpleHarvest/CropHandler.java) is anything to go off of. Sorry for the trouble.
