### ISSUE TITLE
Paperbark Trees

### ISSUE THREAD

**Issue by StarquestBaron** [MatrexsVigil/harvestcraft#131]
When I craft a paperbark sapling and plant it, I get a tree with paperbark wood on the exposed trunk, but jungle wood beneath the leaves.  When I use an axe on the paperbark, the wood does not drop, although the jungle wood does.  

![image](https://user-images.githubusercontent.com/10749070/35201618-ef35bfca-feea-11e7-8727-b328453bffa6.png)

**Comment by MatrexsVigil** [comment]
In order to move fruit blocks (this includes paperbark, maple syrup, and cinnamon logs) you need to use shears.  

I'll look into making the paperbark trunks more uniform.
