### ISSUE TITLE
(1.9.4c)Mustard/Sesame Seeds confusion

### ISSUE THREAD

**Issue by jimis2001** [MatrexsVigil/harvestcraft#132]
In the latest version of the mod there is something wrong with those two items. The seeds apart from being listAllseed just like they are supposed to, also appear as the equivalent crop in the ore dictionary and the item that is supposed to act as the crop doesn't belong to any ore dictionary class. This means that the seed which is used just for planting the crop block is now used in recipes where the crop item should have been instead. It is definetly a mistake in the code and the crop item should be given the crop ore dictionary class, and for the case of mustard the listAllspice class as well. Sorry if this bug report wasn't clear enough.

**Comment by MatrexsVigil** [comment]
Fixed!
