### ISSUE TITLE
listAllsmoothie oreDict missing some entries.

### ISSUE THREAD

**Issue by Mystogrigen** [MatrexsVigil/harvestcraft#134]
Edit: hit enter by accident.

Went to make some delighted meals with apple smoothies, turns out it doesn't work.  Don't know if it was by design or accident that there are smoothies not added to that oreDict entry.  Here are the smoothies missing from listAllsmoothie:

- Apricot Smoothie
- Fig Smoothie
- Grapefruit Smoothie
- Persimmon Smoothie
- Gooseberry Smoothie
- Apple Smoothie
- Coconut Smoothie
- Cranberry Smoothie
- Grape Smoothie
- Pear Smoothie
- Plum Smoothie

**Comment by MatrexsVigil** [comment]
Thanks!  I'll fix this

**Comment by MatrexsVigil** [comment]
Fixed in 1.12.2p
