### ISSUE TITLE
[1.10] Easy Harvest Starnge behavior

### ISSUE THREAD

**Issue by MachinegunMarty** [MatrexsVigil/harvestcraft#134]
I know you don't have a 1.10 version, but i'm testing which mods work and don't and this just seems to work under 1.10 so i'm using it.

Found some strange behavior tho.

I'm also using the mod: Agricultural Expansion and found this weird bug.

Normal: If you harvest a mature plant you get an essence and a sprout. 
When i harvest i don't get a sprout.

I reported this to the mod maker and he couldn't reproduce the problem.

So today i did some test to find out what was causing this (because with just agricultural expansion installed it worked).
I added mods until it stopped working.
I found out it works with all the mods i have, except Pam's HarvestCraft.

If i set easyharvest to false in harvestcrafts config file, then it works.
I did some more test and easy harvest just seems to break the normal behavior.

Through testing with Agricultural Expansion's mod maker i tracked it down to this.

Here a link to the github:

https://github.com/xLionel775/AgriculturalExpansion/issues/10

Big thanx to xLionel775 for his time, testing and patience with me ;-)

Hope it helps you somehow.

grtz,

Machinegun_Marty

**Comment by MatrexsVigil** [comment]
I'm not certain how to fix this, sorry.
