### ISSUE TITLE
1.8.9e missing crop textures

### ISSUE THREAD

**Issue by kotoroshinoto** [MatrexsVigil/harvestcraft#135]
plants render normally, but the crop items are purple and black cubes.

**Comment by kotoroshinoto** [comment]
I THINK the JSON files ended up with lowercase names again as in a previous issue

**Comment by Pthalocy** [comment]
Same issue 1.8.9e, huge chunk of food items are purple cubes.
It's not even a missing flat item texture, it's presenting them like they're _blocks_ with missing textures, which doesn't make much sense either.

**Comment by Calendis** [comment]
I am experiencing this as well

**Comment by drago15243** [comment]
Same. :/

**Comment by Calendis** [comment]
The .json files do indeed have lowercase "item", just checked. That is probably the problem

**Comment by drago15243** [comment]
so... what do we do?

**Comment by UnstableCodeScarlet** [comment]
Probably use D until an F is released, or fix it your self, which is unlikely anytime soon considering pam is busy.
What were the differences between D and E anyways?

**Comment by kotoroshinoto** [comment]
I ended up writing a short command to autorename the files, dont' recall if I still have it.

**Comment by katubug** [comment]
Thank you so much for the .bat script, icestorm! Worked for me.

While I understand that 1.8.9 is no longer supported, I suggest that, since icestorm has so helpfully provided a fix, why not use it and upload a new version with those changes? It seems to me that it would ultimately be to everyone's benefit - users wouldn't have to try to find this fix and implement it, and that would mean less people bothering Pam and wasting her time.

**Comment by Trisscar05** [comment]
Just tried using the batch script, and got this result, which blocked Pam's from loading, though the game continued on regardless (I should note this is with FML alone, as opposed to using FTB, ATL, or the like):
[00:52:25] [Client thread/DEBUG] [FML/]: Examining file Pam's HarvestCraft 1.8.9e.jar for potential mods
[00:52:25] [Client thread/DEBUG] [FML/]: The mod container Pam's HarvestCraft 1.8.9e.jar appears to be missing an mcmod.info file

**Comment by Wolforine2002** [comment]
I don't understand how to do any of this? can someone explain in more detail or something. The Item words already have capital I's in the config and I don't understand this

**Comment by kotoroshinoto** [comment]
most of us that fixed it manually coded something quick and dirty and repackaged the files in the jar.

I'll see if I can whip it up again when I get back from work, I didn't keep a copy of it, but it should only be a dozen lines of code or so.

**Comment by Wolforine2002** [comment]
oh ok

**Comment by Wolforine2002** [comment]
Oh well I see whats wrong now and fixed it by renaming the item with a captial I. But I don't understand any of this codinf stuff ;^; sorry. Im wondering will I just have to rename them all or is there like a weird thing i don't understand that will fix it? Sorry I feel dumb

**Comment by Syndaryl** [comment]
They'll all have to be fixed. You should hopefully just be able to turn on a case-sensitive search for the word item and replace with Item (big I) and then just use Replace All.

**Comment by Wolforine2002** [comment]
How do I do that in Win-Rar? (I'm such a noob)
