### ISSUE TITLE
[1.12.2] HO Age Crash Not Fixed

### ISSUE THREAD

**Issue by yepidoodles** [MatrexsVigil/harvestcraft#136]
Hello,

The Hunger Overhaul age crash (https://github.com/MatrexsVigil/harvestcraft/pull/132), has not been fixed in latest version (1.12.2m) `Fixed: Crops: AGE is now CROPS_AGE to fix issues with Hunger Overhaul (PR by alexbegt)`.

Client crash on SpongeForge server:
https://pastebin.com/KizaC6Ju
Client crash on Single Player:
https://pastebin.com/ev8zxraj

Happy to provide extra details on request.

Alice

**Comment by xiaoschannel** [comment]
Same problem here.

**Comment by trilexcom** [comment]
same problem here too https://pastebin.com/0K5xSP33

i tried few troubleshooting steps i reg the config for harvestcraft and tried again it didn't do anything , still the same issue, this is when you right click on the crop to harvest, if you left click on the crop it wont give you anything either

**Comment by alexbegt** [comment]
I have to release a new version of HungerOverhaul before the bug is fixed.
