### ISSUE TITLE
[1.12.2] Apples dropping as textures. 

### ISSUE THREAD

**Issue by Keaton1188** [MatrexsVigil/harvestcraft#137]
Hey, The apples you normally get from a Pam's Harvestcraft appletree have a broken texture and the wrong ID. It should be ID-9300, but it is ID-7877. They grow fine on the tree then when you right-click the ripe ones they drop as the wrong item name + texture etc.  Dropping as item.appleitem.name. Therefore they are unusable.

PamsHarvestcraft version: Pam's HarvestCraft 1.12.2g.jar

SpongeVersion: 1.12.2-2555-7.1.0-BETA-2840

FTB Pack: Revelations

**Comment by MatrexsVigil** [comment]
This is an issue with an earlier version of Hunger Overhaul interacting with HarvestCraft.  Updating both should fix this.
