### ISSUE TITLE
cranberries cannot be crafted into cranberry seeds

### ISSUE THREAD

**Issue by LlubNek** [MatrexsVigil/harvestcraft#137]
Cranberries cannot be crafted into cranberry seeds.  The only means to get cranberry seeds is from planted cranberries.  This means that cranberries are unfarmable without cheating in seeds or farming gardens.

I'm using Pam's HarvestCraft 1.9.4c.jar on forge 2005 for minecraft 1.10.2.

**Comment by MatrexsVigil** [comment]
Fixed!
