### ISSUE TITLE
Unable to craft fruit trees

### ISSUE THREAD

**Issue by Crepox** [MatrexsVigil/harvestcraft#138]
The various food trees spawn into the world, but the player is unable to regrow the various foods by combining them with the corresponding tree types and replanting them. This is in version 1.9.4c

**Comment by LieseDenise** [comment]
If you put three fruits around a sapling you a get a fruit sapling. I have been having trouble only getting one fruit on each tree and Not being able to get them to grow in my under ground farm, no mater how large a space I create, even if I go to the surface.

**Comment by LieseDenise** [comment]
Well I figured it out. They only grow at or above water level.
