### ISSUE TITLE
[1.12.2] [Server] Can't load removed vanilla food recipes

### ISSUE THREAD

**Issue by kaonashi97** [MatrexsVigil/harvestcraft#138]
I have a problem with the removed vanilla food recipes.

I'm using Minecraft Forge 1.12.2 14.23.1.2604 and Pam's Harvestcraft 1.12.2m. I can't use the recommended version of Forge (2555) because other mods need a newer version. Never the less I get this error when running Harvestcraft on a Forge Server.

`Parsing error loading built-in advancement minecraft:recipes/food/pumpkin_pie
com.google.gson.JsonSyntaxException: Unknown recipe 'minecraft:pumpkin_pie'`

This is logged on start up. The server is starting and a user can connect to it. When opening the recipes book the client game will crash.

Therefore I have this log files from the server showing the errors:
[fml-junk-earlystartup.log](https://github.com/MatrexsVigil/harvestcraft/files/1670116/fml-junk-earlystartup.log)
[latest.log](https://github.com/MatrexsVigil/harvestcraft/files/1670117/latest.log)
And the crash report from the client:
[crash-2018-01-27_14.32.56-client.txt](https://github.com/MatrexsVigil/harvestcraft/files/1670110/crash-2018-01-27_14.32.56-client.txt)

As far a I think the errors are upcoming with the removal of the vanilla foods. Hopefully there is a way fixing this error. I'm loving this mod and want to use it in 1.12.2.

**Comment by MatrexsVigil** [comment]
The error is just cosmetic and removes the recipe achievements when don't do anything in game.  I don't consider this a bug because it doesn't affect anything tangible.
