### ISSUE TITLE
[1.9.4] [Suggestion] Blood Magic Harvest Handler Compatibility

### ISSUE THREAD

**Issue by WayofTime** [MatrexsVigil/harvestcraft#139]
Greetings!

I would like to put forward a suggestion. Blood Magic has a few ways that automatically harvests crops, but because it assumes nothing about the crops a harvest handler needs to be registered. What it allows is for a crop to be harvested, dropping all of its contents while at the same time replanting itself. There isn't much effort needed on your part if you decide to do so. All you would need to do is implement an IHarvestHandler and register it using the HarvestRegistry.

https://github.com/WayofTime/BloodMagic/blob/1.9/src/main/java/WayofTime/bloodmagic/api/iface/IHarvestHandler.java

https://github.com/WayofTime/BloodMagic/blob/1.9/src/main/java/WayofTime/bloodmagic/api/registry/HarvestRegistry.java

If you have any questions about this compatability suggestion, let me know either here or in the #bloodmagic IRC channel.

**Comment by TehNut** [comment]
For the majority of your crops, you could do something similar to [this](https://gist.github.com/TehNut/6bdb9b9017d062e63c8c309ba300c803) if you don't want the dependency.

**Comment by MatrexsVigil** [comment]
I will be working on compatibility with various mods soon!  Thanks.
