### ISSUE TITLE
[Request] Source code for the 1.7.10 and 1.11 versions

### ISSUE THREAD

**Issue by akvgergo** [MatrexsVigil/harvestcraft#14]
Hi, inspired by [this](https://redd.it/6m23ga) reddit post I wanted to create some statistics for Harvestcraft. While that post is probably sufficient for 90% of the players, I wanted to go a little more in-depth as to what are the best plant combinations, what has little to no use, what to plant if you only have limited space etc. however, looking trough JEI to get all this information would be incredibly tedious.

To make it easier on myself, I started writing a small c# application that basically gets the recipes from the source code and works from that, I ran into two issues tough:

* First when you randomly took down the source for 1.11 (I got a mini heartattack when it was just gone, please don't do that again)
* Now that I have the 1.12 source I can work with that, I have no access to the 1.7 source though, and it would be nice to create separate data for the 1.7 playerbase where I can account that ~~tofu is stupidly OP~~ some recipes are different

I tried to decompile the old jar files, but that proved to be useless since most of your little helper methods got inlined, making my job even harder, and on top of that the usual minecraft obfuscation made quite a few parts unreadable and very hard to interpret.

If you still have the old source then I would be very grateful if you could upload that somewhere where I can get access to it.

**Comment by richardhendricks** [comment]
I am also interested in this information!  I'd love to see a breakdown of how many foods are in each category, such as how many delighted meals, wholesome meals, light meals, etc.

**Comment by MatrexsVigil** [comment]
Once I can find my old source code, I will be uploading it for viewing (but not bug fixing/updating).  Closing this for now.
