### ISSUE TITLE
Planting rice or seaweed results in the seeds popping out of the ground.

### ISSUE THREAD

**Issue by Mystara0001** [MatrexsVigil/harvestcraft#14]
Create a farm plot.
Plant rice or seaweed seed.
Cause any update near bock or wait for plant to start to grow.

Expected: Rice or seaweed grows as normal until mature and then can be harvested.
Actual: Rice seeds pop out of ground.

Unless the mechanic on these plants changed, this is their current behavior. I have tried the plant on water method, it also does not work.

Edited to add: seems this applies to cranberries as well.

**Comment by Haggle1996** [comment]
Having this problem as well

**Comment by MoonCutter2B** [comment]
maybe they should be planted in water?

**Comment by Haggle1996** [comment]
They won't plant in water anymore like they used to.

**Comment by reteo** [comment]
Having this issue as well; it seems to be a mod interaction issue with Hunger Overhaul.  I've also submitted to that mod's github as well.

**Comment by Dulciphi** [comment]
From the 1.7.10j changelog: 
"- Config Option: You can now disable special farmland needs of water crops - enablecropspecialplanting - Default: true (If true, seed planting doesn't work on farmland. If false, crop planting doesn't work on water. No matter how it's set, previously planted crops on water *only* will stay)"

Setting     B:enablecropspecialplanting=false  in the "crops" section of Harvestcraft.cfg results in rice, grape and seaweed seeds being plantable on normal farmland. They will no longer pop out of the ground - even with HungerOverhaul installed. This may not be ideal but it's the only workaround that seems to exist currently - and it does work
