### ISSUE TITLE
[1.12.2]Adverse effects when using Pam's HarvestCraft 1.12.2 L and LiteLoader 1.12.2 together?

### ISSUE THREAD

**Issue by karikusa** [MatrexsVigil/harvestcraft#140]
Well, I was in trouble ...
I am playing with MOD including Pam's HarvestCraft 1.12.2 L,
Even if you own wheat, cows and sheep will not react. I can not breed, so I tried to verify with a configuration that reduced the number of MOD.

Configuration MOD
   Forge 14.23.1.2587
   Optifine_1.12.2_HD_U_C8
   LiteLoader 1.12.2
   mod_voxelMap - 1.7.0 _ for - 1.12.2
   Hwyla - 1.8.23 - B38 - 1.12
   IntelliInput-2.6-for1.12.2
   NoMoreRecipeConflict - 0.9 (1.12)
   SpawnChecker - 2.7.7.137
   WailaHarvestability-mc1.12-1.1.12
   Pam's HarvestCraft 1.12.2 L

I verified with this configuration, but there was no response as well, and the chickens could breed without problems. The reaction of pigs to carrots was strange to normal.
It seems that items taken in by Pam's HarvestCraft are probably affected.
Also, wheat, beetroot is collected by right click to collect only seeds.
There is no problem for destroying and collecting like vanilla ...
Furthermore, I took out LiteLoader 1.12.2 and VoxelMap and experimented it, but if this was normal, it responded to wheat even under the environment of PAM 's MOD and could do the harvest properly!
I will report it to PAM for the time being, but in what case should I report it ... XD

Potatoes from Japan ...

**Comment by MatrexsVigil** [comment]
I replace all vanilla foods in my mod.  If you are having issues, you can disable the replaced foods in the config or just not use LiteLoader.

**Comment by darthvader45** [comment]
Where is this in harvestcraft.cfg?  I cannot find anything like that, except the saturation change option.

**Comment by Geethebluesky** [comment]
`# Makes changes to vanilla food item and drop hunger restore and saturation values to be balanced with HarvestCraft food. [default: true]`

`B:enablevanillafoodBalance=false`

**Comment by darthvader45** [comment]
Got it.  Now it works.  Wish wheat could be right-click harvested even with
the balancing, as right-click vs punch harvest are both as simple, one is
just more efficient as it takes less time.

Golden rule in Minecraft: Never dig straight down.

**Comment by Geethebluesky** [comment]
Yeah, I'm also wondering when someone will come up with a mod to change all vanilla crops to right-click harvest...

**Comment by darthvader45** [comment]
Agreed.  Also, love the addition of the paradise burger.  Gonna have so
much fun eating that.  And with the gourmet burger patties, fries and such,
I'm gonna make a McDonalds in Minecraft.

Golden rule in Minecraft: Never dig straight down.
