### ISSUE TITLE
Removed tools and Blocks

### ISSUE THREAD

**Issue by LieseDenise** [MatrexsVigil/harvestcraft#140]
( When) will the removed tools be returned? It is hard to make a lot of the stuff with out them. 

- Removed: _Market_, Churn, Quern, Presser, _Apiary_, _Beehives_, Candles, Hardened Leather, Wax, Oven, Cake Blocks, Fish Trap, Animal Trap, Tool Blocks, Salt Ore/Blocks

_ italics denote that they are currently present in 1.9.4 to my knowledge_

I know there is a lot to do. Thank you for the awesome mod. It is one of my favorites.

**Comment by MatrexsVigil** [comment]
Everything but the oven, cake blocks, tool blocks, and salt ore/blocks have returned.  Cake blocks will return soon, everything else has been phased out.
