### ISSUE TITLE
Bring back placeable cutting board, pot, etc.

### ISSUE THREAD

**Issue by Pulverizer** [MatrexsVigil/harvestcraft#141]
Title says all. This was such nice and useful feature.

**Comment by MatrexsVigil** [comment]
The cooking counter and oven blocks from Cooking with Blockheads does what I was trying to achieve so much better though.

**Comment by CosmicHikari** [comment]
Maybe add them back as a legacy item? They're so useful regardless

**Comment by Pulverizer** [comment]
@MatrexsVigil Thing is, some people don't use Cooking for Blockheads. (Though now that I've seen it I might start using it.)

Either way, they were a really nice feature to have.

**Comment by MatrexsVigil** [comment]
This might be a something I will add back later.  Closing this.
