### ISSUE TITLE
[1.12.2] Fruit tree trunk blocks (maple/paper) don't give items

### ISSUE THREAD

**Issue by phellmes** [MatrexsVigil/harvestcraft#142]
When I right-click ripe trunk blocks on Maple and Paperbark trees I don't get any items out of them. They change texture back as usual, so there is a reaction. But no fruit items appear. They either vanish to nowhere or don't spawn at all.

Main mods:
forge-1.12.2-14.23.1.2555
Pam's+HarvestCraft+1.12.2m
HungerOverhaul-1.12.2-1.3.1.jenkins142

**Comment by MatrexsVigil** [comment]
This is an issue with Hunger Overhaul.
