### ISSUE TITLE
Gardens generate anyway even if the generation is disabled

### ISSUE THREAD

**Issue by Insane96** [MatrexsVigil/harvestcraft#143]

**Comment by Pulverizer** [comment]
Had the same issue with Beehives. Want to use purely forestry bees.

**Comment by Insane96** [comment]
For behives check back the config. The new config may have reenabled them

**Comment by Pulverizer** [comment]
Well, I haven't updated since I set the config so I wouldn't think so? Idk if a newer version has fixed it.

**Comment by Guinaro** [comment]
Yes, I disabled the gardens and soggy gardens keep generating on my plains.
Have a limited world setup (only plains, beach, river and ocean with OTG) and Soggy gardens do spawn, while disabled in the config file. Harvestcraft 1.12.2q version.
