### ISSUE TITLE
Hangs on "Loading World Building Terrain" (Realistic Terrain Generation)

### ISSUE THREAD

**Issue by viper2g1** [MatrexsVigil/harvestcraft#144]
Referencing this from Realistic Terrain Generation as well:  Team-RTG/Realistic-Terrain-Generation#853

**Affected Mod Versions:**

Forge version: 12.18.1.2014
RTG version: Alpha 6
Pam's HarvestCraft version: 1.9.4-1.10.2a

**Issue Description:** 

When Pam's HarvestCraft is included in the modpack that has RTG it will throw errors when generating the world.  If HarvestCraft is removed the world generation does occur, albeit slowly.

**Steps to reproduce the issue: (If it's easily reproducible.)**

Ensure Pams HarvestCraft and RTG are included in the mods folder
Select RTG generation in options
Generate new world

**Extra Information:**

Minecraft Crash Report: https://gist.github.com/viper2g1/efa72a96464b366e92425f9ff6480b07
Client Log: https://gist.github.com/viper2g1/07860bc5d79acb77309b69c9c610e4cf
Identification of the issue on Minecraft Forums: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2524489-realistic-terrain-generation-rtg-realistic-biomes?comment=3158
Another Pastebin of the crash: http://pastebin.com/fui7sHTX

**Comment by MatrexsVigil** [comment]
I have no idea how to fix this.  =(

**Comment by GordonHollow** [comment]
Same crash with GregTech - worldgen function
