### ISSUE TITLE
[1.11.2] Drawers are invisible / broken with Pams stuff inside

### ISSUE THREAD

**Issue by LeaHarvey** [MatrexsVigil/harvestcraft#145]
Drawers with pams stuff in them are invisible or pink/black when chunks are loaded.  If i clear the drawer it looks normal again, even if i put the same stuff in there i just cleared out. Apples on trees are dropping as pink/black cubes.

![2018-01-30_21 03 10](https://user-images.githubusercontent.com/35974857/35592616-dfbc2000-060d-11e8-85b6-93398d699612.png)
![2018-01-30_21 03 20](https://user-images.githubusercontent.com/35974857/35592617-dfd7830e-060d-11e8-8be5-2739c3efb978.png)
![2018-01-30_21 04 03](https://user-images.githubusercontent.com/35974857/35592618-dff0780a-060d-11e8-8de0-547176c7f420.png)

**Comment by MatrexsVigil** [comment]
I am not supporting any version other than 1.12.2 right now.
