### ISSUE TITLE
Way to convert harvestcraft's fish into vanilla fish

### ISSUE THREAD

**Issue by WeaselOnaStick** [MatrexsVigil/harvestcraft#149]
There are recipes in many other mods that need only vanilla fish.

**Comment by Pulverizer** [comment]
I think harvestcraft is using oredict for this so other mods (if coded correctly) can automatically use harvestcraft items?

**Comment by MatrexsVigil** [comment]
I've fixed this in 1.12.2p  - You can put any HC fish in the crafting grid to get a normal Vanilla fish.
