### ISSUE TITLE
[1.12] Client crashes when near to a placed Market (1.12c)

### ISSUE THREAD

**Issue by Krowerom** [MatrexsVigil/harvestcraft#15]
Clent crashes to desktop when player is near to a placed Market block.  This doesn't happen immediately - I traded and got a sapling, then kept crashing back to desktop.  I managed to get around it by removing the block in creative (once I managed to get close enough).
Another of my players placed a market, went to get emeralds to trade for an item, and crashed when he got close again.
This is a severe issue, as that player cannot log in again until the block is removed somehow (after a lot of login attempts by an OP in creative).
p.s. You've done a great job of the conversion, Pam :) Thank you for your hard work!

**Comment by Krowerom** [comment]
I've only managed to "fix" this by loading the world into MCEdit and removing the Market block there.

**Comment by MatrexsVigil** [comment]
If you are still experiencing this crash after updating to HarvestCraft 1.12.2L and Forge 2555+, please re-post here: https://github.com/MatrexsVigil/harvestcraft/issues/127
