### ISSUE TITLE
[1.10.2] Pam's HarvestCraft cannot craft candles.

### ISSUE THREAD

**Issue by shortybsd** [MatrexsVigil/harvestcraft#153]
**Forge Version:** forge-1.10.2-12.18.1.2056-universal
**Pam's HarvestCraft version:** Pam's HarvestCraft 1.9.4-1.10.2b

JEI doesn't show recipe for candle and unable to craft with one string and one beeswax

**Comment by remeisigma** [comment]
Can confirm this is still the case in Forge 12.18.1.2073 (opened another issue, actually, before I saw this one. Closed that issue and posted here.)

**Comment by remeisigma** [comment]
Most recent update fixed this! I now have pretty white candles all over my house.

**Comment by LieseDenise** [comment]
Closed

**Comment by LieseDenise** [comment]
LieseDenise/harvestcraft#153

**Comment by LieseDenise** [comment]
LieseDenise/harvestcraft#153 closed

**Comment by Iteries** [comment]
Not closed, you can do **_white candles_** but not colored, nor is the recipe in where to place said dyes on the harvestcraft wiki.

**Comment by remeisigma** [comment]
Huh, I'll have to examine more - I thought JEI gave me the recipes for the colored ones when I searched. I'll check later tonight and report back.

**Comment by Iteries** [comment]
Oh the candles, I ran into another problem.  I have using a stack of them I made up in a dungeon crawl and only the first candle placed down was giving off any light.  The rest there after was just looks.  I did space them out pretty far at least 15-30 paces (paces= 1 blocks)

**Comment by remeisigma** [comment]
Popping back in to confirm - I can make colored candles with 4 white candles and 1 dye. JEI tells me it's a formless recipe, but the default is 3 candles across the top, a candle on the left-middle, and dye in the middle. 

Idk about the light, though. Haven't sat down to play creative, and don't have enough wax to make more than just a couple candles.

**Comment by Syndaryl** [comment]
I can confirm, neither the white candles nor the coloured ones are lighting up things. This is with release 1.10.2f, forge 2095, and Optifine running without any shaders. New light objects from other mods work fine, such as the white candles added by Forestry.
