### ISSUE TITLE
Sunflower Seeds cannot be planted

### ISSUE THREAD

**Issue by remeisigma** [MatrexsVigil/harvestcraft#157]
Forge 12.18.1.2073, Minecraft 1.10.2 - Sunflower seeds (crafted from sunflowers) cannot be planted in tilled dirt.

**Comment by JunpakuRaven** [comment]
You get more sunflowers via the vanilla method of applying bonemeal to the flower itself, another sunflower will pop off.

**Comment by Syndaryl** [comment]
Seems weird to not have them as a normal old crop, just like everything else. I don't see why they're so valuable that they should need bone-meal to reproduce.

**Comment by remeisigma** [comment]
That was my thought. The harvestcraft wikia says they should be plantable, but idk how official/current that is.

**Comment by josh-parris** [comment]
Given the conversion rate of two sunflowers into two sunflower seeds, which would be planted into two sunflower plants, the only advantage you would get from "farming" sunflowers is you can control their location.

**Comment by Syndaryl** [comment]
It's a different appearance on Farmland than on Grass; one is agricultural, one is a wild field. Farmland also has the advantage of not allowing monster spawns >.>
