### ISSUE TITLE
Chestnut and Almonds craft Flour and not butter

### ISSUE THREAD

**Issue by JSW-TheOtherOne** [MatrexsVigil/harvestcraft#157]
The recipes for the butteritem and the flouritem are the same. The game defaults to crafting Flour.

**Comment by Lethann** [comment]
Came here to report this as well.

Running FTB Revelations 1.4.0 so not sure if it's a modpack specific error

**Comment by ElvenChaos** [comment]
The recipe conflicts are self-contained. Funny enough, nut-flours and nut-butters are pretty much made the same way, so the conflict makes total sense, and yet I currently have no idea what ingredient to add to differentiate the recipes. I learned something new thanks to a recipe conflict in a mod, thanks pam xD.

I caught the conflict in a craft tweaker recipe conflict scan, here are the results I got that only pertain to harvest craft:
```
[Shapeless] (Flour) <harvestcraft:flouritem:0> * 1 conflicts with [Shapeless] (Chestnut Butter) <harvestcraft:chestnutbutteritem:0> * 1

[Shapeless] (Flour) <harvestcraft:flouritem:0> * 1 conflicts with [Shapeless] (Almond Butter) <harvestcraft:almondbutteritem:0> * 1

[Shapeless] (Lemonade) <harvestcraft:lemonaideitem:0> * 1 conflicts with [Shapeless] (Fruit Punch) <harvestcraft:fruitpunchitem:0> * 1

[Shapeless] (Cotton Seed) <harvestcraft:cottonseeditem:0> * 1 conflicts with [Shapeless] (Cotton) <harvestcraft:cottonitem:0> * 1  (I had Natura cotton on when I ran this scan, not sure if that will affect this entry)
```

**Comment by JSW-TheOtherOne** [comment]
Recipes changed, issue fixed!
