### ISSUE TITLE
[1.10.2] Presser does not disallow item input into output slots

### ISSUE THREAD

**Issue by JonoColwell** [MatrexsVigil/harvestcraft#16]
The presser will input into all available slots, even when using a hopper from vanilla.

http://i.imgur.com/3gEwdSa.png

**Comment by xenoflot** [comment]
Confirmed.  I feel this is a bug because it prevents automation even with vanilla hoppers. 

Forge 14.23.0.2512
HC 1.12-1.2.6-18

**Comment by pixzi** [comment]
Still an ongoing issue, playing Simple life 2. Trying to automate soybeans, and this happens. Any sign of a fix?

**Comment by MatrexsVigil** [comment]
Not accepting non 1.12.2 bug reports at this time.

**Comment by JonoColwell** [comment]
Ignore me. Incorrect bug.
