### ISSUE TITLE
[Bug] Extreme Beetroot Spam

### ISSUE THREAD

**Issue by MysticAura** [MatrexsVigil/harvestcraft#164]
MC: 1.10.2
Forge: 2068
Mod Version(s): 102b, 102c (possibly earlier versions as well)

Steps to recreate: Right-click harvest vanilla beetroot

Result: [Console/Log Output](http://pastebin.com/J62vSsUt)

This issue has been around a very long time and I look forward to seeing it resolved.

**Comment by bennyman123abc** [comment]
I think that might have been there for debug testing? I will look into it but for now, that is funny XDXD

**Comment by warlordjones** [comment]
Appears to be fixed.
