### ISSUE TITLE
[1.10.2] Missing Models

### ISSUE THREAD

**Issue by MrAmericanMike** [MatrexsVigil/harvestcraft#165]
I don't think this is an important bug, but definetly it spams the console a lot.
Not sure if I'm missing something, or if it's just missing models as for now.
Thanks for taking a look into it.

http://pastebin.com/G9jZFwxn

Using Pam's HarvestCraft 1.9.4-1.10.2d

**Comment by drakray** [comment]
![candlemissingmodel](https://cloud.githubusercontent.com/assets/4303126/18788974/144cd020-8177-11e6-8e85-373cdc4abc38.png)
