### ISSUE TITLE
1.8.9: Fertilized Dirt (Random Things) causes odd behavior for crops, however I found a workaround for the time being

### ISSUE THREAD

**Issue by Trisscar05** [MatrexsVigil/harvestcraft#166]
This is done with PHC 1.8.9a and Random Things 3.6.6 (1.8.9). Planting Harvest crops on fertilized dirt works fine as long as you don't plant other things directly next to them after. You can plant as many Harvest crops as you want in the same area as long as they are only DIAGONAL to each other, and MC Vanilla seeds won't break if you plant Harvest crops next to them, but the vanilla seeds will break harvest crops if planted second. If broken in this fashion the seeds do not drop. The plants grow just fine even with what look like bonemeal ticks going off, and can be harvested and (manually bonemealed) with right click without breaking or showing any other odd behavior.
This results in a checker board of vanilla and Harvest crops, and honestly I figured this was a cool new way of enforcing that farming technique where you plant different crops together to ward off pests, but then I tried the Harvest crops on regular tilled dirt and found it only applied to fert. dirt.
I should also mention that I am using Forge 11.15.1.1902 in a vanilla profile, and have things like Pixelmon, Chameleon, Mantle, Chisel, Roguelike Dungeons, Buildcraft, and denseores installed, of the ones I can think of that do anything to the world or the code in general.
I did notice that this has been reported before, but that was done with only one low on detail sentence without mention of the environment, so I figured I should attempt to add as much detail as I could.

**Comment by bondgb** [comment]
In 1.10 I can't seem to plant any seed from Harvestcraft on RandomThing's fertilized dirt. Would love support.

**Comment by Trisscar05** [comment]
Did you till it first? Also can you plant wheat seeds and potatoes and such on it just fine?

**Comment by bondgb** [comment]
Yeah, I tilled it. Other seeds plant fine, just not Harvestcraft ones.

**Comment by Trisscar05** [comment]
May I ask what if any other mods you have installed? In case this is another mod entirely causing the issue.

**Comment by bondgb** [comment]
Never mind, it is actually working when I use it manually. When I use it alongside a EnderIO Farming Station it won't plant Harvestcraft seeds on the fertilized soil (it does plant vanilla crops though)

Also I'm experiencing the same bug as you, not being able to plant two of the same crops alongside each other on fertilized soil.

**Comment by MarkL4YG** [comment]
duplicate #154

**Comment by warlordjones** [comment]
Should be fixed.
