### ISSUE TITLE
Pams harvestcraft not appearing in JEI/none of the recipies are craftable, even though the mod is installed both server and client side. 

### ISSUE THREAD

**Issue by Ozimundis** [MatrexsVigil/harvestcraft#167]
Been having this issue for a little while now, over a couple of specific modpacks, Donutcraft and Spilled Juice. 

The mod is installed, yet, when doing "@Pam" or "@Harvest" in JEI brings up nothing. 
However, when looking through different food recipes, the JEI models/sprites appear, but hovering over them, nothing appears and as I'm writing this, It seems that trying to craft anything causes a ctd, in this case, the pestle. 
(Pastebin of crash http://pastebin.com/cqyCzZsb )

Also, on joining the server there are these error messages appearing in chat. 
https://gyazo.com/2b1085bc4abf07bc6cb3f1beeae13272

However, testing in a singleplayer world, using the pestle appears in the creative menu and when hovering over it, the tooltip appears and shows it's name, like it would normally. As does crafting said item. 

The pack is Spilled Juice available on the AT Launcher, pack version 0.1.15, the version of pams is Pams HarvestCraft 1.9.4-1.10.2d (We just updated to .15 of the pack, however this issue has been present for some time.)

In writing this I'm not 100% sure if this is directly a harvestcraft issue or something unrelated, however, this has been persistent over a few separate, unrelated packs.

**Comment by drakray** [comment]
Have you found the source of your problem? because I can say it's not a Harvestcraft issue, as it work perfectly alone or in some other pack(also your other referenced issue is closed so)

**Comment by Ozimundis** [comment]
Apologies, I forgot to close this. We figured it out, the hosting company messed up, the pams file was only 4kb! A re-upload from my pc fixed it.
