### ISSUE TITLE
[1.10.2] Apiary Not Working

### ISSUE THREAD

**Issue by Nephatrine** [MatrexsVigil/harvestcraft#177]
I have an apiary with a queen bee in it. It's been several days (in minecraft) without any progress in the apiary. No products are being created and the queen has taken no damage yet. I have a wide variety of vanilla flowers around the apiary. Is there something else I'm missing?

Using:
Pam's HarvestCraft 1.9.4-1.10.2f
FML 2094

**Comment by warlordjones** [comment]
Should be fine in 1.11.2.
