### ISSUE TITLE
[1.12] Apiary/Presser doesn't have a block break time

### ISSUE THREAD

**Issue by Discomanco** [MatrexsVigil/harvestcraft#18]
Apiary and Presser currently breaks instantly, with any tool (and hand), and doesn't drop its contents, like the Queen Bee inside it and potential honey/wax.

But hey, at least it's craftable after the latest update, so that's very much appreciated :D 

EDIT: Added Presser too

**Comment by MatrexsVigil** [comment]
Fixed in 1.12.1c (coming soon).
