### ISSUE TITLE
Fruit tree sapling recipe [v1.10.2] 

### ISSUE THREAD

**Issue by Iteries** [MatrexsVigil/harvestcraft#180]
The recipe for fruit tree or any creation of making food bearing saplings is not working.  Not sure suppose to be as such but would like to have said feature return.  Getting to a ''market'' to buy not so easy to find.

Thanks

**Comment by Syndaryl** [comment]
Fruit tree sapling is working: are you using two fruits or three? It was changed to 3 as a balance measure.

**Comment by Iteries** [comment]
AH! I thought it was still one.  I will try next time playing.  Oh, there a specific placing in the 3x3 table?

**Comment by Syndaryl** [comment]
I'm not sure if it IS a shaped recipe, but I always do it as 
```
SF
FF
```
Where S is sapling, and F is fruit/nut/whatever.

**Comment by bennyman123abc** [comment]
I will look into making it a shapeless recipe if it is not already

**Comment by LieseDenise** [comment]
It is shapeless. I make mine by putting the sapling in the center bottom and the fruit around that.

**Comment by bennyman123abc** [comment]
Ok. The issue can be considered resolved now.

**Comment by Iteries** [comment]
Nods, closed and thank  you.
