### ISSUE TITLE
[1.12.2] Forge Server Crash with HarvestCraft 1.12.2s

### ISSUE THREAD

**Issue by fandomaniac** [MatrexsVigil/harvestcraft#180]
I crashed with HarvestCraft 1.12.2s running Forge 1.12.2: 14.23.2.2611 (recommended build)

Here's my crash log:
https://pastebin.com/nEnvTAHi

I also replied under the similar Sponge crash report. I apologize for the duplicate post. I just wanted to make sure this was flagged for Forge as well.

**Comment by Pythonic-Rainbow** [comment]
Same crash in Forge 2636

**Comment by panoskj** [comment]
Does this happen on a physical server? Because func_185359_l is getBiomeName and getBiomeName is declared as client-sided only. Moreover the name is queried just to be printed in the log file. If that's the issue, fixing it should be a matter of skipping the name.
