### ISSUE TITLE
Candles Do Not Emit Light As Of 1.9.4-1.10.2g

### ISSUE THREAD

**Issue by iBELLinc** [MatrexsVigil/harvestcraft#184]
This issue was brought up in issue https://github.com/MatrexsVigil/harvestcraft/issues/153 but this is not directly related to the original topic. 

Issue: When candles of any color (or white) are placed in the world they give the "flame" animation of the torch but do not actually give off any light.

The following pictures were taken in the same exact location. The only difference between the two is the placement of either a candle or a torch. You can easily see that the candles are not giving off any light. The only mod loaded is Harvestcraft so it is not a mod compatibility issue.

![candlelight](https://cloud.githubusercontent.com/assets/7228683/19834527/4d258d5e-9e39-11e6-93f0-dfe0455ff44a.gif)

**Comment by warlordjones** [comment]
Will be fixed in latest (1.11.2) build.
