### ISSUE TITLE
Question: in 1.10.2 how do we make soymilk?

### ISSUE THREAD

**Issue by Kaisoul** [MatrexsVigil/harvestcraft#186]
what's the recipe for soymilk in 1.10.2?

**Comment by remeisigma** [comment]
IIRC, you need to put soybeans in the presser and then (maybe? Someone who's actually on can confirm) press the tofu product as well.

**Comment by Kaisoul** [comment]
yea just found out i gotta press soybeans to get silky tofu  then press the
silky tofu to get soy milk  O_o   so wished jei had that info lol

**Comment by brodycas3** [comment]
Yeah I also wish it had jei support.

**Comment by warlordjones** [comment]
#209
