### ISSUE TITLE
automation appears not to work

### ISSUE THREAD

**Issue by kotoroshinoto** [MatrexsVigil/harvestcraft#19]
for instance to autocraft used up queens, combine with larva and re-insert them into an apiary. I can't seem to figure out how to get this to work.

**Comment by kotoroshinoto** [comment]
there is a similar problem with keeping traps filled with bait

**Comment by kotoroshinoto** [comment]
hoppers and other inventory emptiers also empty the bait slot unless they can filter which items they pull

**Comment by nevercast** [comment]
Good to see an issue for this is already provided. I too cannot push items in to HarvestCraft machines. But pulling from them (in my case, using LogisticsPipes. Though everything is the same). Works fine.

**Comment by nevercast** [comment]
Seems this is intended.
https://github.com/MatrexsVigil/harvestcraft/blob/master/java/com/pam/harvestcraft/TileEntityPamFishTrap.java#L358-L361

I'm likely going to rebuild this mod for my own use with the validator coded in. But as for HarvestCraft. Having this as a default: no automation; configuration would be great.

**Comment by kotoroshinoto** [comment]
Somewhat obnoxious to deliberately block automation without allowing us to change it in a config.

**Comment by kotoroshinoto** [comment]
The code doesn't appear hard to fix as long as you know which slot that represents.

**Comment by nevercast** [comment]
The last slot is the input slot.
All the others are output slots.

It's copy-paste from the apiary (Could have extended a common base class, but it works regardless)
