### ISSUE TITLE
Some Items missing - Violet/Black tiles

### ISSUE THREAD

**Issue by TheRealDadbeard** [MatrexsVigil/harvestcraft#190]
Most of the cake recipes are missing and have no icon, like that one apple too.
![2016-11-08_16 29 49](https://cloud.githubusercontent.com/assets/23340600/20105259/397c6fbc-a5d1-11e6-9a2e-6f01bf502f4a.png)
![2016-11-08_16 29 45](https://cloud.githubusercontent.com/assets/23340600/20105260/398345da-a5d1-11e6-94fa-ad6fcb84d840.png)

**Comment by mankra** [comment]
These items are listed twice in the JEI item list and only the second one is missing its texture. They should be removed. Here's a list of the affected items:

- Carrot Cake
- Cheese Cake
- Cherry Cheese Cake
- Chocolate Sprinkles Cake
- Holiday Cake
- Lamington
- Pavlova
- Pineapple Upside Down Cake
- Pumpkin Cheese Cake
- Red Velvet Cake

The apple is not listed twice as far as I can see.

Forge version: 1.10.2-12.18.2.2120
HarvestCraft version: 1.10.2h
JEI version: 3.13.2.360

**Comment by mankra** [comment]
The-Fireplace [fixed the issue](https://github.com/The-Fireplace/Adobe-Blocks/issues/7), maybe he can help.

**Comment by warlordjones** [comment]
Should be fixed in the upcoming 1.11.2 release.
