### ISSUE TITLE
[1.12.2] Immature gooseberries being harvested with actual fruit

### ISSUE THREAD

**Issue by Geethebluesky** [MatrexsVigil/harvestcraft#193]
On a private world with the latest Harvestcraft version 1.12.2t on Forge **2641**, whenever I harvest mature gooseberries off a tree, a number of immature crop items gets harvested along with the mature fruit.

This results in the crop itself staying on the tree and maturing again as normal, plus X mature gooseberry items in my inventory which register as normal food, plus a larger number of immature, placeable crops that I can't eat, with the texture for stage 1 growth.

I can go around placing those crops on neighboring trees and get 150 gooseberry trees in short order that way. 

Not sure what other info would be useful, I am running a number of other mods but this doesn't produce a crash or an error (nothing in the logs).

**Comment by Geethebluesky** [comment]
Okay well I also chopped down a gooseberry tree by mistake and it dropped the immature fruit items too.

**Comment by DevOpDan** [comment]
I am having the same problem. I'm not sure they are 'Immature' Gooseberries though, but rather the 'Crop' of the Gooseberry which can then be planted under leaves without needing seeds.

**Comment by Geethebluesky** [comment]
Yeah I mentioned that above. Normally you can't harvest immature fruit so it's technically the crop item. Are you on 1.12.2u by any chance or still using version t?

**Comment by DevOpDan** [comment]
Okay, it turns out Hunger Overhaul was actually causing this issue. They have since fixed it.
This can now be closed unless @Geethebluesky can confirm s/he isn't using HO.

**Comment by Geethebluesky** [comment]
Oh hey, thanks for adding that. I actually am using Hunger Overhaul!

Closed then. :)
