### ISSUE TITLE
Chicken Parmesan spelled incorrectly

### ISSUE THREAD

**Issue by Drakma** [MatrexsVigil/harvestcraft#194]
Spelled as Chicken Paramasan instead of Parmesan

**Comment by SpartanSamuel** [comment]
There's a handful of other spelling errors as well:

Incorrect - Correct
Manjuu - Manjū
Marshmellows - Marshmallows
Museli - Muesli
Nachoes - Nachos
Potato and Cheese Pirogi - Potato and Cheese Pierogi
Sausage in Bread - Sausage Bread
Spagetti - Spaghetti
Spagetti and Meatballs - Spaghetti and Meatballs
