### ISSUE TITLE
Harvestcraft is using a ton of item IDs for no good reason

### ISSUE THREAD

**Issue by MalkContent** [MatrexsVigil/harvestcraft#196]
Every item in harvestcraft is registered with it's own id, rather than using the metadata to differ them
As far as i can see, there is no good reason for that and harvestcraft is using up a lot of item IDs.

I can elaborate on the subject if needed :)

**Comment by Syndaryl** [comment]
Metadata food is notoriously cranky. Metadata objects in general play poorly with other mods.

This would be an annoyingly big rewrite, and I'm not sure what benefit you get out of this given that the item ID space was drastically revised in 1.8

**Comment by MalkContent** [comment]
How so? I asked in #minecraftforge beforehand, and aside from registering things for wolf food, there seems to be no issue with food items with metadata as far as they could tell me.

As for it being a big rewrite, it's mostly just busy work, changing the item registration. I could make a PR for that if that would be acceptable. And true, there is little benefit other than practicing good practice and maybe saving a meager couple of bytes in memory ^^

**Comment by warlordjones** [comment]
However, this would break previous worlds. Possibly to be done on the next major (i.e. breaking) Minecraft update.
