### ISSUE TITLE
Some HarvestCraft Blocks Cause Missing Textures on Other Placed Blocks in Chunk

### ISSUE THREAD

**Issue by DrGirlfriend** [MatrexsVigil/harvestcraft#2]
## Environment
- The New Frontier version 29
- MineCraft 1.11.2
- Forge 13.20.1.2388

## HarvestCraft Version
- Pam's HarvestCraft 1.11.2h.jar

## Problem
Some HarvestCraft Blocks Cause Missing Textures on Other Placed Blocks in Chunk

**NOTE:** Placed **Known Affected Mod Blocks/Items** are not all 100% affected with this issue within the chunk, only some

## Steps
1. Within a chunk place any of the **Known HarvestCraft Blocks**
2. Within the same chunk place any of the **Known Affected Mod Blocks/Items**
3. Exit world or go do something in another chuck for a while
4. Reload world or come back to chunk with placed blocks

## Results
Notice some of the **Known Affected Mod Blocks/Items** have missing textures

In cases like BiblioCraft, just the frames are present without the wood paneling

## Workaround
1. Remove **Known HarvestCraft Blocks** from chuck
2. Exit world or go do something in another chuck for a while
3. Reload world or come back to chunk with placed blocks

## Known HarvestCraft Blocks
- Presser
- Apiary
- Market

## Known Affected Mods and Known Affected Mod Blocks/Items
- BiblioCraft[v2.3.2][MC1.11.2].jar - Potion Shelf, Chests
- buildcraft-7.99.4.jar - Pipes (wooded, stone, gold, void - Fluid and/or Item)
- StorageDrawers-1.11.2-4.2.9.jar and StorageDrawersExtras-1.11.2-2.0.0.jar - Any of the wood Drawers

## Logs
[Logs.zip](https://github.com/MatrexsVigil/harvestcraft/files/1177901/Logs.zip)

**Comment by Dr-Zoidberg-de** [comment]
Finally i found this... was regenerating chunks for hours (and re-decorating the house) never expected my market to be the issue. on all the mods2 its causing an instant crash for every player who trys to render stuff in hte affected chunk if there are thermal expansion machines together with the known harvestcraft blocks in one chunk(i think the missing textures crash the client... logs wont tell anything useful sadly

**Comment by groulot** [comment]
Hello. We hit a similar issue on our server, I would find my bibliocraft tool rakes rotated 90 degrees (taking and putting back a tool would fix it temporarilly), my base was crashing with TE machines too, we had to remove TE as a result. I had a Pam apiary and presser.
Here are some details in my case: only some tool rakes would rotate. Breaking and placing it one block up/down or left/right would make it behave.

Immersive engineering wire connectors would also rotate. It was all visual, the power would still pass through, I think everything was fine from the server's point of view.

**Comment by MatrexsVigil** [comment]
Fixed in 1.12.1b
