### ISSUE TITLE
Tree generation bug

### ISSUE THREAD

**Issue by xsi93** [MatrexsVigil/harvestcraft#2]
Self explanatory title, there are 3 different kinds of fruit growing from a single tree (in this example: Grapefruits, apricots and almonds)
![3 fruits in 1 three](https://cloud.githubusercontent.com/assets/8198874/7107407/f7fa08d8-e164-11e4-9652-01d99ca677c7.png)

**Comment by Ianaver** [comment]
confirmed, quite rare though, the trees must have been different heights and at the same block
