### ISSUE TITLE
Unlimited seeds from the Market

### ISSUE THREAD

**Issue by LyraelRayne** [MatrexsVigil/harvestcraft#20]
Originally reported on the Obscurity modpack issue tracker. I've copied most of wlhlm's excellent bug report from here and added my own bits: https://github.com/SnowShock35/Obscurity/issues/213

It is possible to get free seeds/saplings from the market block with NEI installed

Steps to reproduce:
1. Place a market block
2. Right-Click Market block
3. Drop Emeralds into the slot
4. Select an item recipe in NEI while still in Market GUI
5. Press Backspace to go back into Market GUI
6. Buy seed/sapling

Observed behaviour:

Buying seeds/saplings in Step 6 won't decrease the number of Emeralds put into the Market making it free essentially.

It actually looks like in the background when the NEI opens the emeralds are dropped on the ground.

Minecraft 1.7.10
Forge 10.13.4.1448
Mods installed: 
Pam's HarvestCraft 1.7.10j
NotEnoughItems 1.7.10-1.0.4.107
CodeChickenCore 1.7.10-1.0.6.43
Waila-1.5.10_1.7.10

**Comment by wlhlm** [comment]
This still happens with 1.7.10k

Here's a visualization:
![harvestcraftmarketcut](https://cloud.githubusercontent.com/assets/1928113/11200174/f61afcb4-8cd3-11e5-8a2e-df8d03987980.gif)

Pam's Harvestcraft 1.7.10k Working
NotEnoughItems 1.0.5.118
CodeChickenCore 1.0.7.47
Forge 10.13.4.1558
