### ISSUE TITLE
Switch over to Capabilities

### ISSUE THREAD

**Issue by TechnicianLP** [MatrexsVigil/harvestcraft#204]
Capabilities are a "new" Addition in Forge (http://mcforge.rtfd.io/en/latest/datastorage/capabilities/)
This includes a Inventory Capability which is now used instead of IInventory (which your TileEntites still use) 
The new System is far more modular which leads to most mods dropping support for the Vanilla IInventory because Forge added Capabilities to Vanilla Blocks

TL;DR: Switch over to Capabilities they are newer (and better) than the now broken IInventory

**Comment by warlordjones** [comment]
In progress.
