### ISSUE TITLE
[1.12.2] Trees cannot generated in OTG generator

### ISSUE THREAD

**Issue by KorDum** [MatrexsVigil/harvestcraft#204]
Plants generated fine, but no one tree around...
I used OpenTerrainGenerator v6 + BiomeBundle and HarvestCraft 1.12.2t

**Comment by ghost** [comment]
Please post your crash report or last log

**Comment by KorDum** [comment]
I created simple modpack for client and server:
- Forge 14.23.3.2655
- OpenTerrainGenerator v6
- Pam's HarvestCraft 1.12.2t

No fruit trees around.
https://gist.github.com/KorDum/359757517d6f909f434fd7fd968d6063

**Comment by ghost** [comment]
I am looking. Waiting please . . .

**Comment by KorDum** [comment]
Thanks for answer!

**Comment by ghost** [comment]
Is this what you want?

![2018-04-21_15 07 23](https://user-images.githubusercontent.com/10398117/39084415-d946269c-4575-11e8-8676-f3a5ddd2ed6c.png)

**Comment by KorDum** [comment]
I want fruit trees from Harvestcraft to be generated in OTG biomes that replace vanilla biomes.

**Comment by ghost** [comment]
This is a problem of OTG. With F3 you can see the Minecraft Boime, but Harvestcraft does not recognize OTG's New Biomes because OTG does not give new names.

Possible solutions:

1. Report this Bug to OTG
or
2. Instead of OTG there are still Biomes o Plenty
     You can also install Custom Biomes there.
     Is also Stable.

**Comment by ghost** [comment]
This you can do. . . 

Download and paste this config in the config folder.
With this you can play the OTG and the trees drop ot of the gardens.

[harvestcraft.zip](https://github.com/MatrexsVigil/harvestcraft/files/1935894/harvestcraft.zip)

Hope can help

**Comment by KorDum** [comment]
Thanks for answer. I'm grateful for the help with the config.

**Comment by fllo** [comment]
Tree generation is whitelist only. And there are currently no defaults for OTG.
As written in #320, I will look into it.
