### ISSUE TITLE
Can't Make Woven Cotton

### ISSUE THREAD

**Issue by bob0bob** [MatrexsVigil/harvestcraft#21]
I know you say all recipes are working but there is no way to make woven cotton.   Only recipe attached to it is using 3 woven cotton to make woven cotton.
I see on the internet all over it says to use 2 string to make woven cotton inside JEI, it show no recipe and when you try that it doesn't work.

**Comment by bob0bob** [comment]
Dug through the recipes and there is nothing to make woven cotton except to use 3 woven cotton to make 3 woven cotton.  That file needs to be updated, if you intended 2 string.  Please update it.
I've update my file wovencottonitem_x3.json  and changed it to string to make 1 woven cotton.

thanks ahead of time.

**Comment by MatrexsVigil** [comment]
Fixed in 1.12.1b
