### ISSUE TITLE
Some recipes won't work

### ISSUE THREAD

**Issue by ghost** [MatrexsVigil/harvestcraft#22]
Recipes that I have used before in previous versions of the game won't work. Most of the recipes that include the juicer don't work and the recipe for cheesecake won't work either. I'll update this list if I find other recipes that don't work.

**Comment by bob0bob** [comment]
I"ve tried the apple juice, and apple smoothie and cactus.  They worked for me in the latest.

**Comment by killfalcon** [comment]
Which version were you using, helenhoang? Harvestcraft has several versions live at once for different versions of Minecraft, so it's tricky to find problems without knowing which of them is having issues.

**Comment by ghost** [comment]
1.12.1c

**Comment by ghost** [comment]
Sorry, 1.12c

**Comment by MatrexsVigil** [comment]
Fixed in 1.12.2e
