### ISSUE TITLE
Apiary dropping new Queen Bees after they are done.

### ISSUE THREAD

**Issue by ScidaJ** [MatrexsVigil/harvestcraft#227]
The apiary is dropping new, usable queen bees after their durability is over. It removes the need for grubs. Version is 1.12.2u

**Comment by Geethebluesky** [comment]
You double-checked to make sure the configuration file wasn't reset to always have Queen Bees as the last item?

**Comment by ScidaJ** [comment]
My apologies, you are correct, I didn't even know that was a setting, thank you.
