### ISSUE TITLE
[1.11.2c] Queen bees not crafting into jelly

### ISSUE THREAD

**Issue by elfin76** [MatrexsVigil/harvestcraft#229]
Using 1.11.2c, queen bees with a durability of 0 do not craft into royal jelly in the crafting grid.

**Comment by IamAlathe** [comment]
I had this issue too, then I thought that maybe the bee wasn't totally exhausted, despite appearing to be so.  I put it back in the apiary and it kept making goodies for me.  So maybe the durability bar is incorrect?  I can't do further testing, as I'm not playing with this mod anymore, I lost 2 worlds from having the presser running.

**Comment by crzo** [comment]
I also have this problem. 
I tried it with a fresh bee and with a empty bee. Both wont turn into a royal jelly.

I tried 1.11.2e.

I try to prepare a fix for it.

Cheers,
Chris
