### ISSUE TITLE
Dedicated Server Randomly Crashes While Using "Shipping Bins"

### ISSUE THREAD

**Issue by carstorm** [MatrexsVigil/harvestcraft#23]
Dedicated servers will crash what seems like randomly when selling things using the shipping bin, client doesn't crash. Attached are the 2 latest crash logs both giving a  "java.util.ConcurrentModificationException" error. I attached two to hopefully be of more help.
[crash-2017-08-13_12.02.16-server.txt](https://github.com/MatrexsVigil/harvestcraft/files/1223151/crash-2017-08-13_12.02.16-server.txt)
[crash-2017-08-14_11.19.01-server.txt](https://github.com/MatrexsVigil/harvestcraft/files/1223152/crash-2017-08-14_11.19.01-server.txt)

**Comment by MatrexsVigil** [comment]
If you are still experiencing this crash after updating to HarvestCraft 1.12.2L and Forge 2555+, please re-post here: https://github.com/MatrexsVigil/harvestcraft/issues/127
