### ISSUE TITLE
Recipe bugs

### ISSUE THREAD

**Issue by Xandoria** [MatrexsVigil/harvestcraft#239]
Hello,
When I was translating your mod into French, I happened to find a few bugs:

- The Ice cream recipe is:
mixing bowl + milk + snowball + salt

     Shouldn't it be?
     mixing bowl + **cream** + snowball + **sugar**

- You are mispelling Lasagna in all the entries and variables (it is written Lasanga, you switch the n and the g)

- An apple item appears with no icon in your item's list (tile.pamapple.name). Maybe you could remove it, since there is already an apple in vanilla minecraft and you are using that one in your recipes.

-Xandoria-

**Comment by MatrexsVigil** [comment]
Salt is used in the process of making ice cream, which is why I included it.

Lasagna and mushroom lasagna will now be spelled right.

I'll fix the apple issue if I can!

Thanks!  Changes will be in 1.11.2h
