### ISSUE TITLE
[Request] SaltyMod integration

### ISSUE THREAD

**Issue by mankra** [MatrexsVigil/harvestcraft#240]
There's a mod called[ SaltyMod](https://minecraft.curseforge.com/projects/saltymod) which I think would be a good companion for Harvestcraft. Unfortunately, the salt from Harvestcraft is incompatible with the one from SaltyMod.

I'm using CraftTweaker for now to make it possible to convert the one salt to the other. But it would be nicer if Harvestcraft would use the "Pinch of Salt" from SaltyMod in it's recipes and provide a config setting for disabling the crafting from Water bucket, as long as SaltyMod is detected.

**Comment by Syndaryl** [comment]
If SaltyMod adds their pinch of salt to the oreDict as "dustSalt", it will automatically be picked up by Harvestcraft, along with Mekanism and probably a bunch of other mods. The OreDict is the core feature for cross-mod compatibility.
