### ISSUE TITLE
Where can I find recipes in this github site

### ISSUE THREAD

**Issue by CollapsedMondas** [MatrexsVigil/harvestcraft#246]
Pam said to go github when searching for recipes. but i can't find it.
Where should I go?

**Comment by MatrexsVigil** [comment]
https://github.com/MatrexsVigil/harvestcraft/blob/1.11.2/src/main/java/com/pam/harvestcraft/item/RecipeRegistry.java

https://github.com/MatrexsVigil/harvestcraft/blob/1.11.2/src/main/java/com/pam/harvestcraft/item/PresserRecipes.java
