### ISSUE TITLE
No way to access config

### ISSUE THREAD

**Issue by LiaoRoy** [MatrexsVigil/harvestcraft#249]
Pam describes the hunger overhaul as modular and able to be disabled in the config, but the config is unable to open in minecraft 1.12 forge.

**Comment by ToMe25** [comment]
@LiaoRoy Just edit the Config File( .minecraft/config/harvestcraft.cfg ) :)

**Comment by MatrexsVigil** [comment]
Yes, I haven't been fancy enough to enable the config opening in Forge.
