### ISSUE TITLE
1.7.10 Localization

### ISSUE THREAD

**Issue by avescarelo** [MatrexsVigil/harvestcraft#25]
Hi, I corrected and added Russian localization for **Pam's HarvestCraft 1.7.10Lb**, because it was not complete.

[ru_RU.zip](https://github.com/MatrexsVigil/harvestcraft/files/1226303/ru_RU.zip)

Please check and add it.

**Comment by MatrexsVigil** [comment]
Not accepting non 1.12.2 bug reports at this time.

**Comment by avescarelo** [comment]
This is not bug report, they its fix locslization
