### ISSUE TITLE
1.12.2u Ground traps picky about height, water filter doesn't accept fresh water

### ISSUE THREAD

**Issue by ZephyrWindSpirit** [MatrexsVigil/harvestcraft#256]
Hi there. I tried to use the ground trap up about y 205 in the Alps, and the ground trap didn't start consuming the bait. When I took it back down to y 65, it worked fine. It appears your ground trap has issues with different world heights. Would you mind looking into this please?

Even with a bunch of woven cotton inside the machine, the water filter won't accept freshwater items to make salt. 

Please consider looking into these and thank you for your time.

**Comment by AWolters-ru** [comment]
First of, it might be better to split of the water filter issue into its own issue. Second, the height should not matter, it not looked at anywhere in the code. Can you try to get one ground trap working and one not working in the same save at the same time? If so, please upload it to the cloud and link it here.

**Comment by ZephyrWindSpirit** [comment]
I did a little more research and asked around. Turns out you need two blocks worth of grass on one side of the trap for it to work properly regardless of world height. 
And I figured out how the water filter works. So the issue is closed. Thank you. 

ex. 
     x x x x
     x T x x
     x x x x

x - grass block
T - ground trap
