### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by Kashdeya** [MatrexsVigil/harvestcraft#257]
Why are you all dropping support for 1.10.2? 100% of the problems in 1.10.2 are easy to fix and are still in 1.11.2 from the looks of it. So why drop support for the most played version of the mod at this time?

**Comment by PapiDimmi** [comment]
I agree. 1.10 has a much bigger modding community than 1.11.

**Comment by MatrexsVigil** [comment]
I only have enough brain power to support one version of Minecraft at a time.  Sorry.

**Comment by PapiDimmi** [comment]
This is completely up to you, but 1.10.2 has a bigger modding community; more mods, more modpacks, _etc._ Why support 1.11.2?

**Comment by PapiDimmi** [comment]
I know it’s completely up to you as to which version to update your mod for, but 1.10.2 has a bigger modding community; more mods, more modpacks, _etc._, so why support 1.11.2?
