### ISSUE TITLE
1.10.2 Version Compatibility 

### ISSUE THREAD

**Issue by yepidoodles** [MatrexsVigil/harvestcraft#264]
This may have been suggested before, but just in case, here it is;

McJty (Dev of RFTools) has made a mod which helps you make mods compatible with both 1.10.2 and 1.11.2 so you don't need to make 2 versions of the same mod.

https://minecraft.curseforge.com/projects/compatlayer

I was hoping you may consider using it so that players can use the updated versions in 1.10.2. Many modpacks and server aren't ready to move onto 1.11.2 leaving 1.10.2 modpacks/servers needing fixes which will never come.

I completely understand if you don't want to do this, but on behalf of most public servers, I ask anyway.

Thanks

- Alice

**Comment by MatrexsVigil** [comment]
I'm sorry, but I am not interested in supporting multiple versions of the mod.  I will be doing so if my Patreon reaches its max goal, otherwise, I will always and only be supporting the latest modded version of Minecraft to ease my sanity.
