### ISSUE TITLE
Suggestion for additional soda

### ISSUE THREAD

**Issue by AsuraTakun** [MatrexsVigil/harvestcraft#266]
I'm looking through the soda available, and I find it fairly limited. Here are some ideas for additional soda off the top of my head:

- Mango Soda
- Melon Soda
- Peach Soda

This would take a little more effort, but possibly flavor mixing:

- Cherry Cola/Rootbeer/Lemon-lime
- Blackberry Rootbeer (seriously, this tastes amazing irl)
- etc.

**Comment by MatrexsVigil** [comment]
Thank you for the ideas but I only add new food items/etc via Patreon or Comissions.
