### ISSUE TITLE
Saplings from Pam’s Harvestcraft cannot be used in Ender IO’s farming station

### ISSUE THREAD

**Issue by PapiDimmi** [MatrexsVigil/harvestcraft#266]
I can’t put Pam’s Harvestcraft saplings in [Ender IO](https://minecraft.curseforge.com/projects/ender-io)’s farming station.

I’m not exactly sure what the cause of this bug is, but it _might_ be that Pam’s Harvestcraft’s saplings don’t use the Ore Dictionary.

**Comment by MatrexsVigil** [comment]
I've listed all my saplings as "treeSapling" in 1.11.2h

I hope this fixes it!

**Comment by PapiDimmi** [comment]
@MatrexsVigil Well, I play on version 1.10.2. Do you not backport changes?
