### ISSUE TITLE
Crash on world creating(or loading)/building terrain

### ISSUE THREAD

**Issue by vrork** [MatrexsVigil/harvestcraft#269]
If i disable this mod, it works just fine

https://gist.github.com/vrork/70181dc5dae6ead0b2abb7a61f40aab2

**Comment by vrork** [comment]
latest logs:
Also, disabling the Trees gen fixed it

**Comment by MatrexsVigil** [comment]
Thanks! Fix will be in 1.11.2h

**Comment by vrork** [comment]
Fix the 1.10.2 version too!
