### ISSUE TITLE
Gooseberries aren't trees!

### ISSUE THREAD

**Issue by Pulverizer** [MatrexsVigil/harvestcraft#27]
"- Added: Gooseberry Trees as a temperate tree spawn"

Just so you know, gooseberries are bushes and really ought to grow on farmland. (Actually I thought you already had gooseberry bushes in the mod?) Yet I have seen some stuff online talking about gooseberry trees so I'm not sure.

However here's a good british gooseberry bush: ![Gooseberries!](http://www.love2learnallotmenting.co.uk/wp-content/uploads/2013/06/How-To-Grow-Gooseberries-Hinnonmaki-Yellow.jpg)

**Comment by MatrexsVigil** [comment]
Gooseberry Trees were a donation item.  Many of my fruit trees/crops aren't botanically correct.
