### ISSUE TITLE
[1.12] Traps causing issue with chests

### ISSUE THREAD

**Issue by ghost** [MatrexsVigil/harvestcraft#27]
Hello!

First I'd just like to say that I'm newly returning to Minecraft (haven't played since about 1.7) and I absolutely love this mod! Thank you for all your hard work.

When A Ground or Water trap is placed in the same chunk as a chest. the chest stops rendering properly. The chests are invisible until you open them, then they become visible for a while. I initially thought this was a mod interaction, but have been able to replicate this with HC being the only mod installed. 

Similarily, traps are also causing odd interactions with some other major Mods. As above, these only happen when placed in the same chunk. I only mention this as perhaps it is related to the above issue.
 these are only examples I didn't check everything possible)
          - Bibliocraft: Rotates signs to always face West - Won't render books in a bookshelves until you open the bookshelf.
          - Tinkers Contstruct 2: Smelteries and Forges in the same chunk will not function unless they are newly built. Liquid tanks won't display their contents unless added to / removed from.

I'm currently running Minecraft 1.12 with Forge 14.21.1.2443 and am running version 1.12c

If there's any other information I can provide, please let me know,

Emily B.

**Comment by MatrexsVigil** [comment]
Fixed in 1.12.1b
