### ISSUE TITLE
cross-mod compat request: Butter

### ISSUE THREAD

**Issue by Syndaryl** [MatrexsVigil/harvestcraft#271]
Can you oredict butter and butter-using recipes? 
Grim's Mod has a butter churn which would be great to use with Harvestcraft. He's already added oredict-based compatibility with his blender and knife (juicer and cutting board equivalents) and other food ingredients like cheese.

I know there's a lot of pages of butter-using recipes; I'd be happy to update the *.java file(s) for the change over to the oreDict if you want to off-load the work (I don't think the latest code is up on Git or I'd have submitted this as a pull request).

**Comment by MatrexsVigil** [comment]
My butter is listed as "foodButter", and all my recipes use the oreDictionary term.  Just have him list his butter as "foodButter", and you'll be able to use it in my recipes.

**Comment by Syndaryl** [comment]
Aha, Grim has it listed under listAllButter. https://github.com/grim3212/grim-pack/blob/master/src/main/java/com/grim3212/mc/pack/cuisine/item/CuisineItems.java#L144
I'll go poke him.

**Comment by Syndaryl** [comment]
Poke sent on https://github.com/grim3212/grim-pack/issues/89
