### ISSUE TITLE
[1.12.2] Tree saplings not plantable on BoP grass blocks

### ISSUE THREAD

**Issue by TimGoll** [MatrexsVigil/harvestcraft#272]
Latest forge, latest BoP and latest harvestcraft

**Comment by Draskh** [comment]
Do not use "latest". Post the version you used. If someone will read this later, the version cannot be reconstructed.

**Comment by NielsPilgaard** [comment]
This is still an issue

## Versions
- Pam's HarvestCraft 1.12.2zb
- Forge1.12-2.14.23.5.2781
- BiomesOPlenty-1.12.2-7.0.1.2424-universal

**Comment by Draskh** [comment]
All recommend to implement a check for oredict entries such as "dirt" and "grass".

**Comment by Ricket** [comment]
This appears to be the method that needs fixing:

https://github.com/MatrexsVigil/harvestcraft/blob/2913b289c3cf7486b6abb5bffd0c387cca5cad3e/src/main/java/com/pam/harvestcraft/blocks/growables/BlockPamSapling.java#L110-L112

~And this location should probably be fixed simultaneously, if it is similarly broken (not sure if BoP grass/dirt is a subclass of BlockGrass/BlockDirt or not -- this is ground traps checking for whether they are surrounded by dirt or grass)~

https://github.com/MatrexsVigil/harvestcraft/blob/2913b289c3cf7486b6abb5bffd0c387cca5cad3e/src/main/java/com/pam/harvestcraft/tileentities/TileEntityGroundTrap.java#L130-L132

EDIT: I tested, the ground trap does detect BoP grass as valid grass. So this second thing is not an issue.

**Comment by TimGoll** [comment]
The second check for the GroundTrap is way better because BOP extends the grass and dirt block of minecraft
