### ISSUE TITLE
[1.12] Wrong display name of cooked Minecraft items

### ISSUE THREAD

**Issue by NielsPilgaard** [MatrexsVigil/harvestcraft#28]
Hey!

Minecraft 1.12
Forge 1.12-14.21.1.2443
Pam's Harvestcraft 1.12.1a

As the title says, cooked Vanilla Minecraft items display the wrong name:
![billede](https://user-images.githubusercontent.com/21295394/29538953-42e2855e-86c8-11e7-9656-b1553673833c.png)

Also, I think you may have forgotten to lower the hunger you get from Cooked Fish, and Cooked Salmon.

Sidenote, I'm looking forward to the overhaul of the mod, so far I'm very happy about the changes :)

**Comment by MatrexsVigil** [comment]
Fixed in 1.12.1b
