### ISSUE TITLE
HarvestCraft makes wheat edible

### ISSUE THREAD

**Issue by geolographer** [MatrexsVigil/harvestcraft#284]
MC version 1.12.2
Forge 14.23.2.2611
HarvestCraft 1.12a (and going back to March 2017)

HarvestCraft should be keeping wheat inedible, but every time I've had HC installed, I've been able to eat it. This can for the most part be ignored except when feeding cows or other wheat-eating livestock. There's a Minecraft glitch that causes food to be fully eaten if it starts being eaten, or if another piece of food in the held stack is used. Feeding a large number of cows while even the slightest bit hungry thus leads to my character eating several pieces of wheat, which I'd prefer to keep for the cows or for more efficient prepared meals. I've been countering this by trying to feed myself first, but this is not always practical, especially in early game when wheat is most likely to be a limited resource.

I still experience this issue after uninstalling all mods except Optifine and HarvestCraft. I've had Hunger Overhaul, AppleCore, and AppleSkin installed previously. Uninstalling HarvestCraft makes wheat inedible again.

**Comment by manusoftar** [comment]
The same still happen with HC 1.12.2za, at least i still can breed cows with this verison but they wont follow me when i have wheat in my hand though...

**Comment by manusoftar** [comment]
I've made a fork from this repo and fixed this issue, now you can configure in the settings file if you want the wheat to be edible or not. I've already asked the owners of this repo to pull my modifications.

**Comment by MatrexsVigil** [comment]
This has been fixed in 1.12.2zc
