### ISSUE TITLE
(Update) add new crops (amaranth, hazenut...) to 1.7.10 version

### ISSUE THREAD

**Issue by MrProton657** [MatrexsVigil/harvestcraft#288]
Hi Pam, I really love your mod, but then I heard that there was a big update, I was first happy, but then really disappointed because I´m still playing on 1.7.10 and the new crops was'nt added to 1.7.10. So I was be really grateful to you, if you could do it if you have some free time for it.

MrProton (aka Michael)

**Comment by matheusvingadouro** [comment]
I have a better suggestion: update 1.7.10 features to newer versions lol (like planting rice on water)... and 1.7.10 had less crops, which is good

**Comment by MrProton657** [comment]
if not then not, I've already updated to 1.12.2
