### ISSUE TITLE
1.12.2 Sunflower Seed Issue

### ISSUE THREAD

**Issue by RogueTuna** [MatrexsVigil/harvestcraft#291]
Hi. I noticed an issue with not being able to plant sunflower seeds. And from the looks of it the only other complaint about it was with a 1.10 version. Figured I should let you know that it still persists. Have a good one.

**Comment by MatrexsVigil** [comment]
Sunflower seeds are now only a food, as there is no Sunflower crop anymore since they added the flowers to the base game.  Sorry.
