### ISSUE TITLE
Invalid id 4096 - maximum id range exceeded

### ISSUE THREAD

**Issue by border999** [MatrexsVigil/harvestcraft#293]
[crash-2018-11-11_12.17.57-client.txt](https://github.com/MatrexsVigil/harvestcraft/files/2570048/crash-2018-11-11_12.17.57-client.txt)

**Comment by ToMe25** [comment]
@border999 this isn't a Issue from Pams Harvestcraft.
This Crash just Occurs because this Many Mods adding to many Items.
Try using [JEID](https://minecraft.curseforge.com/projects/jeid) or [NEID](https://minecraft.curseforge.com/projects/notenoughids).
Most likely one of them will fix this :)
