### ISSUE TITLE
Juicer Not Working

### ISSUE THREAD

**Issue by gilbertthefish** [MatrexsVigil/harvestcraft#294]
When I attempt to juice blackberries and raspberries with the juicer, it does not work. This may be a glitch or perhaps the recipe was changed since previous versions. This is for Minecraft version 1.12.2

**Comment by ToMe25** [comment]
Which version of Harvestcraft are you using?
I am using Pam's Harvestcraft+1.12.2za and the Juicer is Working.
Are you Trying to juice 1 ore 2 berries?
1 should not work.

**Comment by MatrexsVigil** [comment]
The new recipe is 2 crops to get juice.
