### ISSUE TITLE
Cake Placeability

### ISSUE THREAD

**Issue by natedogith1** [MatrexsVigil/harvestcraft#30]
At the moment, your cakes don't work well with auto-placers (like Botania's Rannuncarpus). I think this could probably be fixed by using minecraft's ItemReed instead of ItemPamCake, but I don't know if that'd break anything.

**Comment by babyblasphemy** [comment]
This seems to still be broken. Multiple mods placers/auto right clickers can't place cakes or they replace another block with cake. Would be helpful to know what's up with this, if there is a fix in the works or if someone else needs to do something to get it working.

**Comment by Zettt** [comment]
@MatrexsVigil I'm playing FTB Untested or what it's called, and I can't place any of the cakes from HC, by myself. I can only eat them.
