### ISSUE TITLE
Banana Milkeshake (sic) spelling error

### ISSUE THREAD

**Issue by luke-bravenboer** [MatrexsVigil/harvestcraft#300]
Hey, not sure if anyone's pointed this out yet but I haven't seen it reported & it affects the latest version (1.12.2za), so... the Banana Milkshake item is misspelt as '_Milk**e**shake_'!

That's it, just wanted to let ya know in case it hadn't been spotted :)

**Comment by MatrexsVigil** [comment]
Fixed in upcoming 1.12.2zd
