### ISSUE TITLE
Sunflower Seeds can't be planted

### ISSUE THREAD

**Issue by Gyromax** [MatrexsVigil/harvestcraft#301]
Hello,

as mentioned above, Sunflower Seeds can't be planted in tilled Dirt. Doesn't matter if it's the vanilla Dirt or Dirt from Biomes O' Plenty.

I've tried it on my Server with Harvestcraft 1.11.2h
and on my Singleplayer with Harvestcraft 1.11.2i
With other Addons activated and in Singleplayer even without additional Addons.

Every Recipe i know and found on the Wiki and in JEI works without Problems.

**Comment by Syndaryl** [comment]
Apparently this is "as intended" (there was a prior ticket about this issue, Pam closed it)

You can propagate sunflowers by putting a sunflower on grass and bonemealing it - it will create more sunflowers nearby. This is a vanilla feature that i had no idea existed until the question came up here.

**Comment by Gyromax** [comment]
Ok, thanks for ur answer. I'll close this Issue then
