### ISSUE TITLE
[1.12] Broken vanilla items

### ISSUE THREAD

**Issue by TheLimePixel** [MatrexsVigil/harvestcraft#31]
As of the least version, many vanilla items have broken localization and cannot be planted.

**Comment by MatrexsVigil** [comment]
Fixed in 1.12.1b

**Comment by TheLimePixel** [comment]
Actually, it's still there. The localization that is.
![image](https://user-images.githubusercontent.com/25333164/29693725-8e0d2b44-8937-11e7-8eb7-05327523004d.png)
