### ISSUE TITLE
[1.10.2] Crash with CoFHCore plus RTG.

### ISSUE THREAD

**Issue by ElvenChaos** [MatrexsVigil/harvestcraft#310]
When HarvestCraft 1.10.2j is loaded with CoFHCore 1.10.2-4.1.9.13 and RTG 4.1.2.4 (I believe this applies to RTG snapshots too) there is a crash where CoFHCore is being handed a bad value. All three mods must be present to create the crash, and the crash may occur when creating a world, or when trying to walk for 2 seconds in the world.

https://pastebin.com/Y0XPccx1

Issue first reported at the CoFH github here: https://github.com/CoFH/Feedback/issues/340
Issue at RTG: https://github.com/Team-RTG/Realistic-Terrain-Generation/issues/1207

**Comment by srs-bsns** [comment]
This issue has been reproduced without HarvestCraft. This issue can be closed.
