### ISSUE TITLE
Stop this madness

### ISSUE THREAD

**Issue by LordMZTE** [MatrexsVigil/harvestcraft#316]
![grafik](https://user-images.githubusercontent.com/28735087/51201555-a88aba80-18fc-11e9-9336-082bb457b779.png)
tf is dis

**Comment by GreatestFool** [comment]
F3+H should solve that I think.

**Comment by Natesky9** [comment]
You have another mod that is showing ore dictionary entries, *and* the F3 debug option turned on. Not related to harvestcraft

**Comment by LordMZTE** [comment]
> 
> 
> You have another mod that is showing ore dictionary entries, _and_ the F3 debug option turned on. Not related to harvestcraft

the thing im making fun of is that its called "sesame seeds seed" which doesnt make sense not the ore dict names

**Comment by scotty9090** [comment]
Did this really need to be opened as an issue?

**Comment by GreatestFool** [comment]
It didn't. But I'm sure the thought didn't cross his mind.

**Comment by LordMZTE** [comment]
> 
> 
> It didn't. But I'm sure the thought didn't cross his mind.

well ur right

**Comment by MatrexsVigil** [comment]
Okay, this isn't an issue and folks are complaining.  I really need to focus on other things right now.  lol
