### ISSUE TITLE
Mod conflict: Rustic + Harvestcraft + Actually Additions

### ISSUE THREAD

**Issue by mcilhargey** [MatrexsVigil/harvestcraft#317]
string_cropFlax.json from latest ref 094199315e0 conflicts with the [rope recipe from rustic](https://github.com/the-realest-stu/Rustic/blob/347f2a5d66100ff8195598228db7887333ef58e4/src/main/resources/assets/rustic/recipes/rope.json) since string was assigned cropFlax by Actually Additions.

I'm not sure of how to fix this from a mod pack perspective.

**Comment by Draskh** [comment]
You can install this mod to change the recipe output while ingame. 
https://minecraft.curseforge.com/projects/stimmedcow-nomorerecipeconflict

Or you can change the recipe with this mod.
https://minecraft.curseforge.com/projects/crafttweaker?gameCategorySlug=mc-mods&projectID=239197

**Comment by mcilhargey** [comment]
brilliant, ty sir

**Comment by MatrexsVigil** [comment]
I feel like this is closed now.
