### ISSUE TITLE
[1.12] Broken logs

### ISSUE THREAD

**Issue by TheLimePixel** [MatrexsVigil/harvestcraft#32]
In all the 1.12 version so far, the logs (Maple and Paperback wood) have always had broken textures in JEI. In the world their texture is fine, but when they're broken in survival mode, they don't drop anything.

**Comment by MatrexsVigil** [comment]
When they're broken in survival, they do not drop anything just like the other fruit blocks.  And all fruit blocks have broken textures in JEI/Creative Menu for now.
