### ISSUE TITLE
spelling mistake itemID lemonade (spelled: lemonaide)

### ISSUE THREAD

**Issue by tjeulink** [MatrexsVigil/harvestcraft#322]
title basically says it all. fixing it would break my spice of life food categories though 👎

**Comment by luke-bravenboer** [comment]
Not an issue. Pam doesn't change the internal IDs of items when she amends their spellings after they've been implemented, because that would break a lot more than just your spice of life food categories. (There's actually a few items like this!)

**Comment by Draskh** [comment]
Changing the ID name would remove all existing items from the game.
The ID doesn't need to match with the real name of an item. It could also be named harvestcraft:lmnd.
This is not an issue.

**Comment by tjeulink** [comment]
In that case im closing the issue :)
