### ISSUE TITLE
Crop to Seed Recipe + Crop Drop Seeds not working

### ISSUE THREAD

**Issue by xhatz** [MatrexsVigil/harvestcraft#325]
Hello! So basically, as the title says, those two options in the config (cropsdropSeeds and enablecroptoseedRecipe) simply does not work and doesn't do anything :(

I am using HC 1.12.2zb with the very latest forge (2815), thank you!

**Comment by MatrexsVigil** [comment]
The crop to seed config is old code that needs to be removed since recipes are now JSON files so thank you for reminding me.

As for the cropsdropSeeds issue, that is now fixed in the upcoming 1.12.2zd.
