### ISSUE TITLE
Nothing is Craftable? [1.12.2zc]

### ISSUE THREAD

**Issue by Sonno-Eterna** [MatrexsVigil/harvestcraft#328]
Hey! Just got this mod earlier this week and updated it just tonight! Yet, even so, I can't craft anything? I've looked at the recipes and everything - I've tried crafting pots and the other utilities - and nothing. Everything is in there in Creative Mode and I can gather up crops naturally, but I can't craft any of the Harvest Craft items. I can craft other mod items and vanilla items I have, just not Harvest Craft ones. I could just grab food and whatnot from Creative Mode, but what's the fun in that? Anyway, thanks for reading this and have a wonderful day!

**Comment by Sonno-Eterna** [comment]
Added specification: I don't lose hunger either? I can lose health and get it back but I don't lose hunger? It wasn't always like this.

**Comment by Sonno-Eterna** [comment]
Never mind, the hunger thing was me being in Peaceful Mode (I'm a dumb Minecraft baby) and I can eat everything, including the Harvest Craft items, but I still can't craft any of them!

**Comment by Sonno-Eterna** [comment]
Never mind again! I can make food, just not to tools for it like the skillet. It's weird, but it's better than nothing! I can leave this up just in case though.

**Comment by MatrexsVigil** [comment]
Are you trying to use iron ingots?  The new recipes use clay bricks to make it easier to make the tools for early food creation.
