### ISSUE TITLE
[1.12.1] Game Crashed with Multiple Markets

### ISSUE THREAD

**Issue by TheBeeCreator** [MatrexsVigil/harvestcraft#33]
Good afternoon/morning and so on.

My friends and I have a server that is crashing when we have multiple markets, they asked me to file a report :) I can get any other information that is needed

Here is the crash log we had, disabling this mod fixed the issue

[-.txt](https://github.com/MatrexsVigil/harvestcraft/files/1249111/-.txt)

**Comment by MatrexsVigil** [comment]
If you are still experiencing this crash after updating to HarvestCraft 1.12.2L and Forge 2555+, please re-post here: https://github.com/MatrexsVigil/harvestcraft/issues/127
