### ISSUE TITLE
Rotating Presser using wrench (or at least the TE crescent hammer) clears its inventory

### ISSUE THREAD

**Issue by ilyvion** [MatrexsVigil/harvestcraft#333]
I assume this issue is a HarvestCraft issue, since the CH doesn't rotate anything you right click on, only, presumably, supported entities. In any case, when the Presser is rotated, whatever was in it disappears into the void, gone forever.

**Comment by MatrexsVigil** [comment]
Fixed in upcoming 1.12.2zd
