### ISSUE TITLE
[1.12.2zc] havestcraft configure confusion.

### ISSUE THREAD

**Issue by Elmfeather7** [MatrexsVigil/harvestcraft#334]
Hai! 
I've been trying to go into the configure files to stop the fast spawn rate of the garden crops, But all I get when opening the file is a bunch of nonsense, can anyone help? thanks! 
![helps](https://user-images.githubusercontent.com/37834855/57005858-bdc2f500-6c1e-11e9-84ec-30f23cd51b9f.PNG)

**Comment by Draskh** [comment]
You cannot edit the .jar file. You must go to gamelocation/config/harvestcraft.cfg.

**Comment by Elmfeather7** [comment]
Thank you! I didn't even realized that, :D
