### ISSUE TITLE
Black and purple cubes instead of fruit.

### ISSUE THREAD

**Issue by QuarixCZ** [MatrexsVigil/harvestcraft#335]
![qH4EXxZ](https://user-images.githubusercontent.com/50244813/57153616-0b825d80-6dd7-11e9-80d8-7ef27b0e2851.png)

Hello,
found a problem where fruit would turn into something like in the picture. I am playing on 1.8.8

Thanks, Quarix

**Comment by MatrexsVigil** [comment]
I will not be fixing versions before 1.12.2 without extenuating circumstances.
