### ISSUE TITLE
Notice of life issues - Welcome back!

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [MatrexsVigil/harvestcraft#338]
@MatrexsVigil I am just glad you have returned that you are working on getting better - I am so sorry that scum re-entered your life but I am glad you are able to help the people the scum also hurt. Good luck in all your endeavors.

**Comment by MatrexsVigil** [comment]
Thank you!  I'm glad I'm also back, and hopefully I can get some of these bugs fixed in timely manner.  :)
