### ISSUE TITLE
game crashes when crafting seeds

### ISSUE THREAD

**Issue by syi666** [MatrexsVigil/harvestcraft#339]
basically my modpack runs just fine until I craft a seed and the game crashes

https://paste.ee/p/rc3UT

https://paste.ee/p/vQRcZ

Modlist
Aether Legacy
AstralSorcery
Baubles
Bewitchment
BiblioCraft
Biomes O' Plenty
Botania
ChickenChunks
Chisel
CodeChicken Lib
CoFH Core
CoFH World
Cooking for Blockheads
CosmeticArmorReworked
CTM
Decocraft
Ice and Fire
Immersive Engineering 0.12-89
LLibrary
Mantle
Pam's HarvestCraft
Patchouli
PTRLib
Redstone Flux
Reliquary
Thermal Expansion
Thermal Foundation
Tinkers' Contruct
Waystones
Plustic
Tinkers armory
FML 14.23.5.2837

**Comment by MatrexsVigil** [comment]
I cannot replicate this bug issue after crafting every seed and then crafting every seed through the book GUI.  Maybe update Forge or make sure HarvestCraft is updated.
