### ISSUE TITLE
[1.10.2] When trying to buy a nametag from a market, server stacktrace. Asyncronous CME warning.

### ISSUE THREAD

**Issue by ProsperCraft** [MatrexsVigil/harvestcraft#34]
https://gist.github.com/ProsperCraft/d3671779e4c4a217122a75afbf9b3cb7

The player that did it said he crashed the server twice prior to to this buying a nametag.

**Comment by killfalcon** [comment]
I'm running a pack without Sponge, and had no issues buying nametags on the market. Might be an issue with an API call to Sponge?

**Comment by ProsperCraft** [comment]
k, its back in your court.  Stop async spawning which causes CMEs

**Comment by MatrexsVigil** [comment]
Not accepting non 1.12.2 bug reports at this time.
