### ISSUE TITLE
[1.7.10] Problem with Pam's HarvestCraft and Forestry

### ISSUE THREAD

**Issue by demycat** [MatrexsVigil/harvestcraft#343]
Hello, I have a problem with crafting a wax capsule, in fact, Nei shows craft that I can craft a wax capsule (wax from Pam 's HarvestCraft mod), but when I use craft I expose it to the table, I cannot craft them .
How to fix this?

Version Forestry: forestry_1.7.10-4.2.16.64
Version Pam's HarvestCraft: Pam's HarvestCraft 1.7.10Lb
![2019-05-27_14 53 10](https://user-images.githubusercontent.com/34833284/58472569-35693e80-814f-11e9-92cf-033cfcab57f7.png)
![2019-05-27_14 54 21](https://user-images.githubusercontent.com/34833284/58472571-3601d500-814f-11e9-90c6-d016bf04534a.png)

**Comment by MatrexsVigil** [comment]
I will not be fixing versions before 1.12.2 without extenuating circumstances.
