### ISSUE TITLE
Private Server - 1.11.2 - Loaded class BSL on invalid side SERVER

### ISSUE THREAD

**Issue by JonnyBrando** [MatrexsVigil/harvestcraft#35]
MC 1.11.2
Forge 13.20.1.2454
Harvestcraft - 1.11.2i

java.lang.RuntimeException: Attempted to load class bsl for invalid side SERVER

[crash-2017-08-24_19.14.59-server.txt](https://github.com/MatrexsVigil/harvestcraft/files/1250458/crash-2017-08-24_19.14.59-server.txt)

[fml-server-latest.txt](https://github.com/MatrexsVigil/harvestcraft/files/1250459/fml-server-latest.txt)

**Comment by MatrexsVigil** [comment]
Not accepting non 1.12.2 bug reports at this time.
