### ISSUE TITLE
Viewing any recipe in NEI crashes client with Pams Harvestcraft 1.7.10La

### ISSUE THREAD

**Issue by Hund** [MatrexsVigil/harvestcraft#35]
I'm running my own custom modpack with Forge 10.13.4.1585.

Crash log: http://hastebin.com/adifoyebuj.txt

**Comment by Xiaminou** [comment]
can reproduce: http://pastebin.com/NPQgcMFt

**Comment by Dream-Master** [comment]
Me too

https://gist.github.com/Dream-Master/8799925db1df7326ff9a#file-crash:

**Comment by JasonMcRay** [comment]
Disable Harvestcraft integration NEI Integration config file. @Tonius needs to update NEIIntegration mod to reflect the changes. https://github.com/Tonius/NEI-Integration/issues/94

**Comment by Dream-Master** [comment]
Thanks for Info

**Comment by MatrexsVigil** [comment]
Thanks guys.  I've updated the GitHub so hopefully everyone that hooks into HarvestCraft can fix any issues.
