### ISSUE TITLE
Arid Gardens not dropping new crops

### ISSUE THREAD

**Issue by antmusic** [MatrexsVigil/harvestcraft#354]
I am using version 1.12.2zd and none of the new crops that are supposed to drop from arid gardens (agave, chickpeas, etc.) are dropping. I have tried deleting and re-installing the mod and it didn't work. I know the crops are in the game because they exist in creative mode but they won't drop from the gardens when I break them only cactus and cactus fruit. Is there a solution?

**Comment by MrTitainin** [comment]
Try resetting the config (removing it). Worked for me.

**Comment by antmusic** [comment]
Thanks that worked!
