### ISSUE TITLE
1.12.1b - Crops - Vanilla - Harvesting - Beetroot and Wheat - Only produce seeds

### ISSUE THREAD

**Issue by scottpage** [MatrexsVigil/harvestcraft#36]
Harvesting beetroot and wheat only produce seeds, instead of crops and seeds.

Carrots and Potatoes work as expected.

**Comment by Th3Fi5ch** [comment]
As for me, I can not confirm this. At least for wheat I can harvest it with left mouse click and right mouse click and in both cases it produces seeds and crops.  - Have not tested it for beetroot though.

HC 1.12.1b with MC Forge 14.22.0.2462

**Comment by scottpage** [comment]
I'll run it without other mods and see if it's a conflict or another mod causing the issue.

HC 1.12.1b with MC Forge 14.22.0.2446 (maybe Forge version issue)

**Comment by scottpage** [comment]
Resolved by upgrading MC Forge to 14.22.0.2462.
