### ISSUE TITLE
Can craft PHC Cotton out of candleberries

### ISSUE THREAD

**Issue by JasonMcRay** [MatrexsVigil/harvestcraft#36]
Not sure if this is intended but there is a recipe to craft two candleberries into two cotton. Its not gamebreaking issue, but what is the reasoning of this? There is already Cotton plant, so why have another way of getting cotton?

Tested with 1.7.10k and 1.7.10La

**Comment by MatrexsVigil** [comment]
Weird, I'll fix that.

**Comment by Timeslice42** [comment]
While we're on the subject, what's the purpose of the "craft two X to get two X" recipes?

**Comment by MatrexsVigil** [comment]
They're there for Ore Dictionary exchanges.
