### ISSUE TITLE
Anyone found a way to get fruit trees to spawn with biomebundle?

### ISSUE THREAD

**Issue by Trnrr** [MatrexsVigil/harvestcraft#363]
I cant find anyway to get them working. Only thing I could find was this https://github.com/PG85/OpenTerrainGenerator/issues/154 but I'm not sure if that means harvestcraft has to fix it or OTG

**Comment by Ezoteric** [comment]
im using BB and i have them spawning.

**Comment by Trnrr** [comment]
I'm not sure what version you are using but perhaps this was fixed by now. Will close as it seems fixed.
