### ISSUE TITLE
Harvestcraft food won't cook, presser empties without working when used with hopper and more

### ISSUE THREAD

**Issue by Lyrina25** [MatrexsVigil/harvestcraft#37]
I can't cook any of the harvestcraft food with the 1.12 update. The 1.10 update doesn't let you use hoppers to automate the process, and when you use one to load a pressed, the food you want pressed goes into the 'finished' box. Also in the 1.10 update, fish trap bait can't be made.

**Comment by killfalcon** [comment]
Using version 1.9.4-1.10.2g of Harvestcraft:
I've tried the Presser in 1.10.2 with hoppers and EnderIO conduits on different faces and can confirm that the "working" item in the top slot of the presser is extracted  from all faces. If there are items in the input and output slots of the presser, the input is extracted first.

Also, you can insert things like pressed wax or honey directly into the presser (appearing in the output slots if the input is occupied). I think this might be something simple like all the slots being registered as both input and output inventory slots.

I was able to craft fish trap bait, though it gets extracted from the traps in the same way as pressers and doesn't seem to be insertable at all.

**Comment by MatrexsVigil** [comment]
Automation forge capacities are being fixed in 1.12.1c  

The only thing that should be cookable in the furnace in any of the later HC versions is meat.  Everything else needs to be cooked using Bakeware in the crafting grid.
