### ISSUE TITLE
[1.12] [HC 1.12.1b] Vanilla Food no names, reduced hunger points.

### ISSUE THREAD

**Issue by NicMoore88** [MatrexsVigil/harvestcraft#39]
In the 1.12.1a and b releases, Vanilla foods do not have names, instead they are labeled as item.minecraft.food.pork (or something similiar, can't recall the exact order).  Removing Harvestcraft or rolling back to 1.12c fixes this.  
This was tested in both a modpack as well as with only HarvestCraft, Forge, and Minecraft 1.12.

**Comment by MrDj200** [comment]
Same here

**Comment by NicMoore88** [comment]
Reupdating to 1.12.1b fixes the naming issue, but the hunger points still seem off.  Steak for example only restores 2 points of hunger vs the normal 8.  Not sure if this is intended.

**Comment by Th3Fi5ch** [comment]
The reduced hunger points are an intended change see changelog: https://github.com/MatrexsVigil/harvestcraft/blob/master/src/Pam's%20HarvestCraft%201.12%20Changelog.txt#L21. 
I guess this issue is resolved then :-)
