### ISSUE TITLE
Mod randomly broke 1.12.2

### ISSUE THREAD

**Issue by Gremzy** [MatrexsVigil/harvestcraft#395]
I have a personal modpack for my own use, and everything worked fine, but all of a sudden out of no where the mod just broke, I hadn't added mods, Just removed some. So now hunger doesn't work right, and some of harvestcrafts blocks are showing up as other blocks, like windy gardens are showing up as iron blocks and even called them, but when I right click them they turn back into windy gardens. Please help.
![2020-02-05_15 31 47](https://user-images.githubusercontent.com/49301135/73886676-ac52ed00-482f-11ea-8945-da629611b6c1.png)
![2020-02-05_15 31 45](https://user-images.githubusercontent.com/49301135/73886677-ad841a00-482f-11ea-9edf-e944b55d3d0b.png)

**Comment by MarioSMB** [comment]
Removing mods can affect the IDs of blocks, it's likely this has occurred in your world.

**Comment by Gremzy** [comment]
It was Mario thank you!
