### ISSUE TITLE
[1.10.2] Sunflower seeds not plantable/plantable version not craftable

### ISSUE THREAD

**Issue by killfalcon** [MatrexsVigil/harvestcraft#40]
Harvestcraft version: 1.9.4-1.10.2g

Sunflower Seeds (crafted from Vanilla sunflowers)  won't plant in tilled soil (or dirt/grass/sand/gravel, not that I expected sand/gravel to work).  The internet implied they should be crafted into a plantable seed, but a seed alone in a crafting grid does nothing and there's no equivalent item showing in JEI.

Minor bug at worst. I can always cheat in more sunflowers if they become important. ;)

**Comment by MatrexsVigil** [comment]
Not accepting non 1.12.2 bug reports at this time.
