### ISSUE TITLE
1.7.10LB Fresh Water Recipe config

### ISSUE THREAD

**Issue by lunarmaximum** [MatrexsVigil/harvestcraft#407]
I can't find the json files to Pam's harvest craft mod for 1.7.10LB version (last version of 1.7.10). I just want to change the water bucket recipe to produce more fresh water instead of the 1:1 recipe... the config files no longer work for this. 

 

Thanks.

**Comment by Gandalf360one** [comment]
You could change it with crafttweaker/minetweaker
