### ISSUE TITLE
1.12.1b - Recipes not working

### ISSUE THREAD

**Issue by Honkerer** [MatrexsVigil/harvestcraft#42]
The following recipes are not working on 1.12.1b:

Pot
Banana Tree
(haven't tried other tools yet as I reverted back to 1.12c)

**Comment by Th3Fi5ch** [comment]
Hi @Honkerer, the pot and some other tool recipes are broken in the current version. They are configured to need bricks instead of iron ingots. I have a patch for these in #38 . As a workaround you can really just use bricks ;-)

**Comment by MatrexsVigil** [comment]
Tools needing bricks is not broken.  That was an intended change.

How is the banana tree recipe broken?  Are you using 3 bananas and any sapling?

**Comment by Honkerer** [comment]
Banana tree is working again since using the very latest version.
Thanks for the information about bricks, I have been referring to the wiki :)

I'll continue testing and reporting issues.
