### ISSUE TITLE
Sesame seed plant not dropping when planted in Agricraft crop sticks

### ISSUE THREAD

**Issue by TheDarkPreacher** [MatrexsVigil/harvestcraft#42]
So I'm helping test a modpack for Tedyhere (Cthulhu Awakens) and I have a Harvestcraft sesame seed plant set up in some Agricraft cropsticks. When the plant is mature, I right click to harvest the plant, and it goes down to 28% grown and doesn't drop a sesame seed. This is with version 1.7.10La of Harvestcraft and version 1.4.5 of Agricraft. Not sure if this is a Harvestcraft bug or an Agricraft bug, will be reporting to Agricraft's dev as well.

**Comment by GirafiStudios** [comment]
This is caused by AgriCraft since the support for Harvestcraft is on their side, as far as I know.

**Comment by TheDarkPreacher** [comment]
actually, I reported this to InfinityRaider and his response is in the following link

https://github.com/InfinityRaider/AgriCraft/issues/482

**Comment by therealericbj** [comment]
Had the same issue as reported by TheDarkPreacher.

Tested with update file, Pam's HarvestCraft 1.7.10Lb.jar, still had the same issue.

Tested on cropsticks, fertilized dirt, and normal tilled dirt.  Still no sesame seeds dropped.

**Comment by Mochnant** [comment]
@MatrexsVigil: Any chance we could reopen this issue?  InfinityRaider looked into it and says it is Pam's Harvestcraft's registration of the Sesame Seed with the OreDict:

```
You're going to have to bug Pam to correctly register the sesameseeds to the OreDict:
seed: <seedSesameSeeds>
fruit: <cropSesameSeeds> (instead of <cropSesameSeed>)
```
http://forum.feed-the-beast.com/threads/2-3-3-2-3-5-agricraft-sesame-seed-not-dropping-produce.140986/

Thanks!

**Comment by Mochnant** [comment]
I believe the line of code @InfinityRaider is referring to in that forum post and in https://github.com/InfinityRaider/AgriCraft/issues/482 is here:

https://github.com/MatrexsVigil/harvestcraft/blob/master/java/com/pam/harvestcraft/PamFoodOreDictionaryRegistry.java#L469-L471
```
/*  469 */     OreDictionary.registerOre("cropSesameseeds", ItemRegistry.sesameseedsItem);
/*  470 */     OreDictionary.registerOre("seedSesameseed", ItemRegistry.sesameseedsseedItem);
/*  471 */     OreDictionary.registerOre("listAllseed", ItemRegistry.sesameseedsseedItem);
```

**Comment by ddrhousehq** [comment]
Sorry that I sound like a total noob, but how do I change the code like that.  I have been trying to figure out how you guys change the code and can't really find a solid answer.  Can you please help me, I would really appreciate it.
