### ISSUE TITLE
[1.12.1b] Harvesting beetroot/wheat produces seeds, but no crops, with LiteLoader installed

### ISSUE THREAD

**Issue by scottpage** [MatrexsVigil/harvestcraft#44]
Java JRE 1.8.0_121
Minecraft 1.12.1
MC Forge 14.22.0.2446 - 14.22.0.2463
LiteLoader 1.12.1-SNAPSHOT (unknown build number - 1 or 2 - I'll find out)

Results of testing (each repeated 3 times):
- Vanilla MC (no Forge, no LiteLoader, no mods) - Harvesting beetroot/wheat produces crops and seeds.
- Forge and Harvestcraft installed (no LiteLoader, no other mods) - Harvesting beetroot/wheat produces crops and seeds.
- Forge, LiteLoader, and Harvestcraft (only, no other mods) - Harvesting beetroot/wheat produces seeds, but no crops.

After final test, LiteLoader was removed again, and harvesting behaved as expected.

**Comment by MatrexsVigil** [comment]
What is the purpose of using LiteLoader?  I'm confused as why you're using it in the first place.

**Comment by scottpage** [comment]
Until a better real-time map mod for Forge comes out, we're stuck with VoxelMap, which uses LiteLoader.  Actually, I don't know of any 1.12+ Forge compatible real-time map mods.  I'm confused as to why you're not just investigating and then fixing the issue, AND, that you've never heard of LiteLoader.

Wow, I'm really confused by your response.  I want to tell you my background, and why you should care, but it's obvious now, that it won't matter.  I'll just stop using Harvestcraft.  Too complicated anyway.

**Comment by scottpage** [comment]
Leaving Harvestcraft.  Not worth the effort.  I would love to contribute, but I can't unteach incompetence.  Someone let me know when troubleshooting becomes mainstream again.  Until then, I'll just keep testing space shuttle main engines and turbofans, being a Metrologist, programmer, and control system engineer.

It's sad to see one of the top listed mods, and the developer questions the use of a very well known mod  loader.  I'd love to help.  Let me know when that's feasible, and I'll be back.  I'll even remove these comments, and praise you.   Awesome mod, and I admire your effort, but, you need troubleshooting experience.
