### ISSUE TITLE
Balance changes to vanilla food should be configurable

### ISSUE THREAD

**Issue by urikkiru** [MatrexsVigil/harvestcraft#45]
While I enjoy using Harvestcraft, for making a mod pack it would be highly desirable if the changes to all the vanilla food hunger point values were something we could configure(Or disable) Otherwise this creates a scenario where the core Minecraft experience relating to food and hunger is dictated by the usage of Harvestcraft. This would cause it to be excluded from some mod packs.

**Comment by MatrexsVigil** [comment]
Added in 1.12.1c (coming soon)
