### ISSUE TITLE
It becomes same Texture when put any of the 4 sinks

### ISSUE THREAD

**Issue by xpenxpen** [MatrexsVigil/harvestcraft#45]
It becomes same Texture when put any of the 4 sinks.
Forge 1448.
Version: 1.7.10k
(Most probaly 1.7.10La has same issue)

http://media-minecraftforum.cursecdn.com/attachments/thumbnails/159/814/204/115/635821280549200094.png

**Comment by Sheldor5** [comment]
Same here.

**Comment by FreedomChicken** [comment]
This still happens with the latest release for 1.7.10
