### ISSUE TITLE
[1.12.1c] Candlelight bug

### ISSUE THREAD

**Issue by axioanic** [MatrexsVigil/harvestcraft#46]
I was really bummed to find out that the candles don't seem to produce any light so I looked into it.

The problem is line 10 in BlockPamCandle.java:  `setLightLevel(7F);`

> setLightLevel - Controls the light emission of the block. Note: This method takes a value from zero to one, not zero to fifteen. To calculate this value, take the light level you wish your block to emit and divide by 16. For instance a block which emits level 5 light should pass 5 / 16f to this method.
>
> source: http://mcforge.readthedocs.io/en/latest/blocks/blocks/ 

Thanks for the mod btw, its the best.

**Comment by MatrexsVigil** [comment]
Fixed in 1.12.1c (coming soon)
