### ISSUE TITLE
[1.12.1]Vanilla food hunger bar value

### ISSUE THREAD

**Issue by Tetalica** [MatrexsVigil/harvestcraft#47]
In 1.12.1 there is no config to set vanilla food to normal vanilla values. Steak, cooked chicken/pork all only give 1 hunger bar and it's incredibly annoying.

**Comment by MatrexsVigil** [comment]
A config option to turn this off is coming in 1.12.1c (coming soon)

Please be aware that everything else in HarvestCraft will be balanced around these numbers so turning them back to Vanilla amounts will unbalance everything.
