### ISSUE TITLE
Cranberry, Seaweed Seeds not craftable

### ISSUE THREAD

**Issue by fullphaser** [MatrexsVigil/harvestcraft#49]
Now I know I have messed with SOME of Harvestcraft seeds through Minetweaker ala the following

#Remove the Recipies to Make them 
recipes.remove(<Growthcraft|Fishtrap:grc.fishTrap>);
recipes.remove(<harvestcraft:riceseedItem>);
recipes.remove(<harvestcraft:grapeseedItem>);
recipes.remove(<harvestcraft:blueberryseedItem>);
recipes.remove(<harvestcraft:raspberryseedItem>); 
recipes.remove(<harvestcraft:strawberryseedItem>);
recipes.remove(<harvestcraft:blackberryseedItem>);
recipes.remove(<harvestcraft:pamappleSapling>);

But... what's curious here is First the Rice Seed actually doesn't end up getting removed in this case which leads me to believe the seeds that drop from the Water Gardens must have something special going on. I didn't see anything in the config and the following is set to true 

"miscellaneous recipes" {
    B:enablecropitemsasseeds=true
    B:enablecroptoseedRecipe=true
    B:enableharvestcraftfish=true
    B:enablelistAllwaterfreshwater=true
    B:enablelistAllwatervanillawaterbucket=true
    B:enablesaltfromwaterbucketrecipe=true
    B:enabletofuasmeatinRecipes=true
    B:enabletofuasmilkinRecipes=true
    I:fishtrapbaitrecipeamount=4
    I:freshmilkfrombucket=4
    I:freshwaterfrombucket=1
    I:fruitbaitrecipeamount=4
    I:grainbaitrecipeamount=4
    I:marketblockrecipeItem=0
    I:veggiebaitrecipeamount=4
}

In the Harvestcraft config 

full Config / scripts in https://github.com/fullphaser/Tame-The-World

Not sure if it's a config switch I flipped, or something else that I'm missing. i didn't see anything about it in the Harvestcraft Wiki. 

Also worth noting that when trying to plant Seaweed Seeds at least, planting anything next to them seemed to cause them to pop right out.

**Comment by Djent-** [comment]
Right click on water with seaweed and cranberries to plant. Still seems strange they don't let you have their seeds.

**Comment by fin-ger** [comment]
+1 Can confirm this bug in versions `1.7.10j+`. This is not present in version `1.7.10j`. Using this version for now.
