### ISSUE TITLE
[1.12] Compatibility with Natura crops

### ISSUE THREAD

**Issue by llloyd4** [MatrexsVigil/harvestcraft#5]
Could you please add compatibility with Natura's crops?

**Comment by MatrexsVigil** [comment]
In what way am I not compatible?

**Comment by llloyd4** [comment]
Right click harvest and growth ‰ on the hud. Works for wheat and such but
wasn't able to with cotton from Natura.

**Comment by MatrexsVigil** [comment]
Oh, this is something I can't do on my end.
