### ISSUE TITLE
[1.12.1c] Invalid registration attempt for an Ore Dictionary item

### ISSUE THREAD

**Issue by ghost** [MatrexsVigil/harvestcraft#52]
I am receiving a lot of "Invalid registration attempt for an Ore Dictionary item with name" errors, as seen in this paste: http://paste.ubuntu.com/25565715/ and I am not sure what to do about it. Is this detrimental to my server?

Thank you for such an amazing mod! :)

**Comment by UnPure** [comment]
I have the same errors in my log (https://pastebin.com/J44mcrce).
This is probably because of the changes about vanilla food items.

**Comment by MatrexsVigil** [comment]
I have no idea how to fix this. =(

**Comment by MatrexsVigil** [comment]
Fixed in 1.12.2e!
