### ISSUE TITLE
[1.12.1c] "Parsing error loading built-in advancement minecraft:recipes/food/*"

### ISSUE THREAD

**Issue by Ksehn** [MatrexsVigil/harvestcraft#54]
Hi @MatrexsVigil ,

When using the latest version of HarvestCraft (1.12.1c), I've got a few errors on server load. Ingame, everything seem to works, but when someone click on the recipe book inside the inventory GUI, the game crash. 

( Same issue? #50 )

## Errors

https://pastebin.com/raw/QCPAkWFf (from latest.log)
https://pastebin.com/raw/frKJDBtC (from fml-junk-earlystartup.log)

## Infos
**HarvestCraft:** 1.12.1c
**Forge:** 14.22.1.2485
**Java:** 1.8.0_144
**Others mods:** None.

**Comment by UnPure** [comment]
I can confirm this. My server is producing the same errors on startup.
This is probably related to the changes of vanilla food recipes while Minecraft is trying to load these recipes from its built in json files.

This problem seems to be for:

    minecraft:pumpkin_pie
    minecraft:mushroom_stew
    minecraft:cookie
    minecraft:bread
    minecraft:beetroot_soup

**Comment by digi-tal-it** [comment]
Same here:
These are the errors on startup, after loading the world
https://pastebin.com/f3eKbkhc

MC: 1.12.2
HC:  1.12.1c
Forge: 14.23.0.2509

**Comment by runescapejon** [comment]
Having the same issue i am on
HarvestCraft - 1.12a

**Comment by MatrexsVigil** [comment]
This happens because enableVanillaFoodBalance config is true, replacing the default Minecraft items with my own versions. I can't fix this error spam in the console (to my knowledge).

**Comment by dooferorg** [comment]
This STILL happens even when setting B:enablevanillafoodBalance=false in the config file.

**Comment by Prasodym** [comment]
B:enablevanillafoodBalance=false

I've done so, but these messages come.
