### ISSUE TITLE
[1.12.1] Parsing error loading recipe

### ISSUE THREAD

**Issue by UnPure** [MatrexsVigil/harvestcraft#56]
While starting a server/client, HarvestCraft is producing a few errors.
This i probably related to (but still not the same): https://github.com/MatrexsVigil/harvestcraft/issues/54

Part of the log: https://pastebin.com/dQqgSDWC

**HarvestCraft:** 1.12.1c
**Forge:** 14.22.0.2475

**Comment by MatrexsVigil** [comment]
This happens because enableVanillaFoodBalance config is true, replacing the default Minecraft items with my own versions.  I can't fix this error spam in the console (to my knowledge).
