### ISSUE TITLE
Red Velvet recipe

### ISSUE THREAD

**Issue by ReverseStateMonad** [MatrexsVigil/harvestcraft#58]
The recipe for Red Velvet Cake is incorrect; Red Velvet is a type of chocolate cake, it should include Cocoa Powder as an ingredient (old fashioned cocoa powder turned red when baked, when dutch cocoa was invented bakers who were upset about their chocolate cakes coming out brown instead of red started dyeing them red, resulting in the invention of the red velvet cake).

**Comment by MatrexsVigil** [comment]
Fixed in 1.12.2d
