### ISSUE TITLE
[1.10.2] Exception loading model for variant harvestcraft:

### ISSUE THREAD

**Issue by ErikSteiner** [MatrexsVigil/harvestcraft#6]
With just Harvestcraft (Pam's HarvestCraft 1.10.2j) active, I get several errors in the log-file. I hope that it can be fixed in the future. I don't know what they mean, so I hope I can help you by providing the log file.

`Exception loading model for variant harvestcraft:crops/cranberrycrop_stage3#inventory, normal location exception`

There are more errors down below.

Feel free to ask for more information if needed.
[Harvestcraft-logfile.txt](https://github.com/MatrexsVigil/harvestcraft/files/1184902/Harvestcraft-logfile.txt)

**Comment by MatrexsVigil** [comment]
Not accepting non 1.12.2 bug reports at this time.
