### ISSUE TITLE
[Request] Better GUI for the Market

### ISSUE THREAD

**Issue by xenoflot** [MatrexsVigil/harvestcraft#61]
As time and enthusiasm permits, it'd be nice to have a better GUI for the market. It's quite tedious to have to click through one at a time. Page by page listing of 10 at a time would be nice. At the very least, please sort them alphabetically!

Cheers!

**Comment by MarikCZ** [comment]
yeah really needed and annoying!

**Comment by MatrexsVigil** [comment]
This is a planned feature once I am better at GUIs.

**Comment by MarikCZ** [comment]
Maybe you can ask for code Tinkers Contruct developer. There was same problem in stencil table in older versions.
