### ISSUE TITLE
[1.12.2a] right clicking wheat or beetroot results in getting seeds only

### ISSUE THREAD

**Issue by Zedrimar** [MatrexsVigil/harvestcraft#63]
This intended or no? because if I right click fully grown wheat, no matter what I get just seeds. If I break, I get usual drops.

**Comment by PeakXing** [comment]
mee to 
mc ver 1.12.2
forge&liteloader ver  1.12.2-LiteLoader1.12.2-1.12.2-forge1.12.2-14.23.0.2503

mod ver 1.12.2a

**Comment by tabbykitty1** [comment]
I have not had this problem. All plants within this mod and Vanilla drop crop and possible seeds when right-clicked on.

Minecraft: 1.12.2
Forge: 14.23.0.2491
HarvestCraft: 1.12.2a

**Comment by Zedrimar** [comment]
@tabbykitty1 Guess it was a forge bug that got fixed. I was testing in an older version before the update

**Comment by Zedrimar** [comment]
@tabbykitty1 actually it is liteloader. Reported the issue to Mumfrey.

**Comment by tabbykitty1** [comment]
Fair enough. I don't have LiteLoader installed since I reformatted my computer. It was something my brother installed for me when I first started playing with Forge and mods, but never put it back in as I never used it.

**Comment by darthvader45** [comment]
@Zedrimar You did?  I don't see the issue at all on Liteloader's github.  Link?

**Comment by Zedrimar** [comment]
I thought I closed this myself? it was a forge interaction thing with liteloader, it was fixed a long time ago which is why I closed it eventually

**Comment by Zedrimar** [comment]
You may wanna take a look at my comments here, @darthvader45 :P

**Comment by darthvader45** [comment]
Nvm, config thing.  Fixed.  Btw, wheat should drop on right-click regardless of the balancing option being true or false.  I don't see how making them only drop seeds is balanced, as breaking them is just about the same thing, except infinitesimally slower.
