### ISSUE TITLE
Enviromine rotten food still edible from lunch bag

### ISSUE THREAD

**Issue by Haggle1996** [MatrexsVigil/harvestcraft#63]
See Haggle1996/RevolutionPack#207 for full details. 

@Funwayguy, I assume this is an issue HarvestCraft would address?

**Comment by Toksyuryel** [comment]
Wrong mod, the lunch bag and lunch box are from Spice of Life

**Comment by Haggle1996** [comment]
Eep. My apologies, @MatrexsVigil
