### ISSUE TITLE
Multiple Shipping Bin Transactions Cause Crash on LAN Game

### ISSUE THREAD

**Issue by jason-booth** [MatrexsVigil/harvestcraft#66]
When using the shipping bin in a LAN game, Minecraft crashes when attempting two transactions in a row in the Shipping Bin.

The shipping bin works as expected when the game is not open to the LAN.

The first transaction in the shipping bin goes fine. If a second is attempted the game crashes. The transaction seems to complete. When the game is restarted an emerald can be picked up and the inventory is gone.

If you do one transaction, exit the shipping bin, look into a different item like a chest, presser, or market block, and then go back into the shipping bin, you can perform another transaction without a crash.

crash report: https://pastebin.com/XQTzQjJa

**Comment by Teslachu** [comment]
I can confirm this happens. If you leave the GUI for the shipping bin after doing one transaction of 32 (like 32 onion for 1 emerald) and DON'T look into another GUI (like open the market, open a chest, open the presser)... and then you click on the shipping bin, it will crash.

I am not sure if I worded that in a way that makes sense.

Steps to also make it crash
* Open GuiI to Shipping Bin
* Sell 32 of one item
* Close Gui to Shipping Bin
* Re-open Gui to shipping bin (without opening anything else after the last time you accessed it)
* Watch the game crash

As "jason-booth" said above, the following also makes it crash:

* Open Gui to Shipping Bin
* Sell 32 of one item
* Sell 32 of one item
* Watch the game crash

These are instances where the game is open to lan or is on a server.

**Comment by angelnc1989** [comment]
The same happens on my server when I'm trading multiple stacks of items for emeralds.
The game crashes for me the exact moment I click the button, but I can't tell how many stacks I have to trade for it to occur.

**Comment by Teslachu** [comment]
@angelnc1989 About a stack, in my testing. A full stack tends to crash it. Anything more than a stack for sure crashes it. Trading half a stack and then checking the inventory of a chest and then going back in to trade another half stack works... But it is tedious... Cause you gotta rinse and repeat. Trade 32, look at the inventory of a chest, trade another 32, look at the inventory of a chest... So on and so forth. It sucks. It has gotten to the point I don't even have them (Market & Shipping Bin) down, until I go to use them. Once I am fine, I pick them back up. I've already crashed the server by buying a birch sapling from the market. I hardly use those items now. I did enough of the tedious work to get a decent amount emeralds and now I just have those items in a chest.

**Comment by angelnc1989** [comment]
It's definitly more than a stack. I was able to trade at least half an inventory of items before it crashed.

**Comment by Teslachu** [comment]
@angelnc1989 well I know this one time I was able to trade several stacks without any problems, without the sever crashing...but then again I was the only person online. I have not tested that since that day. Later on I encountered the bug, while others were online. I simply decided to not mess with it much further.

**Comment by angelnc1989** [comment]
I am the only one playing on the server (sad, I know) so I use the Shipping Bin as a I need it and just wait for the server to restart after the crash. It actually always lets me trade in several stacks before it crashed. I just traded a whole inventory in and no crash. It's very inconsistent.

**Comment by ghost** [comment]
Can you try with the latest 1.12.2 Harvest Craft file? And update to 1.12.2. All mods in 1.12 or 1.12.1 in theory should work with 1.12.2.

**Comment by Teslachu** [comment]
Well I can't test it on that server, because it is no longer on All The Mods: Expert Remastered. However I am currently on a server that is on a 1.12 pack, that does have harvest craft... And already did some testing, it would appear the issue is not present in 1.12 like it was in that 1.10 pack. To be fair, it is also possible that the mod pack for ATM was not on the latest harvest craft mod, for 1.10.

**Comment by angelnc1989** [comment]
I'm always on the latest version. Haven't tested with the one that came out today, but before that the crash happened very frequently.

**Comment by MatrexsVigil** [comment]
If you are still experiencing this crash after updating to HarvestCraft 1.12.2L and Forge 2555+, please re-post here: https://github.com/MatrexsVigil/harvestcraft/issues/127
