### ISSUE TITLE
Infinite yoghurt

### ISSUE THREAD

**Issue by ghost** [MatrexsVigil/harvestcraft#67]
I'm playing [All the Mods 3](https://minecraft.curseforge.com/projects/all-the-mods-3), and I’ve found the following recipe.

![infinite yoghurt minecraft cropped](https://user-images.githubusercontent.com/25916106/32303805-419753f6-bf6b-11e7-865a-7bd9debe966d.png)

Doesn’t this recipe allow you to have a virtually infinite amount of yoghurt by simply having a cow, a bucket, and one yoghurt to begin with?

I am not sure if this recipe is added by another mod or Pam’s HarvestCraft, but I can’t find anything yoghurt-related or Pam’s HarvestCraft-related in the CraftTweaker scripts.

ATM 3 version: 4.4
Minecraft version: 1.12.2
Pam’s HarvestCraft version: 1.12.2a

**Comment by richardhendricks** [comment]
I believe that's intended.  The yoghurt is a base that is mixed in with other fruits and whatnot.

**Comment by ghost** [comment]
@richardhendricks It’s still infinite food, as the plain yogurt itself can be eaten. A bit silly, if you ask me.

**Comment by richardhendricks** [comment]
It';s not infinite, any more than a carrot is infinite.  It takes a bucket, a cow, and waiting around for the cow's milk timer to expire.

And with Pam's balancing of the foods, higher tier foods will be better, so I don't think this is an issue.

**Comment by ghost** [comment]
What milk timer? As opposed to a carrot (or any other crop), you don’t have to wait for anything. Just right-click the cow, craft the yoghurt, and repeat.

**Comment by richardhendricks** [comment]
LOL, I am used to modded, there the cows have a couple-minute timer on them between milkings.

Yeah, not sure on what a proper resolution on this would be.  Maybe require a consumable item of some kind, or degrade a tool.

**Comment by ghost** [comment]
They don’t for me. I can keep milking them.

Maybe it’s a mod that adds a timer.

**Comment by MatrexsVigil** [comment]
1.12.2d - Removed Plain Yogurt + listAllmilk = Plain Yogurt x2 recipe,  added Plain Yogurt + Leather = Plain Yogurt x4 recipe (change count in Plain Yogurt x4 recipe JSON)
