### ISSUE TITLE
[1.12.2] Recipe Conflict

### ISSUE THREAD

**Issue by NielsPilgaard** [MatrexsVigil/harvestcraft#68]
Hey!

Peking Duck and Stuffed Duck have the same recipes:

![billede](https://user-images.githubusercontent.com/21295394/32538776-88fe9316-c467-11e7-8848-0299f4ea4b21.png)
![billede](https://user-images.githubusercontent.com/21295394/32538782-8cbb0c28-c467-11e7-9508-75ef2d5f6617.png)

**Comment by MatrexsVigil** [comment]
Fixed in 1.12.2

**Comment by NielsPilgaard** [comment]
Thank you
