### ISSUE TITLE
1.12b - Missing Recipes 

### ISSUE THREAD

**Issue by 4AM-Campfire** [MatrexsVigil/harvestcraft#7]
This is a list of all the items that do not have a crafting recipe in JEI. I've tested a random sample of them and all have failed using the old recipes, but it could just be bad luck. Testing them is slow going.

In addition, there are a number of recipes that are inconsistent. Some of the juice recipes are hand crafted (2 Fruit + Juicer), while others are crafted via the presser; some even have both and Carrot has neither. Not sure if that's design intent or not. I've noted them anyway.

There are also a couple of items that don't have names and are listed item.[FOOD]item.name, also noted.

Ground Trap
Apiary
Honey Block
Honeycomb Block
+++All Candle Colours+++

Carrot Cake
Cheese
Cherry
Chocolate Sprinkle
Holiday
Lamington
Cheese
Ice Cream
Grilled Cheese
Apple Sauce
Carmel Apple
Apple Pie
Cup of Coffee
Flour
Dough

Heavy Cream
Butter
Apple Juice - Press
Melon Juice - Craft
Carrot Juice - None
Strawberry Juice - Both
Grape Juice - Press
Blueberry Juice - Press
Cherry Juice - Press
Papaya Juice - Both
Starfuirt Juice - Both
Orange Juice	 - Both
Peach Juice - Both
Lime Juice - Press
Mango Juice - Craft
Pomegranate Juice - Both
Blackberry Juice - Press
Raspberry Juice - Craft
Kiwi Juice - Press
Cranberry Juice - Press
Cactus Fruit Juice - Press
Plumb Juice - Both
Pair Juice - Both
Apricot Juice - Press
Fig Juice - Press
Grapefruit Juice - Press
Persimmon Juice - Both

Carrot Soup
Glazed Carrots
Buttered Potato
Fries
Grilled Mushroom
Chicken Sandwich
Chicken Noodle Soup
Chicken Pot Pie
Breaded Pork Chop
Hotdog
Baked Ham
Hamburger
Cheese Burger
Beacon Cheese Burger
Fish Sandwich
Fish Sticks
Fish and Chips
Fried Egg
Boild Egg
Egg Salad
Caramel

Cocoa Powder
Chocolate Bar
Hot Chocolate
Chocolate Ice Cream
Fruit Salad
Ketchup
Chicken Parmesan
Fish Lettuce Wrap
BLT
Leafy Chicken Sandwich
Deluex Cheese Burger
Delighted Meal
Hash
Braised Onions
Hearty Breakfast
Corn on the Cop
Cornmeal
Cornbread
Fish Taco
Creamed Corn
Chocolate Strawberry
Grape Jelly
Grape Salad
Cucumber Salad
Cucumber Soup
Fried Rice
Curry Rice
Baked Beans

Beans and Rice
Chili
Bean Barrito
Grilled Skewer
Hot Wings
Chilli Poppers
Extreme Chilli
Chilli Chocolate
Lemonaid
Lemon Bar
Fish Dinner
Lemon Smoothie
Lemon Meringue - listed as "item.lemonmeringueitem.name”
Candied Lemon
Lemon Chicken
Blueberry Smoothie
Blueberry Pie
Blueberry Muffin
Blueberry Pancakes
Cherry Pie
Chocolate Cherry
Cherry Smoothie
Eggplant Parm
Chai Tea
Espresso
Coffee Con Lache
Beet Salad
Beet Soup
Baked Beets
Brocoli Mac
Brocoli n Dip
Creamed Brocoli Soup
Candied Sweet Potatos
Baked Turnips
Ginger Bread
Ginger Snaps
Candied Ginger
Garlic Bread
Garlic Mashed Potatoes

Garlic Chicken
Celery and Peanut Butter
Chicken Celery Casserole
Celery Soup
Asparagus Quiche
Asparagus Soup
Candied Walnuts
Brownie
Guacamole
Cream of Avocado Soup
Avacado Burrito
Fruit Crumble
Banana Split
Banana Nut Bread
Banana Smoothie
Banana Yogurt
Chocolate Milk
Chicken Curry
Coconut Shrimp
Coconut Yogurt
Keylime Pie
Lime Smoothie
Lime Yogurt
Cinnamon Roll
French Toast
Doughnut
Chocolate Doughnut
Jelly Doughnut
Frosted Doughnut
Cactus Soup

Jellybeans
Biscuit
Cream Cake
Jaffa
Fried Chicken
Footlong
Blueberry Yogurt
Lemon Yogurt
Cherry Yogurt
Grape Yogurt
Chocolate Yogurt
Blackberry Cobble
Blackberry Smoothie
Blackberry Yogurt
Chocolate Milk
Cinnamon Sugar Doughnut
Kiwi Smoothie
Kiwi Yogurt
Apple Yogurt
Cranberry Sauce
Cranberry Bar
Black Pepper
Ground Cinnamon
Ground Nutmeg
Baklava
Gummy Bears
Bacon Mushroom Burger
Fruit Punch
Egg Nog
Custard
Garden Soup
Apple Jelly
Apple Jelly Sandwich
Blackberry Jelly
Blackberry Jelly Sandwich
Blueberry Jelly
Blueberry Jelly Sandwich
Cherry Jelly
Cherry Jelly Sandwich
Cranberry Jelly
Cranberry Jelly Sandwich

Kiwi Jelly
Kiwi Jelly Sandwich
Lemon Jelly
Lemon Jelly Sandwich
Lime Jelly
Lime Jelly Sandwich
Cherry Soda
Cherry Soda
Cola Soda
Ginger Ale
Grape Soda
Lemon-Lime Soda
Caramel Ice Cream
Ginger Chicken
Gingered Rhubarb Tart
Lamb Barley Soup
Honey Lemon Lamb
Beef Jerky
Leek Bacon soup
Herb Butter Parsnip
Bamboo Steamed Rice
Cashew Chicken
Apricot Yogurt
Apricot Glazed Ham
Apricot Jelly
Apricot Jelly Sandwich

Apricot Smoothie
Fig Bar
Fig Jelly
Fig Jelly Sandwich
Fig Smoothie
Fig Yogurt
Grapefruit Jelly
Grapefruit Jelly Sandwich
Grapefruit Smoothie
Grapefruit Yogurt
Grapefruit Soda
Citrus Salad
Bacon Wrapped Dates
Date Nut Bread
Cinnamon Apple Oat Meal
Chocolate Caramel Fudge
Lavender Shortbread
Beef Wellington
Epic Bacon
Chicken Gumbo
General Tso’s Chicken
California Roll
Futo Maki
Beans on Toast
Honeycomb Chocolate Bar
Cherry Coconut Chocolate Bar
Fairy Bread
Chiko Roll
Damper
Beet Burger
Gherkin
Ceasar Salad
Chaos Cookie
Chocolate Bacon
Lamb Kebab

Cooked Clam
Cooked Crab
Cooked Creyfish
Cooked Frog Legs
CookedOctopus
Cooked Scallop
Cooked Shrimp
Cooked Snail
Cooked Turtle
Apple Cider
Bangers and Mash
Battered Sausage
Batter
Chorizo
Coleslaw
Energy Drink
Fried Onions
Cooked Turkey

Cooked Veneson
Chocolate Milkshake
Banana Milkshake
Cornflakes
Coleslaw Burger
BBQ Pulled Pork
Lamb with Mint Sauce
Cherry Ice Cream
Pistachio Ice Cream
Neapolitan Ice Cream
Spumoni Ice Cream
Almond Butter
Cashew Butter
Chestnut Butter
Cornish Pasty
Cottage Pie
Croissant
Curry Powder
Dim Sum
Fried Pecan Okra
Gooseberry Jelly
Gooseberry Sandwich
Gooseberry Milkshake
Gooseberry Pie
Gooseberry Smoothie
Gooseberry Yogurt
Ham & Sweet Pickle Sandwich
Hushpuppies
Kimchi
Apple Smoothie
Coconut Smoothie
Cranberry Smoothie
Cranberry Yogurt

Honey Sandwich
Cheese on Toast
Chocolate Roll
Jam Roll
Coconut Cream
Cracker
Garam Masala
Deluex Chicken Curry
Gravy
Hot and Sour Soup
Chicken Chow Mein
Kung Pao Chicken
Hoisin Sauce
Five Spice
Char Siu
Bacon and Eggs
Biscuits and Gravy
Apple Fritter
Creeper Cookie
Honey Bread
Honeybun
Honey Glazed Carrots
Honey Glazed Ham
Honey Soy Ribs
Anchovy Pepperoni Pizza
Choco Voxels Cereal
Cinnamon Toast
Corned Beef Hash
Corned Beef
Cotton Candy
Crackers
Creeper Wings
Dhal
Durian Milkshake
Durian Muffin
Homestyle Lunch
Hot Sauce
Hummus
Iron Brew
Lasagna
Lemon Drizzle Cake - listed as "item.lemondrizzlecakeitem.name”

Cooked Mussel
Cooked Tofake
Cooked Tofacon
Cooked Tofish
Cooked Tofegg
Cooked Tofutton
Cooked Toficken
Cooked Tofabbit
Cooked Tofurkey
Cooked Tofenison
Fish Trap Bait
Cutting Board
Bakeware
Juicer
Hardened Leather
Hardened Leather Helm
Hardened Leather Chest
Hardened Leather Leggings
Hardened Leather Boots

**Comment by MokahTGS** [comment]
This seems like the jsons are missing from the latest update.  In the last two changelogs a lot of this was supposed to be fixed.  This is a lot of recipes missing.

**Comment by trilexcom** [comment]
hi Pam Thanks for the update again i really appreciate it the above recipes are not working either for us i tried Pam with my modpack and without Still the same result Forge 2426  Pam 1.12b

**Comment by ghost** [comment]
I decided to take a look at the code. I was able to fix the apiary recipe but not the presser. 

I gave up on that and switched to crafttweaker. The process is taking ages. This should NOT be flagged as released on curseforge. It is NOT a functional mod if half of its recipes are uncraftable. 

I'll upload the script file when it's done for anyone who cares.

**Comment by trilexcom** [comment]
hi PsionicArchon Dont be mean to the mod maker, they dont make any money of their mods they do this for us for free, you should appericate what mod makers do for us. Even if they do make money you should still be nice to them. 

Pam is doing her best as always we will test for her and report any issues to her.

Stay Positive My friend

Mat (TrilexCom)

**Comment by MokahTGS** [comment]
Agreed.   Please do not be rude to mod makers.   Many of the recipes do work and if you have cooking for blockheads installed it makes things that much easier.   Understand that the jump to 1.12 was a huge change to how recipes work and ALL of the mod makers had to deal with this change.   Be patient,  be kind and try to help.

**Comment by 4AM-Campfire** [comment]
No need for the sickly 'be nice' stuff, it's a bug report not a group hug.

Right now the mod is non-fuctioning. The amount of work require to fix it, or the difficulty of the work, doesn't matter. Flagging it as a release is a mistake, as the update is clearly a work in progress. It's a factual statement, it's neither rude or kind.

And Cooking for Blockheads won't fix anything, it can't craft recipes that don't exists/work.


Also, to correct the above, money is made by this mod. You can see a public amount on Patreon, and additional money probably comes from Curse or donations. It doesn't change anything, but there is money involved in modding.

**Comment by trilexcom** [comment]
4am-Campfire are you saying because your paying to Pam your own Pam? if you are human and care about people you won't talk that way, if you have a bug just report dont be rude! 

and if Pam can do this full time, with getting money from people in Patreon format or any other its none of your business, 

i would love to see all modder, be comfortable when they are modding dont you ?

and by the way its a group hug! i give free hugs to everyone that is kind and not rude!

Mat

**Comment by Rahmiel** [comment]
@trilexcom I really hate this way of thinking, we are in a system right now where mod developers are making tons of money for their content, and yet release completely broken code and then disappear for weeks without fixing it. The idea that it takes time to fix the mod for the new version is correct, however I want to point out that other, more complex mods are updated and working a whole lot better. If you want I can list them. What makes matters even worse is that Pam herself is not fixing the code here, the people submitting commits are, and yet she is getting all the rewards for it. It is not fair, it leads to a poor system, and it in the end everyone, except Pam in this case, looses.

Pam if you read this, there was a time where you claimed to be a "river to (your) people" I'd like to see that river flow. This mod is great, and I've always been a fan of you and your work, but right now I'm having trouble maintaining that belief in you, if you don't have the time to code and fix a mod with the popularity yours have, you shouldn't be modding at all.

**Comment by ghost** [comment]
I'm not sure how I was being 'mean'. I simply stated that Pam's Harvestcraft should have been flagged as alpha.

Those flags exist for a reason. It allows us modpack makers to select mods that have been deemed stable by their creators. I'm always willing to test alpha releases and drop appropriate bug reports when necessary, but I'd still like to know what I'm getting into beforehand. 

I had to scrap my Immersive Engineering/Spice of life/Tough as nails hardcore pack as it relied heavily upon the wealth of food in Pam's. 

We (myself and my friends) gave up on the crafttweaker script. We spent too much time combing through the code and were too tired by the time we got to crafttweaker. 

Beyond all of this, I was willing to continue digging through the code as I believe we have isolated at least half of the problem. Something I am actually doing for free. You can look me up on Patreon, you wont find one. 

If I'm feeling spunky I'll give it another go but I'm not promising anything. Best of luck.

**Comment by Jiinxycat** [comment]
I just wanted my favorite mod to be functional. I honestly would rather this mod be playable than completely unplayable.  I would rather code your mod, and do the work I am being paid for, than work for half that money at my terrible minimum wage job. If you make $730 to release a finished product, just pull this mod until it is done, or just say it is alpha or something. I would have like to have been warned my favorite mod was going to not work before I wasted time trying to figure out what recipes work and which ones do not. There is so much that needs fixing, but I don't have time nor am I getting paid to produce this mod. Please at least put a warning. ˚‧º·(^˚ ˃̣̣̥⌓˂̣̣̥^ )‧º·˚

**Comment by trilexcom** [comment]
i am not going to make a issue of this, i said what i had to say, that's how i feel about what you said. whatever!

**Comment by Jiinxycat** [comment]
@trilexcom Don't be too salty. That is what comments are for, you will not always agree, but just try to understand where the other person is coming from. I am just looking at it from a professional stand point. Just some communication would have been nice.

**Comment by trilexcom** [comment]
awww thanks lol

**Comment by latenightbuddha** [comment]
Hopefully the recipes will be fixed soon, I just wish the mod author would update us on an ETA and/or a progress report about this version of the mod.

**Comment by MatrexsVigil** [comment]
There were warnings all of this mod that the recipes were broken.  In fact I've been keeping people up to date on Patreon and Twitter about recipes being fixed.  Having over 900 recipes is making this process difficult.

I am working on this issue as I can.  Thank you for reporting what recipes aren't working.

Also, this git and the issues section are for reporting issues.  If you have a problem with me as a person, me getting money, me being a shitty coder that needs help, or anything of that sort, please take it to the r/feedthebeast, one of my personal media accounts, or send me an e-mail.

**Comment by MatrexsVigil** [comment]
As of 1.12c (uploaded to CurseForge and this git right now) fixes the following issues:
Recipes being broken
Carrots not being able to be squeezed for juice and bait
Lemon Drizzle Cake and Lemon Meringue not having names

The following issues from this thread aren't fixed, but I'm closing this anyway:
That I'm a shitty coder
That people help me with issues
That 190+ people think I'm cool enough to donate to
That everyone will make toast sandwiches and beef wellington to power their bases, ignoring 898+ other recipes in the mod anyway

**Comment by trilexcom** [comment]
I love You Pam thanks for the update again

**Comment by MokahTGS** [comment]
Heh... I install spice of life to make people eat other things
