### ISSUE TITLE
Tree fruit remains on leaf decay

### ISSUE THREAD

**Issue by speakerrob** [MatrexsVigil/harvestcraft#71]
Not sure if this is a Pam's Harvestcraft issue, but when using the Fast Leaf Decay mod the tree fruits remain suspended in the air.

I found this open issue on Fast Leaf Decay git, but the link posted in response leads to a 404 Harvestcraft git page.

https://github.com/Olafski/FastLeafDecay/issues/9

MC and Mod versions:
Forge1.12.2-14.23.0.2532
MC 1.12.2
Pam's Harvestcraft 1.12.2a
Fast Leaf Decay v14

**Comment by ofseaandstars** [comment]
Also having this issue. When the tree is chopped down, fruit remains floating in the air.

**Comment by tabbykitty1** [comment]
I too have the same problem of the fruit remaining floating in the air.

**Comment by MatrexsVigil** [comment]
Fixed in 1.12.2e
