### ISSUE TITLE
Gardens don't drop anything(1.8.9c)

### ISSUE THREAD

**Issue by Febilian** [MatrexsVigil/harvestcraft#72]
Got the latest version, tried to punch a garden in single player survival, it dropped nothing. Tried right clicking - it did nothing. The console log has an error pop up whenever I try to harvest a garden:

https://paste.ee/p/tYkfZ

This happens with the latest Forge version with nothing but HarvestCraft installed.

On a side note, the gardens use the "stone" block breaking sound, whereas I believe a plant or leaf based sound would be more appropriate.

**Comment by MatrexsVigil** [comment]
Thank you.  I'll look into this right now.

**Comment by PokeMaserJ** [comment]
I want to add to this. It seems like it is just the HarvestCraft crops that aren't dropping anything. I got Wheat, Carrot, and Potato to drop from a "windy garden". So maybe only Vanilla crops are dropping from the gardens?
