### ISSUE TITLE
[1.12.2a] Raisin recipe does not support other mods' grapes

### ISSUE THREAD

**Issue by aetherknight** [MatrexsVigil/harvestcraft#72]
HarvestCraft's raisin recipe only supports harvestcraft grapes, instead of using `cropGrape`. This seems like an oversight to me because other grape-based recipes added by HarvestCraft, such as grape juice and grape yogurt, use `cropGrape` instead.

Would it be possible to improve this recipe?

Thanks!

**Comment by ghost** [comment]
You can change this with MineTweaker I believe until it gets released if you need it badly.

Or Craft Tweaker

**Comment by MatrexsVigil** [comment]
Fixed in 1.12.2 along with all the other previous smelting recipes
