### ISSUE TITLE
OP fresh milk

### ISSUE THREAD

**Issue by ghost** [MatrexsVigil/harvestcraft#73]
Personally, I think that four fresh milk for just one milk bucket is a bit too good. I think it should be a 1:1 recipe.

**Comment by SephirothWS** [comment]
@PapiDimmi The default setting is OP, I agree with that. However, you can configure how many Fresh Milk you get per milk bucket in the config:
Under Miscellaneous Recipes: I:freshmilkfrombucket=4

**Comment by ghost** [comment]
I didn’t know that, but still, I think the default should be one.

**Comment by st753m** [comment]
I like it being 4.  Clicking on a cow with a bucket 16 times then moving all of those buckets up to the crafting grid to make a stack of fresh milk is already kind of tedious; I wouldn't want to have to do it 4 times as much.  Either way it's infinite milk from 1 cow anyway.

**Comment by tabbykitty1** [comment]
It does not change in the Config file for 1.12.2a, that was changed to a json file edit... which I don't know how to access.

**Comment by ghost** [comment]
@st753m I guess you have a point.

About that, I wish cows had some sort of timer so you’d have to wait before milking a cow again.

**Comment by MatrexsVigil** [comment]
Go into the JAR file under recipes and fine "freshmilkitem" JSON file.  Change the count from 4 to 1.
