### ISSUE TITLE
1.12.2 Vanilla recipe keep/change option?

### ISSUE THREAD

**Issue by Wissi** [MatrexsVigil/harvestcraft#74]
Hi, thanks for all the hard work, we love your mod. We have a bit of an issue with the vanilla recipes being overwritten. Our mod requires vanilla recipes for bread.

Can there be an option to enable/disable the vanilla recipes in the config, please.
Or is there an option/setting we missed that i couldn't find?
Thanks.

**Comment by MatrexsVigil** [comment]
Yes, set enablevanillafoodBalance to false.

**Comment by FinalKill9175** [comment]
Does not work, when you set it to false.

**Comment by DamienBrittan** [comment]
Well , i set it to false , and there's no recipe for bread at all .-.
