### ISSUE TITLE
All items have missing textures(1.8.9d)

### ISSUE THREAD

**Issue by Febilian** [MatrexsVigil/harvestcraft#75]
https://i.gyazo.com/609479f3d75291214e1dda49b78b810d.png
https://i.gyazo.com/f0213b5bb4298f3e91059cee22c4949b.png
https://i.gyazo.com/2b26d57885b337e8cb97f0a3fe70c2a2.png

I'm not entirely sure what's going on here, to be honest. The item textures worked in the previous version, 1.8.9c; and in this version, the blocks are fine, it's just the items as far as I can tell.

Happens with both recommended and latest Forge for 1.8.9. Tested with nothing but Harvestcraft and Forge to the same effect.

EDIT: I notice MultiMC is registering the mod version as 1.8.9a still, despite the file I downloaded being called 1.8.9d. Just a side note.

**Comment by MastaC729** [comment]
I can confirm this as well. I'm using Forge 11.15.1.1855, and the mcmod file seems to suggest the version is on 1.8.9a (however I doubt it is).

**Comment by LandauTST** [comment]
Same here. Also noticed MultiMC reading it as 1.8.9a, and it's also listed as such in the MCMod.info within the jar file. Maybe the link downloads the wrong file?

**Comment by Geethebluesky** [comment]
So I renamed all the JSON files on my end so they match the capitalization used in the code, for example: vegetablesoupitem.json --> vegetablesoupItem.json (capital "I") and that was enough to fix the issue.
Could someone else confirm, and if so: maybe this configuration change can help keep the filename case intact? 
http://stackoverflow.com/questions/17683458/how-do-i-commit-case-sensitive-only-filename-changes-in-git
