### ISSUE TITLE
Plum harvesting drops 2 items (1 not edible) 

### ISSUE THREAD

**Issue by Krhymez** [MatrexsVigil/harvestcraft#75]
When harvesting plums, 2 items drop sometimes. One of the items seems to be an under-grown fruit. Not sure if other fruits also do this.

**Comment by ghost** [comment]
This is better is better worded in #92 . Thanks for reporting tho!

**Comment by MatrexsVigil** [comment]
This is a Hunger Overhaul bug, not HarvestCraft.
