### ISSUE TITLE
Carrot cake The One Probe issue

### ISSUE THREAD

**Issue by ghost** [MatrexsVigil/harvestcraft#76]
The icon and name is the vanilla cake.

![pam s harvestcraft cake](https://user-images.githubusercontent.com/25916106/33185189-34b896be-d081-11e7-9975-86ae264dc6af.png)

****

**Minecraft version**: 1.12.2
**Forge version**: 14.23.0.2552
**Pam’s Harvestcraft version**: 1.12.2a

**Comment by ghost** [comment]
Is the issue that it shows a Cake instead of the carrot cake? Maybe upload this to The One Probe mod authors since this is their issue

**Comment by josephcsible** [comment]
If you pick block a Pam cake, it picks the vanilla cake. That's the cause of this bug; it has nothing to do with TOP.
