### ISSUE TITLE
[1.12.2a] Garden Harvestibility

### ISSUE THREAD

**Issue by SephirothWS** [MatrexsVigil/harvestcraft#77]
Gardens are no longer instant-break when punched. They have the same block harvesting speed as dirt blocks do when punching them with an open hand. Doesn't appear to have an applicable tool to harvest them either.

Minecraft 1.12.2 with Forge 14.23.0.2552
Harvestcraft v. 1.12.2a

Not sure if this was an intended change or not.

**Comment by MarikCZ** [comment]
Yep, very anoying.

**Comment by MarikCZ** [comment]
When using mod ore excavator and harvesting gardens (in natural form, not crops) it breaks all gardens, but to inventory comes only 1 - pls fix that.

**Comment by ReverseStateMonad** [comment]
In my experience, shovels are the applicable tool for digging up gardens.

**Comment by MatrexsVigil** [comment]
Fixed in 1.12.2d
