### ISSUE TITLE
agricraft

### ISSUE THREAD

**Issue by shrael** [MatrexsVigil/harvestcraft#78]
I was wondering will there be agricraft compatibility for the crop sticks and seed analyzer? For 1.8.9

**Comment by Cobra1117** [comment]
Confirmed:

Seeds from Pam's Harvestcraft are no longer plantable on crop sticks.

Tested with:
Agricraft: 2.0.0a3
Harvestcraft: 1.8.9d

**Comment by Cobra1117** [comment]
Cross-posted to Agricraft Github: https://github.com/InfinityRaider/AgriCraft/issues/624
