### ISSUE TITLE
[1.8.9] Ore Dictionnary "listAllseed" missing

### ISSUE THREAD

**Issue by Xiaminou** [MatrexsVigil/harvestcraft#79]
some of the seeds are missing the Ore Dictionnary "listAllseed".
![2016-04-11_20 09 01](https://cloud.githubusercontent.com/assets/8670392/14437476/a7a9774c-0021-11e6-8150-e44781afe941.png)

**Comment by Syndaryl** [comment]
Do you mind if I ask what plugin you're using to see that? I've been looking for a replacement for 1.8.9...

**Comment by Xiaminou** [comment]
no plugin, just F3 + H, it's not as customizable as NEI Integration did but it does the job.

**Comment by Veirilli** [comment]
For the Record the following seeds are missing that categorization:
Artichoke, Cabbage, Okra, Rice and Rutabaga seeds.

**Comment by Geethebluesky** [comment]
Grr, still getting the hang of cherry-picking commits. Sorry for the mess above.
