### ISSUE TITLE
[1.10.2] Juices don’t give you speed

### ISSUE THREAD

**Issue by ghost** [MatrexsVigil/harvestcraft#79]
Their tooltips say that they give you speed, but you don’t get it when you drink it.

**Modpack**: [The Simple Life 2](https://minecraft.curseforge.com/projects/the-simple-life-2-hqm)
**Pam’s Harvestcraft version**: 1.10.2j

**Comment by MatrexsVigil** [comment]
Not accepting bug reports for versions before 1.12.2 at this time.
