### ISSUE TITLE
oredictionary

### ISSUE THREAD

**Issue by TimGoll** [MatrexsVigil/harvestcraft#82]
Can you please change the oredictionary registration to an earlier point in the init routine? Because you are registering it after the minetweaker scripts get run. So I'm unable to change oredictionary stuff.

**Comment by ghost** [comment]
Are you having any issues that are fixed with MineTweaker that you could tell us about tho?

**Comment by TimGoll** [comment]
I changed many recipes, including stuff with salt

**Comment by MatrexsVigil** [comment]
1.12.2d - Moved the Ore Dictionary Registry to preInit.  I hope that helps.
