### ISSUE TITLE
[1.12.2] [Request] Adding blacklist and whitelist for spawn areas of trees wih fruits and nuts to the config

### ISSUE THREAD

**Issue by Draskh** [MatrexsVigil/harvestcraft#83]
If BOP is installed many fruti trees spawn in the Highland biom. But I want to keep this as a mountain and not an orchard biom. Is there a way to blacklist the highland biome?

**Comment by ghost** [comment]
No, it would be in the config file and there was nothing on it in the Tree Section. Would be useful Config option to add tho.

**Comment by Draskh** [comment]
A blacklist or whitelist would be very useful in this mod to getting along with other mods.

**Comment by fllo** [comment]
Hi @MatrexsVigil 
just wanted to let you know, that I am rewriting the whole fruittree configuration part.
I will probably push the changes to github and create a pull request next weekend.
