### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Trixz2018** [MatrexsVigil/harvestcraft#84]
added Embers into my private pack and got this https://pastebin.com/jys0Uuh6, any info on how to stop it from crashing would help thanks.

**Comment by F43nd1r** [comment]
That has nothing to do with this mod in particular, you just have too many mods.
Further reading:

http://www.minecraftforge.net/forum/topic/21681-maximum-id-range-exceeded/

http://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/wip-mods/2467198-notenoughids-maximum-id-range-exceeded-no-more

**Comment by Trixz2018** [comment]
i see. well thanks for the info, didnt know that was a thing, havent played minecraft since 1.7
