### ISSUE TITLE
Salt Not Craftable?

### ISSUE THREAD

**Issue by Siyaa0** [MatrexsVigil/harvestcraft#86]
It looks like Bubbly Water and Salt share the same recipe, making salt uncraftable.

I am playing Sky Factory 3 at its current version; I'm not certain what version of HarvestCraft this modpack uses.

EDIT: SF3 v.3.0.15

**Comment by MelanX** [comment]
maybe you should add version of Sky Factory 3 - other SF3 verison, other Harvestcraft version

**Comment by tabbykitty1** [comment]
Maybe an earlier version of HarvestCraft?

In 1.12.2a it uses 1 pot 2 fresh water for bubbly water, and 1 pot 1 fresh water for salt.

**Comment by Siyaa0** [comment]
Hmm, it must be because 1:1 was giving me the bubbly water. Good to know that it's fixed in a later version though! I'll have to look into whether it's possible to update/change the version of a mod in SF3 or maybe just let them know that they need to use a later version. Thanks!

**Comment by MelanX** [comment]
I tried this version, you're right, in this version of Harvestcraft, there is the same recipe for two things.
If you want, you can just update Harvestcraft to version 1.10.2j, there is everything fine :)
