### ISSUE TITLE
[1.8.9d] Cannot harvest crops with Thaumcraft golems

### ISSUE THREAD

**Issue by Geethebluesky** [MatrexsVigil/harvestcraft#87]
When broken by the golems (or broken with a tool, since golems use tool mechanics to interact with blocks), crops drop themselves instead of the produce. (#77 has been opened about that but I don't know if this isn't wanted behavior for some reason.)

If it is, maybe adding a config option to toggle whether tool usage returns produce instead of crop items would be a good solution?

**Comment by ZaneQLD** [comment]
This is the same issue with Ender IO's farming station
