### ISSUE TITLE
[1.12.2] Forestry Integration

### ISSUE THREAD

**Issue by Draskh** [MatrexsVigil/harvestcraft#87]
Could you add integration for forestry or is it not intended? I think it would be great if Pam's bees works along with Forestry. Or is there already a addon that supports that?

**Comment by ghost** [comment]
Forestry is doing its project to add compability in this github issue: https://github.com/ForestryMC/ForestryMC/issues/223
Try suggesting here for help.

**Comment by Draskh** [comment]
I asked here again: https://github.com/ForestryMC/ForestryMC/issues/1471
