### ISSUE TITLE
[1.9a] NoSuchMethodError for net.minecraft.item.ItemMonsterPlacer.func_185078_a

### ISSUE THREAD

**Issue by RealGrep** [MatrexsVigil/harvestcraft#88]
Things working fine until I add the new release (1.9a, and thanks for that, BTW, I eagerly awaited it). The server then fails to start. The log:

http://pastebin.com/4XHQjMNx

Relevant part of the log/stack trace:

[18:18:02] [Server thread/ERROR] [FML/]: Caught exception from harvestcraft
java.lang.NoSuchMethodError: net.minecraft.item.ItemMonsterPlacer.func_185078_a(Lnet/minecraft/item/ItemStack;Ljava/lang/String;)V
	at com.pam.harvestcraft.gui.MarketItems.registerItems(MarketItems.java:312) ~[MarketItems.class:?]
	at com.pam.harvestcraft.HarvestCraft.preInit(HarvestCraft.java:56) ~[HarvestCraft.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]

Full stack trace obviously in the log above.

This is with MC 1.9, HarvestCraft 1.9a, and tested with both Forge 1887 and 1891.

Thanks, and let me know if I can provide other information or help in any way.

**Comment by Zkaface** [comment]
Yup, got the very same error! Thx for updating to 1.9. When things run smoothly, I will gonna love it again!

**Comment by gl0x** [comment]
same  here. ssp works seemingly.

**Comment by EnderT5** [comment]
same crash (in server only)

http://pastebin.com/hcbV7wbL

**Comment by lebertran** [comment]
Yep. The method ItemMonsterPlacer.applyEntityIdToItemStack is client-only. On a server, the method cannot be found. My fork should have fixed it, but I am not sure if the spawn eggs still work, please check so I can create a pull request.

**Comment by Zkaface** [comment]
@lebertran aus frischem Fischöl,

your fix seems to work properly. I am not sure, what should be wrong with spawn eggs. regards

**Comment by apex2top** [comment]
Your fix is working! Tested with forge-1.9-12.16.1.1892-universal.jar

**Comment by gl0x** [comment]
@lebertran your fix works but textures are incredibly broken.

**Comment by Renadarain** [comment]
@gl0x I found that using the forked version on the server and the released version by Pam on the client works fine and all graphics show up :)

HTH

**Comment by lebertran** [comment]
@gl0x I think I may have fixed your textures problem. For some reason, the texture names were messed up.
@Zkaface :) In the market, you should have spawn eggs for cows, pigs, etc. I am not sure if I messed that up on servers.
