### ISSUE TITLE
[1.12.2a] Fruit Trees dropping fruit oddly

### ISSUE THREAD

**Issue by yepidoodles** [MatrexsVigil/harvestcraft#92]
Hello,

I recently started building a new 1.12.2 test modpack, and found some strange behavior with fruit trees. When you right click to harvest the fruit, it drops one of the fruit (as it's supposed to), but it also drops 1-4 of the same fruit, but the tile entity version (ex. `harvestcraft:pampecan`, `harvestcraft:pamapple`).

Versions:
Pam's Harvestcraft: 1.12.2a ([EDIT] and 1.12.2b)
Forge: 14.23.1.2562

I believe issue #75 is the same thing, but the report is poor and lacking information.

Happy to provide any further information on request.

Alice Sellars
DragonTechMC

**Comment by TimGoll** [comment]
Can confirm this
the crop dropping is the "item" which is rendered in the tree

also all pams items are bugged (rendering-wise)
try holding a tree-spling in your hand

**Comment by Insane96** [comment]
Still an issue in 1.12.2c

**Comment by MatrexsVigil** [comment]
Added the drawScreen method to my machines in 1.12.2d, hope that helps.  Also, automation fixes will be coming when I can figure out capabilities.  Closing this thread because of the drawScreen being added.

**Comment by MatrexsVigil** [comment]
This is a Hunger Overhaul bug, not HarvestCraft.
