### ISSUE TITLE
Server Crash if two people using market/shipping bin at the same time

### ISSUE THREAD

**Issue by Akitori** [MatrexsVigil/harvestcraft#93]
Yeah my server randomly crashed when two different people started using the market at the same time.

Also a bug, spawn eggs don't give actual mobs, they're empty.

**Comment by ghost** [comment]
Can you give a crash report please?

**Comment by Akitori** [comment]
[crash-2017-12-16_20.39.02-server.txt](https://github.com/MatrexsVigil/harvestcraft/files/1577753/crash-2017-12-16_20.39.02-server.txt)

this is the one i believe.

**Comment by MarikCZ** [comment]
It crashes me too but no where more players use it, but everytime when use fast (or more than 2-3 times). Crashlog I cant provide, my PC is in servis. Erlier on 3 Jan.

**Comment by MarikCZ** [comment]
Its really annoying to click trought all trades - can you make some choose gui?

**Comment by MatrexsVigil** [comment]
If you are still experiencing this crash after updating to HarvestCraft 1.12.2L and Forge 2555+, please re-post here: https://github.com/MatrexsVigil/harvestcraft/issues/127
