### ISSUE TITLE
Shifting while breaking Forest Garden or other plants

### ISSUE THREAD

**Issue by ghost** [MatrexsVigil/harvestcraft#94]
While holding shift, or crouching if its bound differently, will break the plant and give it to you instead of the crop. Not sure if this is a bug but cant find anywhere where this is a feature listed so figure I would say something here.

**Comment by ghost** [comment]
Maybe a feature? Shift is commonly used to revert the uses of stuff, especially in mods. (Example: Optifine Shaders options can be long can be gone backwards by holding shift)

**Comment by TimGoll** [comment]
yep it is a feature :)

**Comment by MatrexsVigil** [comment]
This is correct, it's a feature.
