### ISSUE TITLE
"Flying" bee hives and fruits

### ISSUE THREAD

**Issue by LemADEC** [MatrexsVigil/harvestcraft#95]
As of 1.12a, when a forest catch fire, the bee hives and hanging fruits remains floating in the air while the tree leaves are completely gone.
I would suggest fruits to break/disappear when the attached leave disappear, and bee hives to be 'burnable' material.

**Comment by ghost** [comment]
Can you try with [1.12.2b?](https://minecraft.curseforge.com/projects/pams-harvestcraft/files/2513077)

**Comment by LemADEC** [comment]
Same issue.

**Comment by 1-rick** [comment]
Presumably same issue (with 1.12.2a; will try again with .2b and update if it works ok).  In my case I chopped down an apple tree; the three green apples on it stayed floating.  They will even grow and can be harvested repeatedly.  I can provide a screenshot if desired.

**Comment by MatrexsVigil** [comment]
Fixed in 1.12.2d!

**Comment by MatrexsVigil** [comment]
Fixed in 1.12.2e
