### ISSUE TITLE
(1.9)Client crash upon world loading in

### ISSUE THREAD

**Issue by LimeTheOn** [MatrexsVigil/harvestcraft#96]
Its not clear for me what to do with this, I can test it with server too if you want but so far nothing helped other then removing harvestcraft but I REALLY WANT it in my modpack :D is there a newer version that got this sorted? <3

I'll try downgrading forge and disable/enabling mods in hope that works.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  CodeChickenCorePlugin (CodeChickenCore-1.9-2.0.1.53-universal.jar)
  FldLoadingPlugin (FastLeafDecay-1.9-1.6.jar)
  LoadingPlugin (HardcoreDarkness-MC1.9-1.8.jar)
  Reborn Core ASM (RebornCore-1.9-2.1.0.53-universal.jar)
  CCCDeobfPlugin (unknown)
  BetterMinecraftChat (BetterMinecraftChat-mc1.9-1.0.8.jar)
  LoadingPlugin (Bloodmoon-MC1.9-1.4.1.jar)
  CCLCorePlugin (CodeChickenLib-1.9-2.0.1.23-universal.jar)
Contact their authors BEFORE contacting forge

// Oops.

Time: 10/05/16 20:32
Description: Exception in server tick loop

java.lang.NoSuchMethodError: net.minecraft.world.storage.loot.LootEntryItem.<init>(Lnet/minecraft/item/Item;II[Lnet/minecraft/world/storage/loot/functions/LootFunction;[Lnet/minecraft/world/storage/loot/conditions/LootCondition;)V
	at com.pam.harvestcraft.item.LootHelper.createLootEntryItem(LootHelper.java:69)
	at com.pam.harvestcraft.item.LootHelper.createLootEntryItem(LootHelper.java:65)
	at com.pam.harvestcraft.item.LootHelper.<clinit>(LootHelper.java:21)
	at com.pam.harvestcraft.handlers.LootHandler.init(LootHandler.java:27)
	at com.pam.harvestcraft.handlers.WorldLoadEventHandler.onWorldLoad(WorldLoadEventHandler.java:23)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_151_WorldLoadEventHandler_onWorldLoad_Load.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:95)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:119)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 605426816 bytes (577 MB) / 1799462912 bytes (1716 MB) up to 6355222528 bytes (6060 MB)
	JVM Flags: 26 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6144m -Xms256m -XX:PermSize=256m -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+UseNUMA -XX:+CMSParallelRemarkEnabled -XX:MaxTenuringThreshold=15 -XX:MaxGCPauseMillis=30 -XX:GCPauseIntervalMillis=150 -XX:+UseAdaptiveGCBoundary -XX:-UseGCOverheadLimit -XX:+UseBiasedLocking -XX:SurvivorRatio=8 -XX:TargetSurvivorRatio=90 -XX:MaxTenuringThreshold=15 -XX:+UseFastAccessorMethods -XX:+UseCompressedOops -XX:+OptimizeStringConcat -XX:+AggressiveOpts -XX:ReservedCodeCacheSize=2048m -XX:+UseCodeCacheFlushing -XX:SoftRefLRUPolicyMSPerMB=20000 -XX:ParallelGCThreads=10
	IntCache: cache: 0, tcache: 1, allocated: 0, tallocated: 0
	FML: MCP 9.23 Powered by Forge 12.16.1.1898 59 mods loaded, 59 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.9-12.16.1.1898.jar) 
	UCHIJAA	Forge{12.16.1.1898} [Minecraft Forge] (forge-1.9-12.16.1.1898.jar) 
	UCHIJAA	CodeChickenCore{2.0.1.53} [CodeChicken Core] (minecraft.jar) 
	UCHIJAA	cei{1.1.1} [Chunk Edge Indicator] (1.9-chunkedgeindicator-1.1.1.jar) 
	UCHIJAA	armoroverlay{3.1} [Armor Overlay] (Armor Overlay 3.1.jar) 
	UCHIJAA	ArmorDamageRecalc{1.1} [Armor Damage Recalc] (Armor Recalc 1.1.jar) 
	UCHIJAA	armorplus{1.10.1-1.9} [ArmorPlus] (ArmorPlus1.10.1(1.9).jar) 
	UCHIJAA	autopackager{1.6.1} [AutoPackager] (autopackager-1.6.1.jar) 
	UCHIJAA	backlytra{1.9-0.0.1} [Backlytra] (backlytra-1.9-0.0.1.jar) 
	UCHIJAA	bdlib{1.11.0.14} [BD Lib] (bdlib-1.11.0.14-mc1.9.jar) 
	UCHIJAA	BetterAchievements{0.2.5.19} [Better Achievements] (BetterAchievements-1.9-0.2.5.19.jar) 
	UCHIJAA	BetterMinecraftChat{1.0.8} [BetterMinecraftChat] (BetterMinecraftChat-mc1.9-1.0.8.jar) 
	UCHIJAA	BiomesOPlenty{4.0.2.2018} [Biomes O' Plenty] (BiomesOPlenty-1.9-4.0.2.2018-universal.jar) 
	UCHIJAA	JEI{3.3.3.199} [Just Enough Items] (jei_1.9-3.3.3.199.jar) 
	UCHIJAA	BloodMagic{1.9-2.0.0-36} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.9-2.0.0-36.jar) 
	UCHIJAA	Bloodmoon{1.2} [Bloodmoon] (Bloodmoon-MC1.9-1.4.1.jar) 
	UCHIJAA	bookshelf{1.2.0.226} [Bookshelf] (Bookshelf-1.9-1.2.0.237.jar) 
	UCHIJAA	ChickenChunks{2.0.1.26} [ChickenChunks] (ChickenChunks-1.9-2.0.1.26-universal.jar) 
	UCHIJAA	chisel{@VERSION@} [Chisel] (Chisel-MC1.9-0.0.4.13.jar) 
	UCHIJAA	claybucket{1.0} [Clay Bucket] (ClayBucket-1.9-1.0.jar) 
	UCHIJAA	clayworldgen{1.1.0} [Clay WorldGen] (ClayWorldGen-1.1.0-1.9.jar) 
	UCHIJAA	compactstorage{v2.0.0a} [CompactStorage] (compactstorage-2.1-1.9-rc.jar) 
	UCHIJAA	crackedzombiemod{3.4.0} [CrackedZombie Mod] (crackedzombiemod-1.9-3.4.0-67.jar) 
	UCHIJAA	craftelytra{1.0} [Craftable Elytra] (CraftableElytra-1.0.jar) 
	UCHIJAA	CraftableEndPortal{1.2.0} [CraftableEndPortal] (CraftableEndPortal[1.9]version2.jar) 
	UCHIJAA	MineTweaker3{3.0.7} [MineTweaker 3] (CraftTweaker-Customized-1.9-3.0.7.jar) 
	UCHIJAA	eplus{4.1.0.86} [Enchanting Plus] (EnchantingPlus-1.9-4.1.0.97.jar) 
	UCHIJAA	endercompass{1.2.3} [Ender Compass] (EnderCompass-1.9-1.2.3.jar) 
	UCHIJAA	fastleafdecay{1.6} [Fast Leaf Decay] (FastLeafDecay-1.9-1.6.jar) 
	UCHIJAA	samsfooddetails{1.0.1} [Food Details] (FoodDetails-1.9-1.0.1.jar) 
	UCHIJAA	foxlib{@VERSION@} [FoxLib] (FoxLib-1.9-0.9.0.jar) 
	UCHIJAA	graves{1.9-b10-universal} [Graves Mod] (graves-1.9-b10-universal.jar) 
	UCHIJAA	HardcoreDarkness{1.8} [Hardcore Darkness] (HardcoreDarkness-MC1.9-1.8.jar) 
	UCHIJAA	hopperducts{1.4.7} [Hopper Ducts] (hopperducts-mc1.9-1.4.7.jar) 
	UCHIJAA	HardcoreQuesting{5.0.0alpha1} [Hardcore Questing Mode] (HQM-New Heights-5.0.0alpha1.jar) 
	UCHIJAA	InfernalMobs{1.6.9} [Infernal Mobs] (InfernalMobs-1.9.jar) 
	UCHIJAA	inventorysorter{0.7.14+32} [Simple Inventory sorting] (inventorysorter-1.9-0.7.14+32.jar) 
	UCHIJAA	IronChest{6.0.133.777} [Iron Chest] (ironchest-1.9-6.0.133.777.jar) 
	UCHIJAA	journeymap{1.9-5.2.0b1} [JourneyMap] (journeymap-1.9-5.2.0b1-unlimited.jar) 
	UCHIJAA	lonelybiome{1.0} [Lonely Biome] (lonelybiome-1.9-1.0.jar) 
	UCHIJAA	mantle{1.9-0.9.4.jenkins114} [Mantle] (Mantle-1.9-0.9.4.jar) 
	UCHIJAA	testdummy{1.10} [MmmMmmMmmMmm] (MmmMmmMmmMmm-1.10.jar) 
	UCHIJAA	moreoverlays{1.3.1} [MoreOverlays] (moreoverlays-1.3.1-mc1.9.jar) 
	UCHIJAA	Morpheus{1.9-3.0.2} [Morpheus] (Morpheus-1.9-3.0.2.jar) 
	UCHIJAA	harvestcraft{1.9a} [Pam's HarvestCraft] (Pam's HarvestCraft 1.9a.jar) 
	UCHIJAA	pressure{1.3.1.13} [Pressure Pipes] (pressure-1.3.1.13-mc1.9.jar) 
	UCHIJAA	progressiveautomation{1.6.42} [Progressive Automation] (ProgressiveAutomation-1.9-1.6.42.jar) 
	UCHIJAA	Psi{beta-31} [Psi] (Psi-beta-31.jar) 
	UCHIJAA	realtimeclock{1.9-0.6.1} [Real Time Clock] (RealTimeClock-1.9-0.6.1.jar) 
	UCHIJAA	reborncore{2.1.0.53} [RebornCore] (RebornCore-1.9-2.1.0.53-universal.jar) 
	UCHIJAA	xreliquary{1.9-1.3.1.342} [Reliquary] (Reliquary-1.9-1.3.1.342.jar) 
	UCHIJAA	Roguelike{1.5.0} [Roguelike Dungeons] (RoguelikeDungeons-1.9-1.5.0.jar) 
	UCHIJAA	SimpleDimensions{1.3} [Simple Dimensions] (SimpleDimensions-MC1.9-1.3.jar) 
	UCHIJAA	Tails{1.9-1.6.1} [Tails] (Tails-1.9-1.6.1.jar) 
	UCHIJAA	tconstruct{1.9-2.2.2.jenkins156} [Tinkers' Construct] (TConstruct-1.9-2.2.2.jar) 
	UCHIJAA	techreborn{1.0.6.197} [TechReborn] (TechReborn-1.9-1.0.6.197-universal.jar) 
	UCHIJAA	territorychevsky{b14} [Territorial Dealings] (TerritorialDealings_1.9_b14.jar) 
	UCHIJAA	vending{1.3.1} [vending] (vending-1.9-1.3.4.jar) 
	Loaded coremods (and transformers): 
CodeChickenCorePlugin (CodeChickenCore-1.9-2.0.1.53-universal.jar)
  codechicken.core.asm.TweakTransformer
  codechicken.core.asm.DelegatedTransformer
  codechicken.core.asm.DefaultImplementationTransformer
FldLoadingPlugin (FastLeafDecay-1.9-1.6.jar)
  com.olafski.fastleafdecay.FldTransformer
LoadingPlugin (HardcoreDarkness-MC1.9-1.8.jar)
  lumien.hardcoredarkness.asm.ClassTransformer
Reborn Core ASM (RebornCore-1.9-2.1.0.53-universal.jar)
  reborncore.asm.RebornClassTransformer
CCCDeobfPlugin (unknown)
  
BetterMinecraftChat (BetterMinecraftChat-mc1.9-1.0.8.jar)
  net.blay09.mods.bmc.coremod.ClassTransformer
LoadingPlugin (Bloodmoon-MC1.9-1.4.1.jar)
  lumien.bloodmoon.asm.ClassTransformer
CCLCorePlugin (CodeChickenLib-1.9-2.0.1.23-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)

	List of loaded APIs: 
		* BetterAchievements|API (0.2.5.19) from BetterAchievements-1.9-0.2.5.19.jar
		* BloodMagic|API (@VERSION@) from BloodMagic-1.9-2.0.0-36.jar
		* ChiselAPI (0.0.1) from Chisel-MC1.9-0.0.4.13.jar
		* ChiselAPI|Carving (0.0.1) from Chisel-MC1.9-0.0.4.13.jar
		* CoFHAPI (1.8.9R1.2.0B1) from RebornCore-1.9-2.1.0.53-universal.jar
		* CoFHAPI|block (1.8.9R1.2.0B1) from ProgressiveAutomation-1.9-1.6.42.jar
		* CoFHAPI|energy (1.8.9R1.2.0B1) from RebornCore-1.9-2.1.0.53-universal.jar
		* CoFHAPI|tileentity (1.8.9R1.2.0B1) from ProgressiveAutomation-1.9-1.6.42.jar
		* compactstorage (v2.0.0a) from compactstorage-2.1-1.9-rc.jar
		* IC2API (1.0) from RebornCore-1.9-2.1.0.53-universal.jar
		* journeymap|client-api (1.2-SNAPSHOT) from journeymap-1.9-5.2.0b1-unlimited.jar
		* journeymap|client-api-display (1.2-SNAPSHOT) from journeymap-1.9-5.2.0b1-unlimited.jar
		* journeymap|client-api-event (1.2-SNAPSHOT) from journeymap-1.9-5.2.0b1-unlimited.jar
		* journeymap|client-api-model (1.2-SNAPSHOT) from journeymap-1.9-5.2.0b1-unlimited.jar
		* journeymap|client-api-util (1.2-SNAPSHOT) from journeymap-1.9-5.2.0b1-unlimited.jar
		* JustEnoughItemsAPI (3.1.0) from jei_1.9-3.3.3.199.jar
		* pressureAPI (1.3.1.13) from pressure-1.3.1.13-mc1.9.jar
		* PsiAPI (2) from Psi-beta-31.jar
		* reborncoreAPI (2.1.0.53) from RebornCore-1.9-2.1.0.53-universal.jar
		* TailsAPI (1.1.1) from Tails-1.9-1.6.1.jar
		* techrebornAPI (1.0.6.197) from TechReborn-1.9-1.0.6.197-universal.jar
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by LimeTheOn** [comment]
Yeah, tried newest forge with only harvestcraft same thing happening, went back till fml.1895 and the crash is gone, if I find something related I'll report back to you ^^

**Comment by GSValore** [comment]
Forge 1896 added a new LootTable system that changes the classes called here, resulting in a crash.  It'll be something to be aware of when a new recommended version comes out or an update is necessary.

**Comment by LimeTheOn** [comment]
Now that you mention it I kinda remember that from the change logs it even stated that inproper use will result in an exception... but I red them at about 6am yday must have slipped my mind :D thanks for the reminder :) so far 1.9 feels great(making modpack for my community) only BoP giving me a headache :P

**Comment by asiekierka** [comment]
Can confirm.

**Comment by EnderT5** [comment]
same happens to me (forge-1.9-12.16.1.1901)

http://pastebin.com/EnHpqixp

**Comment by lebertran** [comment]
Fixed in fork above and in the next release. Until then, use Forge 1895 (or earlier) as @LimeTheOn suggests.

**Comment by b0bst3r** [comment]
Can you push this please newer JEI releases require 1900 (or something I'm using does)

**Comment by lebertran** [comment]
A preliminary release is available in my fork. May contain bugs, though.

**Comment by b0bst3r** [comment]
Is there a compiled jar about somewhere?

**Comment by LimeTheOn** [comment]
https://github.com/lebertran/harvestcraft/releases

**Comment by b0bst3r** [comment]
thanks
