### ISSUE TITLE
[1.12.2] recipe conflict between soft pretzel and crackers

### ISSUE THREAD

**Issue by Water-Cat1** [MatrexsVigil/harvestcraft#97]
There is currently a recipe conflict between the soft pretzel and the crackers, with minecraft favouring the pretzel, making things that use crackers (like smores) unobtainable. The recipe is Bakeware, dough, butter and salt.

There is also a singular "cracker" item made with bakeware, flour, oil salt and water. This doesn't have any follow on recipes so could probably be used for the crackers instead.

**Comment by MatrexsVigil** [comment]
Fixed in 1.12.2d by adding listAllwater to Soft Pretzels
