### ISSUE TITLE
Trading with Market Crashes server w/ Log

### ISSUE THREAD

**Issue by domosplace** [MatrexsVigil/harvestcraft#98]
Playing Direwolf 20 1.12 using Pams version 1.12.2a jar. When trading for any item causes the world to crash. I have included a crash log. 

https://pastebin.com/qeNGZcfn

**Comment by alxcool** [comment]
Hi! I got lots of crash file to report the same issue : AL_COOL singleplayer using the old minecraft launcher as 1.12.2. (windows 7 64 bit.) Note : parts of a personal set of 90 mods (no packs.)

As a guess it look like the game crash is link to a time laps.
Could it be an incompatibility with an another mod?
as a guess incompatibility could include one of the following : 
-Aroma1997Core-1.12.2-1.3.0.2.jar (crash occur when market have an item or emerald inside his inventory. looks like the mod try to save the item as beeing inside of it, but the trade system is not built to keep any inventory. (like the enchantment table.) Crash could occur twice every minecraft day, only when manipulating items inside the trade block to sell.
-Bloodmoon-MC1.12.2-1.5.2.jar (seems to have some issue with light color and light level, or time of the day when a bloodmoon is about to occur.)
-ColorUtilityCorePlugin
-OpticPatchingLoader


Note : I may have done some mistake while writting as english is not my first language. I'l be happy to edit / update this comment if required. For more crash report , let me know I may have 20 about this single issue!
 https://pastebin.com/GxVaUqfh

**Comment by Flyrija** [comment]
I can't provide a crash log, but I encountered the same problem. Client and Server crash when trading for an item. I push the buy button -> item is bought but get's dropped instead of into my inventory and the game crashes.  I'm using Version 1.12.2a

I could prevent the crash by making sure that I have an empty slot on my Hotbar and put only the needed amount of emeralds for one trade into the market slot. With this, the trade works and the seed/sapling goes without into my Hotbar.

**Comment by alxcool** [comment]
Hi! I got some good news! Updating (not harvestcraft) but forge's version have almost resolved the problem! As I've said, I don't know exactly the reason why minecraft crash when I use not the market, but the shipping bin. (might be the same bug for both.) Example I place 16 rotten flesh inside the shipping bin, then when I click the action button, an emerald fly arround, never reach my inentory then the game crash. 

Whats new with forge version 2555 is when a problem occur with the trading system, you lose the items being manipulated, then the server won't crash anymore!

Here a change log page if someone's ask for, or is better at reading this log than me : https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.1.2555/forge-1.12.2-14.23.1.2555-changelog.txt
Here the page to update your forge's version : https://files.minecraftforge.net/

Thk again for this mod's autor as this mod is quite an awsome mod with full of unique ideas and lots of dedication!

**Comment by MatrexsVigil** [comment]
If you are still experiencing this crash after updating to HarvestCraft 1.12.2L and Forge 2555+, please re-post here: https://github.com/MatrexsVigil/harvestcraft/issues/127
