### ISSUE TITLE
1.12.2 Gardens spawn and spread like crazy!

### ISSUE THREAD

**Issue by katubug** [MatrexsVigil/harvestcraft#99]
I know there are config options to assist with this, but I didn't really understand what the numbers specifically meant, so I left them as default. There are dozens of (specifically Frost Gardens) coating every surface of every hill near my base. I ended up disabling them, as I have all the crops I need now, but hoo boy. It's nuts. There must be 100+ in our general base area.

**Comment by katubug** [comment]
I had to fly up quite high to show the whole area, but you can see there's a ton in the upper left, upper right, middle right, lower left, and another bit in the middle. These are only the visible ones. And I have already gone into creative to remove a lot of them.

![2018-01-02_21 33 19](https://user-images.githubusercontent.com/20935286/34508409-94eb1078-f004-11e7-8eb5-4c11107d829e.png)

**Comment by MatrexsVigil** [comment]
How long did this take to grow?  Just lower the config option from 30 to 10 or even 5 I guess?

**Comment by katubug** [comment]
This was over a few irl days, I'd guess. I ended up just disabling them
entirely, since I bought all the seeds I needed from the market block
thing.

**Comment by MatrexsVigil** [comment]
Okay.  I will mark this closed as this can be changed in the config, but I will test to see if the default is set too high (and change if needed).
